### ISSUE TITLE
Timeouts on SUBSCRIBE opcodes

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#122]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
/usr/local/lib
└─┬ storjshare-cli@3.0.4
  └─┬ storj@0.6.15
    └── kad@1.5.10
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
I have 27 of 81 opcodes in my config file.
I would expect 27 opcode SUBSCRIBE messages to each node.
(some bonus SUBSCRIBE for tunnel and other stuff like that)
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
FIND_NODE returns 3 nodes.
My node would like to send all opcode SUBSCRIBE messages to all 3 nodes at the same time.
My CPU is at 100% and to slow for that job. At the end I am getting more and more timeouts.
A short brake between the opcodes would be nice.
That would allow me to send all SUBSCRIBE without timeouts and it would allow me to answer the 27 SUBSCRIBE of my neigbor node without timeouts.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Configure some more opcodes. On a fast system use all 81 possible opcodes.
2. Start the node and look for timeouts.

**Comment by gordonwritescode** [comment]
Added a `SUBSCRIBE_THROTTLE` constant that will place a default of 3 second wait between `SUBSCRIBE` messages sent as part of `FarmerInterface` initial network join: https://github.com/Storj/core/pull/115

**Comment by littleskunk** [comment]
My node will love you for this :)
