### ISSUE TITLE
offline nodes not removed from contact list

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#131]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
/usr/local/lib
└─┬ storjshare-cli@3.0.5
  └─┬ storj@0.6.16
    └── kad@1.5.10
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
3 isolated nodes connected to each other.
node 3 goes offline. I would expect that node 1 and 2 remove the offline node from there contract list.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Node 1 and 2 try to send messages to node 3. The result is always a timeout.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Setup 1 isolated node with no connection to any other node.
2. Start node 2 and node 3 connected to node 1.
3. Stop node 3.
4. Wait 15 minutes and take a look into the logfile. Node 1 and node 2 will try to send PUBLISH messages to the offline node. Both will get timeouts.

**Comment by gordonwritescode** [comment]
Are you sure the contact does not get dropped after the timeouts occur? Since contacts don't maintain an active connection to each other, nodes do not discover that a contact has gone offline until it receives a timeout or other connection error.

**Comment by littleskunk** [comment]
Yes I am sure. Node 1 and 2 are not stopping it. They are getting timeouts but they try it again and again.

**Comment by gordonwritescode** [comment]
Thanks, you're right, looks like we don't drop them after timeout: https://github.com/kadtools/kad/blob/8d8e86f927ac771924c1fc4fdb5328c19abd2e9c/lib/rpc.js#L307-L311

**Comment by gordonwritescode** [comment]
We need to make sure this gets called: https://github.com/kadtools/kad/blob/master/lib/router.js#L129

**Comment by gordonwritescode** [comment]
Issue moved: https://github.com/kadtools/kad/issues/59
