### ISSUE TITLE
api.storj.io nodeID are changed faster than we can pull out new releases

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#142]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
/usr/local/lib
└─┬ storjshare-cli@3.0.6
  └── storj@0.6.16
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Stable api.storj.io nodeids for a stable network.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
The api.storj.io nodeids are changing on every bridge update.
We can't pull out new storjshare-cli and storjshare-gui releases that fast.
We need stable nodeids or nobody is able to connect.
CLI user replaced the outdated api.storj.io nodesids with some other user nodes.
That way the CLI user create an isolated network with no connection to api.storj.io.
New nodes can't join that isolated network.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Write down the current api.storj.io nodeids.
2. Wait a few days and try to connect with the old nodeids.
3. Try to keep your nodeid list up to date.

**Comment by littleskunk** [comment]
@phutchins Can you give me the current nodeids please. That will not fix this issue but that will allow the user to update there config files and connect again.

**Comment by bookchin** [comment]
I know that this goes without saying, but loosing the bridge private key is a huge problem as it would mean we'd no longer be able to negotiate DataChannels or perform audits for the bridge users. So going forward the nodeID for the bridge renters should not change. 

But more the point if this issue, it's a little silly that our bridge server is the only used entry point for the network. I'd propose setting up a means to discover seeds similar to bitcoin's DNS seeds. 

For now, how about we keep a `seeds.txt` in the core repo and keep a list of known good seeds there. We can use that list as the default seeds in the `Network` class to avoid this issue.

**Comment by littleskunk** [comment]
We can use http://api.storj.io/contacts to discover seeds.

**Comment by bookchin** [comment]
I've been considering pulling the bridge client into core anyway since it already heavily relies on core. I think I will go ahead and do that and expose a way to give it to the `Network` class for automatic peer discovery.

**Comment by bookchin** [comment]
Closing and tracking at #144. You can get the current nodeID by doing `GET /` at the bridge and using the `x-network-seeds` property.
