### ISSUE TITLE
Add Unlockkeyring Command

### ISSUE THREAD

**Issue by super3** [Storj/core#147]
### Actual Behavior

Currently the user has to enter in the passphrase every single time they want to upload a file. 

```
$ storj uploadfile 573b4ce25da55fc8715b4c5a cat.jpg
 [...]  > Enter your passphrase to unlock your keyring  >  ******
$ storj uploadfile 573b4ce25da55fc8715b4c5a cat.jpg
 [...]  > Enter your passphrase to unlock your keyring  >  ******
$ storj uploadfile 573b4ce25da55fc8715b4c5a cat.jpg
 [...]  > Enter your passphrase to unlock your keyring  >  ******
```

### Expected Behavior

User is able to unlock their keyring for x number of seconds [like Bitcoin](https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list). Good compromise between security and user experience. 

```
$ storj unlockkeyring <passphrase> <timeout in seconds>
$ storj uploadfile 573b4ce25da55fc8715b4c5a cat.jpg
$ storj uploadfile 573b4ce25da55fc8715b4c5a cat.jpg
$ storj uploadfile 573b4ce25da55fc8715b4c5a cat.jpg
```

**Comment by utdrmac** [comment]
I can see there is currently no glob support: (ie: uploadfile /path/to/files/*.jpg). Attempted to work around this by using

```bash
for i in `ls -1 /path/to/files/*.jpg`; do storj uploadfile <bucket> $i; done
```

but cli asks for password each time and using -k is a bit insecure since it is added to bash history. +1 for this timeout support or even reading password from a file maybe?

**Comment by super3** [comment]
This would require major changes to the tools that we can't focus on right now.

**Comment by utdrmac** [comment]
What would be the proper way then to upload batches of files from CLI?

**Comment by super3** [comment]
@utdrmac At this point I use a bash script. There more proper ways to do it, but for example this is a script that I use:

```
#!/bin/bash
while true;
do
        dd bs=1024 count=10240 </dev/urandom >upfile
        storj upload-file -k "123456" 5745e8e64294714908887281 upfile
        rm upfile
done
```
