### ISSUE TITLE
Mock audit to the API

### ISSUE THREAD

**Issue by harryio** [Storj/core#149]
Trying to upload file through [Storj Api] (https://app.storj.io/#/dashboard/api-docs?_k=qc1mh8) by making call at endpoint `/frames/{frame_id}` from an android client but the call requires computing  `challenges` and `trees` for which there is currently no recourse in Java.

Need mock values for said parameters to test uploads/downloads before implementing the audit feature.

**Comment by bookchin** [comment]
See the protocol specification and corresponding examples in the audits section. 

https://storj.github.io/core/tutorial-protocol-spec.html

**Comment by harryio** [comment]
@bookchin Tried api call with mock values generated from code available [here] (https://storj.github.io/core/lib_auditstream.js.html) but getting `{"error":"Invalid tree supplied"}` as response. Following are the values generated:

**Challenges**
```
String challenges[] = {"3190a47d72d219859f3cda01fa26a761c962ba23f605c74ea1c479375830f64b",
                       "a55756987f4254653468b24e55701cac70cb8275d33bad1417edee25e458fccd",
                       "a730c99ff7e13c357b2d4619fb0bbe1b3001ba6a3f3f39adf1398c414969ea85",
                       "107fbd626c3e88b5ed156be7939c8eb7c2c64327884f8f01dd36c2c810218912",
                       "17bdae3102a43bcb2801542eac5fe7bd4e838a34c95084f677a69ac3395baeef",
                       "a2c31c36708beb39ccff74b211f38bfcd8dfee9e72ad55bebffede214644bc8f",
                       "9cc091d6403e5ecec7d914a1021e54f779af8f2b9b534b9c8ec169a5fe272566",
                       "c1054a8557727a140175e6ec913329889ef2f3dca0a4cb35e01ab16cf5bc1ff4"};
```

**Trees**
```
String trees[] = {"73f1d819dbaed08762dd1ca48db78dd8e72bfa30",
                  "8abe243009fe3bb6dcff6b7692dc155ca943fa45",
                  "f40a999d28b93bad846674fd7b387d632115d8bf",
                  "e8024d537174b2410544312c1a1dca3085961775"};
```

**Comment by bookchin** [comment]
Check the format of your request: https://github.com/Storj/core/blob/master/lib/auditstream.js#L150

**Comment by harryio** [comment]
@bookchin Oops! It was a typo. That solved the `Invalid tree supplied` error. Thanks! However, replaying the same request, gives error `Challenges and tree do not match`. So I tried the request with only first 4 challenges, but it resulted in a **502 Bad Gateway**. Here's the stacktrace for the api call:

```
D/OkHttp: --> PUT https://api.storj.io/frames/57587d7ea320d265222a9495 http/1.1
D/OkHttp: Content-Type: application/json; charset=UTF-8
D/OkHttp: Content-Length: 588
D/OkHttp: x-signature: 3046022100b3c4d93cc23bd95eb266b2f4b072b2f48bbb01635d1dc0ffd74859c04153e2fc0221009ceb7f92b4c890d32b6d62a625e48dcf34615a269447c8e53213bed2a7fed2f4
D/OkHttp: x-pubkey: 04aca9ce9f3bb2919c5e8df1bdc30684d966bc924f7a8d1cb11935267505a32cffb22326aa491616bbe2fac7ad238158d36a5d164b6acc9b04d4e0de7acc112829
D/OkHttp: {"__nonce":1465417083914,"challenges":["3190a47d72d219859f3cda01fa26a761c962ba23f605c74ea1c479375830f64b","a55756987f4254653468b24e55701cac70cb8275d33bad1417edee25e458fccd","a730c99ff7e13c357b2d4619fb0bbe1b3001ba6a3f3f39adf1398c414969ea85","107fbd626c3e88b5ed156be7939c8eb7c2c64327884f8f01dd36c2c810218912"],"hash":"9366e4595aa3b9ada9829573bb9ad7a400b7b3b654b3a602d5b8dec9f222cc90","index":0,"size":2097155,"tree":["73f1d819dbaed08762dd1ca48db78dd8e72bfa30","8abe243009fe3bb6dcff6b7692dc155ca943fa45","f40a999d28b93bad846674fd7b387d632115d8bf","e8024d537174b2410544312c1a1dca3085961775"]}
D/OkHttp: --> END PUT (588-byte body)
D/OkHttp: <-- 502 Bad Gateway https://api.storj.io/frames/57587d7ea320d265222a9495 (525ms)
D/OkHttp: Server: nginx/1.10.0
D/OkHttp: Date: Wed, 08 Jun 2016 20:18:07 GMT
D/OkHttp: Content-Type: text/html
D/OkHttp: Content-Length: 173
D/OkHttp: Connection: keep-alive
D/OkHttp: OkHttp-Sent-Millis: 1465417084010
D/OkHttp: OkHttp-Received-Millis: 1465417084487
D/OkHttp: <-- END HTTP (173-byte body)
```

Also, as it is mentioned [here] (https://github.com/Storj/core/blob/master/lib/auditstream.js#L14) that the  audits are the number of challenges to generate, so when generating these challenges number of audits were set to 4, but 8 challenges were generated.

**Comment by bookchin** [comment]
You used core to generate the challenges? The tree is created from the challenges so you should always get the same number of each.
