### ISSUE TITLE
Uploading same file results in duplicate file

### ISSUE THREAD

**Issue by utdrmac** [Storj/core#155]
### Package Versions
```
root@gasgiant:/usr/src# npm -g list storj
/usr/lib
├── storj@1.1.0
└─┬ storj-bridge-client@0.5.2
  └── storj@1.1.0
Node: v4.4.5
```

### Expected Behavior
Uploading the same file twice should not result in two files inside my bucket. Would have expected Storj to do some sort of checksum on the file to be uploaded and verify that it doesn't already exist on the network.

```
root@gasgiant:/usr/src# md5sum get-pip.py
6ad553aac431bab122faeed96a349cd2  get-pip.py
root@gasgiant:/usr/src#
root@gasgiant:/usr/src# storj uploadfile 575869851f545db43016498d get-pip.py
 [...]  > Enter your passphrase to unlock your keyring  >  ***********

 [info]   Generating encryption key...
 [info]   Encrypting file "get-pip.py"
 [info]   Encryption complete!
 [info]   Creating storage token...
 [info]   Storing file, hang tight!
 [info]   Cleaning up...
 [info]   Encryption key saved to keyring.
 [info]   File successfully stored in bucket.
 [info]   Name: get-pip.py, Type: application/octet-stream, Size: 1412743 bytes, ID: 57586dd11f545db430164a1a
root@gasgiant:/usr/src#
root@gasgiant:/usr/src# storj uploadfile 575869851f545db43016498d get-pip.py
 [...]  > Enter your passphrase to unlock your keyring  >  ***********

 [info]   Generating encryption key...
 [info]   Encrypting file "get-pip.py"
 [info]   Encryption complete!
 [info]   Creating storage token...
 [info]   Storing file, hang tight!
 [info]   Cleaning up...
 [info]   Encryption key saved to keyring.
 [info]   File successfully stored in bucket.
 [info]   Name: get-pip.py, Type: application/octet-stream, Size: 1412743 bytes, ID: 57586ded1f545db430164a26
root@gasgiant:/usr/src#
root@gasgiant:/usr/src# storj listfiles 575869851f545db43016498d | grep pip
 [info]   Name: get-pip.py, Type: application/octet-stream, Size: 1412743 bytes, ID: 57586dd11f545db430164a1a
 [info]   Name: get-pip.py, Type: application/octet-stream, Size: 1412743 bytes, ID: 57586ded1f545db430164a26
```

### Actual Behavior
See above. Same file uploaded twice results in duplicate files on network.

### Steps to Reproduce
See above. Upload same file multiple times to same bucket.

**Comment by bookchin** [comment]
Each upload is encrypted with a unique key/iv before being distributed or reported to the bridge for tracking, so they are actually not the same file (as far as anyone but you is concerned) and the bridge has no way of knowing that it is a duplicate.

**Comment by utdrmac** [comment]
So how would I, an end user, prevent multiple copies of the same files from being uploaded? Consider a backup utility that runs nightly. If 99% of the files don't change, why would I want to upload duplicates to my storj bucket?

Is there something I could do before uploading to determine a duplicate? Is there a local cache stored where I could compare a checksum-based manifest?

**Comment by bookchin** [comment]
Yes, a sync/share or application built on storj would want to implement some sort of local cache or other mechanism for de-duplicating files, but I think it's out of scope for the core library and CLI tool to handle. 

We are focused on building the groundwork and infrastructure on which developers can build the end-user focused tools.

**Comment by utdrmac** [comment]
Ok. Just to be certain I understand, there's no way to retrieve metadata about a file stored in Storj that would contain some sort of usable hash? The [API docs](https://storj.github.io/bridge/#!/buckets/get_buckets_id_files) indicate a hash is available but in some testing I just did, that hash isn't present in the JSON response. Will this hash eventually be added to the response?

I'm thinking about the case where my local cache gets removed and I have to recreate it (ie: laptop stolen, hard drive dead, rm'd cache). It would require downloading every file in each bucket, temporarily, calculating and recording the hash, then removing the file. If one has TBs of data in storj, this would take a very long time to rebuild.

I've done some testing with Amazon Cloud Drive and they provide the MD5 of each file uploaded as metadata (so does Google drive, M$ drive, etc) so that you can compare without having to download the entire file.

**Comment by super3** [comment]
Amazon Cloud Drive, Google Drive, M$ Drive are all top level applications. They would calculate the hash of the file and store it in the app. That is the job of the _application_, not the data layer. 

Two things to note:
1) The API never touches the data. This is way different from all the other applications that actually touch the data. How can the API have the hash, if it can't touch the file?
2) We live by Privacy by Design principles. If we stored the hash of the data then we could tell what all your files were. We don't want to know this information. We take your privacy and security very seriously. 

It comes down to would like a private and secure system, or the top level application have to write a few extra lines of code.

**Comment by utdrmac** [comment]
Thanks @super3 If the API never touches the data, how does it know mimetype, filename, and filesize? Can't the API know the hash in the same way it knows these pieces of information? And if you calculated/stored the hash based on file contents and my key, wouldn't that make it impossible for you to identify my files?

Speaking of 2) I was quite surprised to read this statement and yet be able to see my entire file list on the web app gui. The first thing I thought was, "ah, I see they have access to my file list" which is probably not true, yet the end-user experience was exactly the same as all other cloud-drive providers (ie: load webpage, log in, see files).

**Comment by super3** [comment]
Those are pushed into the API from the client. Later on will probably encrypt those so that only the user can read it and not us. It its important to know that those are labels. If its labeled cata or catb, really has no consequence on the file. 

Why does the API have to do that? Why can't the application do that and decide its scheme?

Web App GUI is just an application itself. To be clear we are not making a cloud drive here, we are making an object storage platform on which applications like cloud drives are built.

**Comment by utdrmac** [comment]
Well, I just re-watched your promo video and everything about it screams "cloud drive"; especially since the video calls out Google Drive, Dropbox and Amazon as comparisons. The girl's voice never says anything about "object store" but instead says "files". A discussion not for here.

Back to topic, any object storage platform should provide a safety measure for each block stored in it, no? Where's the guarantee from the platform that what I uploaded was actually stored? If I store a 1MB object and the platform simply says OK, I have no guarantee knowing the file is correct (ie: not corrupted) unless I re-download that file and compare checksums/hashes. You can't possibly be suggesting that someone who is storing 100TB of objects must re-download each object immediately after having uploaded it, just to verify that it was stored properly.

**Comment by bookchin** [comment]
To be clear, we *do* know the hash of the individual shards that compose a "file" (which is just a metadata entry that includes the mimetype and name and size that you *declare*). 

But since each shard you distribute is uniquely encrypted before you declare any metadata to bridge, the hashes will always be different.

**Comment by utdrmac** [comment]
@bookchin Ok, file is sharded locally, each shard encrypted locally, then sent out to the network with some associated metadata, provided by the user/app.

Where is the guarantee that each shard is written correctly? If I happen to get 1 of 36 shards of your "file" and it gets corrupted on write to my HDD, how does your end client (storjcli for example) know that 1 block/shard failed and the remaining 35 shards on 35 other hosts should be removed? Or does the "network" know that block write failed and it attempts that block write on another host (thus the network guaranteeing that all writes are atomic)?

**Comment by utdrmac** [comment]
And there's no way for the end-user API to initiate one of these audits? I've got a file on my laptop that I uploaded a month ago. Hasn't changed but I want to validate it still exists on the network; can I do that without downloading the entire file locally?

I'm taking from your statement that shard/block writes are guaranteed by the network, correct? How often are audits performed?

**Comment by super3** [comment]
We do that automatically on our side, but yes you the user/application can do that independently of us. Basically you would generate some additional audits, and then issue them whenever you would like.

Up to the contact. Could be once an hour(super important document), could be every week(backup that you will probably never use ever again).

**Comment by utdrmac** [comment]
Is there documentation on how to do/initiate those audits and the information I get back? Knowing I can initiate an audit and get some sort of validation that a file is good and exists, my current thinking is to upload files to the network, saving a local hash for cache, fork off a background thread that routinely audits each file to guarantee it exists in the network every X minutes (where X is determined by their subscription level in my app).

**Comment by super3** [comment]
Yes, command line tool: https://storj.github.io/core/tutorial-command-line-interface.html 
Protocol: https://storj.github.io/core/tutorial-protocol-spec.html, https://storj.github.io/core/tutorial-renting-data.html

**Comment by utdrmac** [comment]
```bash
root@gasgiant:~# storj -V
1.1.0
root@gasgiant:~# storj prepare-audits 2 testFile.txt
 [error]  Unknown command "prepare-audits", please use --help for assistance
```

Same for prove-file and verify-proof

**Comment by super3** [comment]
@utdrmac These are new commands in v.1.2.0, which was pushed out 3 hours ago. You have to upgrade.
