### ISSUE TITLE
Storjshare keygen should save id_ecdsa file

### ISSUE THREAD

**Issue by BlackDuck888** [Storj/core#158]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
/usr/local/lib
└─┬ storjshare-cli@4.0.1
  └── storj@1.1.0
```

Replace the values below using the output from `node --version`.

```
v4.4.3
```

### Expected Behavior

`storjshare` should save an encrypted id_ecdsa file. As farmer the id_ecdsa is needed for a setup, only the output to stdout did not help a farmer to setup a host. There is no use case for this information.

**Comment by bookchin** [comment]
The setup generates a keypair automatically, so i agree that the `keygen` command is not useful in the context of storjshare-cli. It was added as a utility, and is now the `generate-key` command in the `storj` CLI, now it's probably better to remove it from `storjshare`.

**Comment by BlackDuck888** [comment]
if it take a password as argument and save it as id_ecdsa it would a nice feature for storjshare-cli, it make it easier to setup a farmer unattended.

**Comment by bookchin** [comment]
I'd rather not duplicate functionality right now, but I'm happy to add support for this to the `storj generate-key` command.

**Comment by BlackDuck888** [comment]
this is also a good solution!

**Comment by bookchin** [comment]
@BlackDuck888 

```
storj generate-key --save path/to/key --encrypt somepassword
```

```
storj generate-key --help
```

**Comment by BlackDuck888** [comment]
awesome
