### ISSUE TITLE
Allow arbitrary payment address to be given to FarmerInterface

### ISSUE THREAD

**Issue by bookchin** [Storj/core#159]
We are still defaulting the payment address to the one that is derived from the `KeyPair` passed to `FarmerInterface`: https://github.com/Storj/core/blob/master/lib/interfaces/farmer.js#L137

That's fine and all, but we need to allow users to specify a different payment address for adding to contracts if they wish. While right now nobody is at risk to lose funds (as long as the private key is kept - as always), users who wish to use an existing address or are conscious of privacy regarding others knowing the funds possessed by a given node should be able to change it.

**Comment by super3** [comment]
In the context of TGC, the renter may evaluate the payment address(and its balance) to determine if it should give a contract to that user or not.

**Comment by bookchin** [comment]
Of course, but if the farmer wished to periodically change the address, she should be able to do that. Right now she cannot, instead having to import her node's ECDSA key into a wallet.

**Comment by super3** [comment]
As it works now that would be her private key? Ideally she would use this to put an arbitrary payment address, and not have to expose her private key to the farming software, correct?

**Comment by bookchin** [comment]
Correct, I'd like to add `payment` section to options that would have an `address` field to supply any address (and later more fields for other things like storage and download price).

If no address is supplied, we can still default to the address derived from the nodeID, which can be used to access funds using the node's private key, but ideally the application layer will push users to supply their own (if not require it).

**Comment by super3** [comment]
I worry about the security in the long run of the farmer storing any coins. You use the node id keypair really often. Much harder to secure it if its always in memory for operations.

**Comment by bookchin** [comment]
Right... Which is why I opened this issue.

**Comment by super3** [comment]
As in if we should even allow an address to be derived from the nodeID. On the other hand, it could be useful. Would allow the farmer to pay for tunneling and other services. Just got to make sure nothing significant is on that address.

**Comment by bookchin** [comment]
There is no reason to remove the functionality from core or force supplying an address at the library level. The latest releases of storjshare use the address provided. The GUI requires one to be supplied. This is an application layer issue now, since I've made it possible to supply an address.
