### ISSUE TITLE
Unable to retrieve a list of bucket files via 'list-files' command

### ISSUE THREAD

**Issue by ShaunHoyes** [Storj/core#161]
### Package Versions

```
/Users/Home
└── storj@1.2.1
```

```
v4.4.4
```

### Expected Behavior

When trying to get a list of files within a particular bucket, I expect to see a list of files (including file names) after using the following command:

```
$ storj list-files <bucket>
```

### Actual Behavior

It is unclear if the command directions are referring to the bucket name or bucket ID, but both scenarios do not seem to work. When using the command above, I get the following message:

```
$ [warn] There are not files in this bucket.
```

I do have an account with one bucket created. This command seems to have been working last week.

### Steps to Reproduce

The same command:
```
$ storj list-files <bucket>
```

**Comment by bookchin** [comment]
Bucket entries were dropped from the DB due to backwards incompatible changes. Bear with us while we are in beta.
