### ISSUE TITLE
UPNP does not open tunnel gateway ports

### ISSUE THREAD

**Issue by BlackDuck888** [Storj/core#164]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
/usr/local/lib
└─┬ storjshare-cli@4.0.2
  └── storj@1.2.1
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

I expect that UPNP open all necessary ports (Client/Farmer, Tunnelserver, Tunnelgateway)

### Actual Behavior

Only Client/Farmer and Tunnelserver ports are forwarded via UPNP.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start storjshare-cli with ports set to 0 and local ip
2. Check your firewall and the upnp settings

**Comment by bookchin** [comment]
Gateway ports get forwarded at the time they are opened: https://github.com/Storj/core/blob/master/lib/network/protocol.js#L389

However, it is keyed on the `_isPublic` property which we set to `true` once the initial port mapping succeeds, thus causing the gateway ports to not get forwarded: https://github.com/Storj/core/blob/master/lib/network/transport.js#L69

Thanks for reporting.
