### ISSUE TITLE
Too Many Open Files

### ISSUE THREAD

**Issue by subwolf** [Storj/core#165]
I'd recently upgraded the NAS to the latest Synology DSM. Got an email like this earlier today:

````
A new exception has been thrown
Server: storj-nas
Application: storjshare
Stack trace:
WriteError: IO error: /root/.storjshare/farmer.db/1532571.log: Too many open files
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/levelup/lib/levelup.js:254:34
````

The open files limit has reset to 1024. Are elements of the shards being opened and not closed? Maybe this belongs under kad.

**Comment by bookchin** [comment]
Could be happening during a LevelDB compaction. Will dig around. Its not in kad, its coming from the LevelDB storage adapter.

**Comment by bookchin** [comment]
Looks like I can set the LevelDB driver's `maxOpenFiles`. By default it's 1000, which gives your system a whopping 24 for anything else.

I'll default it to 512, and make it configurable.

**Comment by bookchin** [comment]
@subwolf, just following up again. is this issue still persisting?

**Comment by subwolf** [comment]
Not so far.

**Comment by bookchin** [comment]
Okay, closing for now - reopen if it shows up again.
