### ISSUE TITLE
MAX CONCURRENT OFFERS default to high -> signature expired

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#185]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
/usr/local/lib
└─┬ storjshare-cli@4.0.3
  └─┬ storj@1.2.7
    └── kad@1.5.13
```

Replace the values below using the output from `node --version`.

```
v4.4.5.
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

Without the last 2 kad fixes the pending offer list was full with searching for renter. Less than 50% will transfer a shard later. More than 50% will fail but even that needs a few seconds. The default value for MAX CONCURRENT OFFERS was optimized for this situation.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

The 2 kad fixes have a hugh impact. Now my node doesn't search for renter. The result is that I have up to 6 pending shard transfers. My CPU can't handle it. My log was full of signature expired. I had to reduce it to 4 pending offers. Now my node is working stable. I assume other nodes will have the same problem. We should set the default value to 3.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start node with default max concurrent offers and keep it running for an hour.
2. Count the number of signature expired.

**Comment by bookchin** [comment]
Good sleuthing @littleskunk - I think you are right, I'll change the default back to 3.

**Comment by phutchins** [comment]
We may should look into making this smarter and adjust itself as necessary. Maybe we could watch the delay in the event loop to see what the load is like and adjust accordingly.

**Comment by super3** [comment]
@littleskunk This is a CPU bound issue correct? If so can you provide your CPU specs for reference.

**Comment by littleskunk** [comment]
Intel® Celeron® 2.41GHz dual-core processor

4 concurrent offer and my cpu is at 100%. 3 would be safe for me.
