### ISSUE TITLE
To many dropping late response and timeouts

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#193]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
/usr/local/lib
└─┬ storjshare-cli@4.0.3
  └─┬ storj@1.2.7
    └── kad@1.5.13
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

My node is running with concurrency = -1. My node will not send any OFFER messages. CPU at ~25%. I would expect a few timeouts because other nodes are running at 100%. It should effect only a few nodeIDs.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

I see to many timeouts. After 10 minutes I copy the log and start analysing it. Here are the results.
253 sending PUBLISH
10 sending FIND_NODE
17 sending SUBSCRIBE
15 sending UPDATE
0 sending PING
295 queueing callback
73 timed out
73 removing from shortlist
59 dropping late response

~25% of the messages timed out but most of them because dropping late response. It looks like the timeout is a littlebit to low.

I did the same with blackduck. He is getting ~13% timeout. The difference between us is the CPU power and latency.

[10minutes.txt](https://github.com/Storj/core/files/323424/10minutes.txt)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start node with loglevel debug and concurrency -1
2. Count queuing callback and compare it with timed out.

**Comment by littleskunk** [comment]
Increasing the timeout didn't help. I am not sure what the reason for this is but here are some more log examples.

Same setup for my node but with the latest version my node is running with ~5% CPU (leveldb job not running at startup)

1.) Publish my tunnel gateway ports. 3 sending PUBLISH message. Received the second callback after 14 seconds. The first timed out without any answer and number three was send to a storj.dk server. I don't think that server has a problem. I received and dropped it after 30 seconds.
```
{"level":"info","message":"publishing message on topic \"0e01\"","timestamp":"2016-06-21T13:14:45.343Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.7.0\",\"address\":\"173.76.238.185\",\"port\":64204,\"nodeID\":\"ad5b6b06dfd839713680d354949455d3774d25b7\",\"lastSeen\":1466514885344}","timestamp":"2016-06-21T13:14:45.344Z"}
{"level":"debug","message":"queuing callback for reponse to b60ac8e68a6bdfaba770a4af60835823c8b807df","timestamp":"2016-06-21T13:14:45.433Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.7.0\",\"address\":\"204.111.240.84\",\"port\":4020,\"nodeID\":\"afc215a54d32372a5cd35b3effafa8b2d4d76a95\",\"lastSeen\":1466514885435}","timestamp":"2016-06-21T13:14:45.435Z"}
{"level":"debug","message":"queuing callback for reponse to 0f7a07d1cfa012b83c1aad1c952639829570fef8","timestamp":"2016-06-21T13:14:45.502Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.7.0\",\"address\":\"server012.storj.dk\",\"port\":5012,\"nodeID\":\"c0792c4c2dcac1582a6d01c93d1d366c5321d94e\",\"lastSeen\":1466514885503}","timestamp":"2016-06-21T13:14:45.503Z"}
{"level":"debug","message":"queuing callback for reponse to e1370fe7061357ce8392e282c1822b52df27ec35","timestamp":"2016-06-21T13:14:45.568Z"}
{"level":"warn","message":"missing or empty reply from contact","timestamp":"2016-06-21T13:14:45.706Z"}
{"level":"debug","message":"checking pending rpc callbacks for expirations","timestamp":"2016-06-21T13:14:51.013Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.7.0\",\"address\":\"204.111.240.84\",\"port\":4020,\"nodeID\":\"afc215a54d32372a5cd35b3effafa8b2d4d76a95\",\"lastSeen\":1466514899966}","timestamp":"2016-06-21T13:14:59.966Z"}
{"level":"debug","message":"updating contact {\"protocol\":\"0.7.0\",\"address\":\"204.111.240.84\",\"port\":4020,\"nodeID\":\"afc215a54d32372a5cd35b3effafa8b2d4d76a95\",\"lastSeen\":1466514899966}","timestamp":"2016-06-21T13:14:59.967Z"}
{"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-06-21T13:14:59.967Z"}
{"level":"debug","message":"checking pending rpc callback stack for 0f7a07d1cfa012b83c1aad1c952639829570fef8","timestamp":"2016-06-21T13:15:00.043Z"}
{"level":"debug","message":"checking pending rpc callbacks for expirations","timestamp":"2016-06-21T13:15:06.020Z"}
{"level":"warn","message":"rpc call b60ac8e68a6bdfaba770a4af60835823c8b807df timed out","timestamp":"2016-06-21T13:15:06.020Z"}
{"level":"debug","message":"removing contact {\"protocol\":\"0.7.0\",\"address\":\"173.76.238.185\",\"port\":64204,\"nodeID\":\"ad5b6b06dfd839713680d354949455d3774d25b7\",\"lastSeen\":1466514885344}","timestamp":"2016-06-21T13:15:06.020Z"}
{"level":"warn","message":"rpc call e1370fe7061357ce8392e282c1822b52df27ec35 timed out","timestamp":"2016-06-21T13:15:06.020Z"}
{"level":"debug","message":"removing contact {\"protocol\":\"0.7.0\",\"address\":\"server012.storj.dk\",\"port\":5012,\"nodeID\":\"c0792c4c2dcac1582a6d01c93d1d366c5321d94e\",\"lastSeen\":1466514885503}","timestamp":"2016-06-21T13:15:06.021Z"}
...
{"level":"info","message":"received valid message from {\"protocol\":\"0.7.0\",\"address\":\"server012.storj.dk\",\"port\":5012,\"nodeID\":\"c0792c4c2dcac1582a6d01c93d1d366c5321d94e\",\"lastSeen\":1466514916332}","timestamp":"2016-06-21T13:15:16.332Z"}
{"level":"debug","message":"updating contact {\"protocol\":\"0.7.0\",\"address\":\"server012.storj.dk\",\"port\":5012,\"nodeID\":\"c0792c4c2dcac1582a6d01c93d1d366c5321d94e\",\"lastSeen\":1466514916332}","timestamp":"2016-06-21T13:15:16.332Z"}
{"level":"debug","message":"contact not in bucket, moving to head","timestamp":"2016-06-21T13:15:16.332Z"}
{"level":"debug","message":"checking pending rpc callback stack for e1370fe7061357ce8392e282c1822b52df27ec35","timestamp":"2016-06-21T13:15:16.401Z"}
{"level":"warn","message":"dropping received late response to e1370fe7061357ce8392e282c1822b52df27ec35","timestamp":"2016-06-21T13:15:16.401Z"}
```

Here is another example. This time I did not search for the callback answer. I am looking for something that can cause a 30 seconds delay and I have a stupid theory. I received a PUBLISH message and I have to send an response somewhere. I can't see it on the log but I think it will be to late. The first step should be relay and answer the PUBLISH message. On the log example we can see that the negotiator is running first. With more cpu load this could delay the answer a few seconds.
```
{"level":"info","message":"received valid message from {\"protocol\":\"0.7.0\",\"address\":\"107.170.14.107\",\"port\":4000,\"nodeID\":\"0352b914a512c6e7dd37cd16d3c5256b8d181c9b\",\"lastSeen\":1466514374567}","timestamp":"2016-06-21T13:06:14.567Z"}
{"level":"debug","message":"updating contact {\"protocol\":\"0.7.0\",\"address\":\"107.170.14.107\",\"port\":4000,\"nodeID\":\"0352b914a512c6e7dd37cd16d3c5256b8d181c9b\",\"lastSeen\":1466514374567}","timestamp":"2016-06-21T13:06:14.567Z"}
{"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-06-21T13:06:14.568Z"}
{"level":"debug","message":"Received contract offer...","timestamp":"2016-06-21T13:06:14.569Z"}
{"level":"debug","message":"pending offers is less than concurrency: false","timestamp":"2016-06-21T13:06:14.572Z"}
{"level":"debug","message":"negotiator returned: true","timestamp":"2016-06-21T13:06:14.572Z"}
{"level":"debug","message":"we have enough free space: true","timestamp":"2016-06-21T13:06:14.572Z"}
{"level":"debug","message":"Not taking the contract...","timestamp":"2016-06-21T13:06:14.572Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.7.0\",\"address\":\"204.111.240.84\",\"port\":4020,\"nodeID\":\"afc215a54d32372a5cd35b3effafa8b2d4d76a95\",\"lastSeen\":1466514374572}","timestamp":"2016-06-21T13:06:14.572Z"}
{"level":"debug","message":"queuing callback for reponse to 4965235e41b34a94b1462f340caed69a69c94da9","timestamp":"2016-06-21T13:06:14.606Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.7.0\",\"address\":\"server012.storj.dk\",\"port\":5012,\"nodeID\":\"c0792c4c2dcac1582a6d01c93d1d366c5321d94e\",\"lastSeen\":1466514374607}","timestamp":"2016-06-21T13:06:14.607Z"}
{"level":"debug","message":"queuing callback for reponse to b365bbd2ce81332790748d04595b034e6a40266c","timestamp":"2016-06-21T13:06:14.668Z"}
```

And my bonus theory:
Even if my first theory is correct the increase timeout should have an effect but it has not. That is why I have a second stupid theory. Maybe my node is sending 3 PUBLISH messages and waiting for the callback befor it answer the received PUBLISH message? Increasing the timeout would allow the PUBLISH message to be send to some more nodes but at the end they will get the same number of timeouts.

**Comment by bookchin** [comment]
> Publish my tunnel gateway ports. 3 sending PUBLISH message. Received the second callback after 14 seconds. The first timed out without any answer and number three was send to a storj.dk server. I don't think that server has a problem. I received and dropped it after 30 seconds.

I don't know if I would be too sure, those nodes are busy little bastards. It took 30 seconds to get a response back, I think that's on him - nothing in the logs indicate to me an operation that would cause that sort of delay in callback execution.

> Here is another example. This time I did not search for the callback answer. I am looking for something that can cause a 30 seconds delay and I have a stupid theory. I received a PUBLISH message and I have to send an response somewhere. I can't see it on the log but I think it will be to late. The first step should be relay and answer the PUBLISH message. On the log example we can see that the negotiator is running first. With more cpu load this could delay the answer a few seconds.

The negotiator function just does a few simple truth checks and wouldn't block the process long enough to cause any issues: https://github.com/Storj/core/blob/master/lib/interfaces/farmer.js#L201-L211

> Maybe my node is sending 3 PUBLISH messages and waiting for the callback befor it answer the received PUBLISH message?

I don't think so, we acknowledge the sender before we relay anything: https://github.com/kadtools/kad-quasar/blob/master/lib/quasar.js#L236-L237

---

I have two theories also:

1. Due to [this performance issue](https://github.com/Storj/core/issues/201#issuecomment-227540232), nodes with more shards (like yours) take much longer to perform their capacity checks and that's what is causing the delay when receiving a series of contract publications (we run the capacity check after every saved contract).
2. The network is busy and high-traffic nodes like `*.storj.dk` are having trouble keeping up (which is another performance issue that I'm not quite ready to tackle), increasing the timeout to 30 seconds might shed some light on this.

Let's start by increasing the timeout again (to 30 secs) and see if my fix for https://github.com/Storj/core/issues/201#issuecomment-227540232 helps out at all. If not, back to the drawing board. Will include these in #202 and close this issue with it and (of course) we can reopen if not resolved.

**Comment by littleskunk** [comment]
Looks better now. 3% timeouts and 1% dropping late response with 3 concurrency offer.

**Comment by bookchin** [comment]
Great :) *whew*

**Comment by Th3Van** [comment]
Common for every storj.dk server : 

- 8 cores (Intel(R) Xeon(R) CPU X5675 @ 3.07GHz)
- 16 GB Ram

storj-bridge@0.8.4 /root/bridge
└─┬ storj@1.2.8
  └── kad@1.5.14 

![server012-15-06-2016_21-06-2016](https://cloud.githubusercontent.com/assets/18688983/16250556/9857426c-381e-11e6-957e-f48fee6a4dc4.png)
![server013-15-06-2016_21-06-2016](https://cloud.githubusercontent.com/assets/18688983/16250561/a2594b5c-381e-11e6-867e-8aeeedac8419.png)
![server014-15-06-2016_21-06-2016](https://cloud.githubusercontent.com/assets/18688983/16250565/a91c0952-381e-11e6-82a7-3fa270bc1cbe.png)
![server015 -15-06-2016_21-06-2016](https://cloud.githubusercontent.com/assets/18688983/16250567/aaac141a-381e-11e6-9f72-ef71486f98fb.png)
![server016 -15-06-2016_21-06-2016](https://cloud.githubusercontent.com/assets/18688983/16250568/ac2cd70c-381e-11e6-870d-52e3ca4f1ffc.png)
![server017 -15-06-2016_21-06-2016](https://cloud.githubusercontent.com/assets/18688983/16250570/ad8c7918-381e-11e6-94f9-3833ab2709d1.png)
![server018 -15-06-2016_21-06-2016](https://cloud.githubusercontent.com/assets/18688983/16250572/aefae802-381e-11e6-939a-27c3fe8b8407.png)
![server019 -15-06-2016_21-06-2016](https://cloud.githubusercontent.com/assets/18688983/16250574/b0ca5104-381e-11e6-94de-7eae55008f5d.png)
![server020 -15-06-2016_21-06-2016](https://cloud.githubusercontent.com/assets/18688983/16250576/b2dad48c-381e-11e6-83be-078d6122dc06.png)
![server021 -15-06-2016_21-06-2016](https://cloud.githubusercontent.com/assets/18688983/16250578/b4c1c5ee-381e-11e6-982d-6a847dbbd9a6.png)
