### ISSUE TITLE
Error is storage manager: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by lunokhod** [Storj/core#197]
~~~~
StorjShare: 4.0.4
Core:       1.2.8
Protocol:   0.7.0
~~~~
I've been running the new cli version behind a firewall, and everything appears to be working perfectly. In looking through the logs, I see a few errors that look like this, which don't look great:
~~~~
{"level":"error","message":"Error is storage manager: ENOENT: no such file or directory, stat '/Volumes/Luna-24/storj/farmer.db/015396.ldb'","timestamp":"2016-06-21T08:44:40.003Z"}
~~~~
Also, the only other "errors" I am getting are the following:
~~~~
{"level":"error","message":"RPC with ID `e77f737cffd2ddfdfe79c1ca6a2c618b52d37ef3` timed out","timestamp":"2016-06-21T08:31:50.085Z"}
{"level":"error","message":"Contract no longer open to offers","timestamp":"2016-06-21T08:28:37.470Z"}
~~~~
I wonder if these latter two should be recategorized as "warn".

**Comment by bookchin** [comment]
Duplicate: https://github.com/Storj/storjshare-cli/issues/79

Also, yes, I agree that those last two should probably be warnings.
