### ISSUE TITLE
[error]  Failed to establish tunnel, reason: No tunnelers were returned

### ISSUE THREAD

**Issue by lunokhod** [Storj/core#198]
~~~~
StorjShare: 4.0.4
Core:       1.2.8
Protocol:   0.7.0
~~~~
Everything works fine for about 2 hours, but then the client exits because no tunnelers were found (this has happened several times...):
~~~~
{"level":"warn","message":"tunnel connection lost, reason: socket hang up","timestamp":"2016-06-21T11:13:18.151Z"}
 [error]  Failed to establish tunnel, reason: No tunnelers were returned
~~~~
Perhaps I am being naïve, or I just don't know what is going on, but it seems to me that this should never happen....

In my config file, I have a list of seeds, and in the worst case scenario, the client should cycle through these to see if there are any new tunnels. I presume that the list of open tunnels changes all the time, so checking back once every minute would be a last-ditch effort instead of simply exiting. In the worst case, the client should probably instead print a warning like "No tunnelers available. Rechecking in 1 minute...."

**Comment by bookchin** [comment]
I've been experiencing this as well. It looks like many nodes that are tunneled themselves are announcing their willingness to tunnel (which does not work).

Next up.

**Comment by lunokhod** [comment]
This is working much better now! However, I ran into a situation where my internet connection was cut for about two hours. In looking at the log files, it appears that about 20 OPEN_TUNNEL attempts were tried when I didn't have a connection, and then the client gave up and exited.

At this point, this is a very minor issue. Nevertheless, a better behaviour might be to instead "check in" every 5 minutes to see if a new connection could be established. Otherwise, after the client exits, it will be necessary to restart it somehow.
