### ISSUE TITLE
Renter CLI unable to login with special characters

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#200]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
/usr/local/lib
├─┬ storj@1.2.8
│ └── kad@1.5.14
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

I followed the guide to install storj cli. On step 4 (https://storj.readme.io/#4-pairing-a-device-with-your-account) I have problems with my password. The webinterface is working. My password must be correct. I tryed password and HASH.

I assume the problem is my password manager.
Example password (I hope github will display it correct)
`çò1¦Ûò(V»ö¢çNiSà.úºµ¨ó0VO/b)b8røs>5ïï¤Ó:'ORñb÷î×IÌ¹U@%#¾üöí²qbLL`

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
 [error]  Invalid email or password
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Use a password generator

**Comment by vmatekole** [comment]
@littleskunk  e.g. of mine from lastpass, same length, changed chars of course but same type  ﻿Lu5vXXX8v6nt2Fuf^czJPsR#LwiX2oLLLq44FU3m

**Comment by bookchin** [comment]
Strange, the CLI and the web interface both use the same code to hash the password and send it [`BridgeClient`](http://storj.github.io/core/BridgeClient.html). I will try to reproduce.
