### ISSUE TITLE
Feature request signature expired error message on joining network

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#206]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
└─┬ storjshare-cli@4.0.4
  └─┬ storj@1.3.0
    └── kad@1.5.15
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

Node would like to join the network but system clock is not synced. I would expect any error message as feedback for the user. The best would be a full crash because any send message will never send back.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Node 1 (clock not synced) is sending FIND_NODE but unable to connect to the Storj network. Note: The incoming messages are not the FIND_NODE response. See logfile of node 2:
```
{"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.7.0\",\"address\":\"veeit30163.dyndns.org\",\"port\":6155,\"nodeID\":\"2b6b9175dcbdcbbce3337ca9e7a73946b82452ea\",\"lastSeen\":1466621936199}","timestamp":"2016-06-22T18:58:56.199Z"}
{"level":"debug","message":"queuing callback for reponse to 4bf3ede6050f82dfc96c83e4e0d15354428e5b05","timestamp":"2016-06-22T18:58:56.241Z"}
{"level":"warn","message":"missing or empty reply from contact","timestamp":"2016-06-22T18:58:57.666Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.7.0\",\"address\":\"veeit30163.dyndns.org\",\"port\":6155,\"nodeID\":\"2b6b9175dcbdcbbce3337ca9e7a73946b82452ea\",\"lastSeen\":1466621942781}","timestamp":"2016-06-22T18:59:02.781Z"}
{"level":"debug","message":"updating contact {\"protocol\":\"0.7.0\",\"address\":\"veeit30163.dyndns.org\",\"port\":6155,\"nodeID\":\"2b6b9175dcbdcbbce3337ca9e7a73946b82452ea\",\"lastSeen\":1466621942781}","timestamp":"2016-06-22T18:59:02.782Z"}
{"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-06-22T18:59:02.782Z"}
```

Node 2 is my own node. I am not veeit30163.dyndns.org but his log will look similar. This time node 1 is using my node as seed. His FIND_NODE will be ignored because signature expired but at the same time I add his node to my shortlist. Later I will try to send him a message but I will never answer any of his FIND_NODE messages.
```
{"level":"info","message":"received valid message from {\"protocol\":\"0.7.0\",\"address\":\"84.111.224.59\",\"port\":5000,\"nodeID\":\"2123925d4aec1aa86e662760974ccfd2bc8a4690\",\"lastSeen\":1466624578660}","timestamp":"2016-06-22T19:42:58.660Z"}
{"level":"debug","message":"updating contact {\"protocol\":\"0.7.0\",\"address\":\"84.111.224.59\",\"port\":5000,\"nodeID\":\"2123925d4aec1aa86e662760974ccfd2bc8a4690\",\"lastSeen\":1466624578660}","timestamp":"2016-06-22T19:42:58.660Z"}
{"level":"debug","message":"contact not in bucket, moving to head","timestamp":"2016-06-22T19:42:58.660Z"}
{"level":"error","message":"Message signature expired","timestamp":"2016-06-22T19:42:58.661Z"}
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start node with wrong clock settings.

**Comment by bookchin** [comment]
We could maybe use https://www.npmjs.com/package/ntpsync to check local server time against NTP, get the delta and exit with a error message indicating the need to sync clock?
