### ISSUE TITLE
Storj Audio streaming

### ISSUE THREAD

**Issue by vmatekole** [Storj/core#207]
Hi!

I'm not sure if this is the best place to ask this... Nonetheless, I am trying to workout if StorJ supports streaming natively. Furthermore, we have a requirement to also protect content from being directly 
accessed, hence, the need for streaming. Attached is a diagram that attempts to articulate my current understanding of Storj in-context of our reqs. Ideally, we'd not have the streaming server between farmer and client and stream directly, whilst not exposing keys to the client or at least restricting access to that session.

![resonate-storj-integration-2](https://cloud.githubusercontent.com/assets/424339/16307387/4e6b00f0-3961-11e6-8700-4dfad6f7d4b3.png)

**Comment by vmatekole** [comment]
Thanks to @phutchins for pointing me to - https://github.com/Storj/core/blob/8784b9ff70db7ee2b4d6c990c50a76ad5d2f09f0/bin/storj.js#L612

**Comment by bookchin** [comment]
As the protocol is currently designed and implemented, if you want to restrict access to some data or avoid exposing the decryption keys, you will need to have an intermediary streaming server. There just isn't a way right now to allow the client to receive the encrypted stream and be able decrypt it without exposing the key+iv.

However, you *can* use the bridge to restrict **access** to the data, by issuing one-time-use tokens to the client on a per-download basis. In practice, this would involve the client requesting a stream from your application, your application providing the decryption keys and ivs to the client along with a `PULL` token that your application gets from a bridge.

This would allow the client to stream and decrypt the data directly from farmers, while keeping access control in your applications hands. The client would have the decryption keys, but would still be required to request a `PULL` token from your application.
