### ISSUE TITLE
Keyring too Big to Unlock

### ISSUE THREAD

**Issue by super3** [Storj/core#211]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
root@storj:~/.nvm/versions/node/v4.4.5/lib/node_modules/storj/bin# npm list storj
storj@1.2.8 (git://github.com/bookchin/storj-core.git#e31bf4de68b5dab7485b9eedeea33d34af649ef1) /root/.nvm/versions/node/v4.4.5/lib/node_modules/storj
└── (empty)
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

Client can handle a large keyring file or starts a new one.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
root@storj:~/.nvm/versions/node/v4.4.5/lib/node_modules/storj/bin# storj reset-keyring
 [...]  > Enter your passphrase to unlock your keyring  >  ******

[SyntaxError: Unexpected end of input]
 [error]  Could not unlock keyring, bad password?
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run a script to constantly upload files for a few days. 
2. Try to upload a new data item and it will tell you ```Could not unlock keyring, bad password?```

**Comment by phutchins** [comment]
This one is currently breaking out download and upload monitor...
