### ISSUE TITLE
could not connect to NAT device via UPnP

### ISSUE THREAD

**Issue by babonet13** [Storj/core#215]
Problem while running Storjshare 0.8.5 for OS X / Core Librairie 1.31. / Protocol 0.7.0

Here are the logs : 
================================
Free Space: 10.90 TB
Balance: 10000 SJCX
{warn} [Sat Jun 25 2016 11:25:46 GMT+0200 (CEST)]
could not connect to NAT device via UPnP
{error} [Sat Jun 25 2016 11:25:46 GMT+0200 (CEST)]
failed to map port for tunserver: timeout
{warn} [Sat Jun 25 2016 11:25:46 GMT+0200 (CEST)]
could not connect to NAT device via UPnP
...
=================================

Thanks for help

Bernard

**Comment by littleskunk** [comment]
I don't see any problem. Enable UPnP, use the tunnel connection fallback or switch to CLI and forward the ports. https://storj.readme.io/docs/storjshare-troubleshooting-guide#port-forwarding

**Comment by babonet13** [comment]
Thanks for quick answer ...
Which port do I forward ? (*8443 ?)*
Best Regards
Bernard

**Comment by babonet13** [comment]
I have enabled UPnP on my box (Freebox), but the problem is still here ...
StorjShare is running on a Mac Mini behind a AirPort (as a routeur) behind a Freebox (as a bridge)

**Comment by littleskunk** [comment]
AirPort is comming with a proprietary implementation. They call it NAT-PMP and it is not compatible with UPnP. Your router doesn't support UPnP.

https://support.apple.com/kb/PH5103?locale=de_DE&viewlocale=en_EN
```
Select Enable NAT Port Mapping Protocol.

NAT Port Mapping Protocol (NAT-PMP) is an Internet Engineering Task Force Internet Draft, an alternative to the more common Universal Plug and Play (UPnP) protocol implemented in many NAT routers. NAT-PMP allows a computer in a private network (behind a NAT router) to automatically configure the router to allow clients outside the private network to contact this computer.
```

If you like you can open a core feature request for NAT-PMP. I don't think we can support a Draft version but maybe we can support it in the future when NAT-PMP is finished and published.
