### ISSUE TITLE
Error downloading file from storj: [error]  No decryption key found in key ring!

### ISSUE THREAD

**Issue by lunokhod** [Storj/core#224]
I successfully uploaded a 1 GB file using the storj command line interface, and I can see the file when listing the files in the corresponding bucket. Now, when I try to download the file (from a different computer than I uploaded it from, but correctly paired to my storj account), I get the error
~~~~
storj download-file 576d9def3319f4d518c159a5 5771adeb46efe913710c9bf6 /Users/lunokhod/test.mkv
 [...]  > Enter your passphrase to unlock your keyring  >  ******************************

 [info]   Creating retrieval token...
 [info]   Resolving file pointer...
 [info]   Downloading file from 128 channels.
 [error]  No decryption key found in key ring!
~~~~
~~~~
% storj --version
1.3.3
~~~~

**Comment by bookchin** [comment]
Your keyring is stored locally on the computer from which the file was uploaded. For now you need to manage your own keyring. You can copy `~/.storjcli/keyring`.

**Comment by lunokhod** [comment]
Ok. But, I was able to use `storj remove-file` without having the decryption key. This is bound to cause problems later when people realize that even though they have their bridge password that they lost their keyring... I'm not offering a solution, but this should probably be stated somewhere in caps-lock...
