### ISSUE TITLE
Could not unlock keyring, bad password?

### ISSUE THREAD

**Issue by Th3Van** [Storj/core#231]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
th3van@Server017.storj.dk:~/bridge# npm list storj
storj-bridge@0.9.3 /root/bridge
└── storj@1.3.5 
```

Replace the values below using the output from `node --version`.

```
v6.2.2
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
To save the key to keyring file : 
 [info]   Encryption key saved to keyring.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
After running for about an hour, the error message randomly appears. 
Sometimes just once, sometimes 8 - 10 in a row:
 [error]  Could not unlock keyring, bad password?

Could it be one or more of the minions trying to access the keyring file 
at the exact same time, which are resulting in this error?
I have not tested if the file being uploaded is somehow damaged and can not be 
downloaded again, due to missing debug/log level.
Would be great if time stamps and loglevel 4 could be added to storj :) 

Check logfile for more details.
```
[Storj.dk - Could not unlock keyring - bad password.txt](https://github.com/Storj/core/files/340499/Storj.dk.-.Could.not.unlock.keyring.-.bad.password.txt)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1.   Install bridge and storj on debian
2.   Setup 5 minions
3.   Keep feeding a queue with 30 x 16MB files and server it to the bridge using storj
4.   Let storj run for about an hour, while using grep "unlock" on stdout.

**Comment by bookchin** [comment]
Duplicate https://github.com/Storj/core/issues/211

**Comment by bookchin** [comment]
If you don't need to download the data again (if you are just spitting out data into the network), you can simply delete `~/.storjcli/keyring` and start again as a workaround.
