### ISSUE TITLE
Duplicate key error E11000

### ISSUE THREAD

**Issue by airatru** [Storj/core#233]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
/usr/local/lib
├── storj@1.3.5 
├─┬ storj-bridge@0.9.3
│ └── storj@1.3.5 
└─┬ storjshare-cli@4.0.4
  └── storj@1.3.5 
```

Replace the values below using the output from `node --version`.

```
v4.4.7

```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```

```

### Actual Behavior

{"level":"error","message":"E11000 duplicate key error index: __storj-bridge-test.shards.$hash_1  dup key: { : \"1e3731774c47bd082c6740dd910c3223da75d6c1\" }","timestamp":"2016-06-30T13:12:08.867Z"}

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run storjshare-cli on linux jessie (for rpi3)
2. Wait
3. Wait a bit more

**Comment by bookchin** [comment]
Please open this at https://github.com/Storj/bridge/issues
