### ISSUE TITLE
Cleanup Error

### ISSUE THREAD

**Issue by super3** [Storj/core#237]
Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

Clean exit.

### Actual Behavior

Trys to access shard after cleanup.

```
 [info]   Data channel opened, transferring shard...
 [info]   Adding shard metadata for 5bc793c2ebbf097a7de550192fb4e6c5c541d18d to frame
 [warn]   Failed to upload shard...
 [error]  <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>

 [info]   Cleaning up...
 [info]   Finished cleaning!
 [info]   Adding shard metadata for 792bce76c3269b35d233702f949028d3a4257b9b to frame
 [info]   Contract negotiated with: {"protocol":"0.7.0","address":"server118.web4you-gmbh.ch","port":4000,"nodeID":"70b731e6be92504973d509476b2046b0422560c4","lastSeen":1467392573613}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/tmp/1a2af5b42281'
    at Error (native)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload 1GB+ file

**Comment by rdegges** [comment]
Hey all, I'm using storj@2.0.7.

I'm trying to upload a large file (1.2G), and keep erroring out:

```
 [Mon Aug 08 2016 16:53:30 GMT-0700 (PDT)] [info]   Data channel opened, transferring shard...
 [Mon Aug 08 2016 16:53:31 GMT-0700 (PDT)] [info]   Adding shard metadata for 5b32de92c46ca6647a984a949bbc75bd2c849280 to frame
 [Mon Aug 08 2016 16:53:35 GMT-0700 (PDT)] [warn]   Failed to upload shard...
 [Mon Aug 08 2016 16:53:35 GMT-0700 (PDT)] [warn]   Error occured. Triggering cleanup...
 [Mon Aug 08 2016 16:53:35 GMT-0700 (PDT)] [info]   Cleaning up...
 [Mon Aug 08 2016 16:53:35 GMT-0700 (PDT)] [info]   Finished cleaning!
 [Mon Aug 08 2016 16:53:35 GMT-0700 (PDT)] [error]  No storage offers were received
 [Mon Aug 08 2016 16:53:37 GMT-0700 (PDT)] [info]   Contract negotiated with: {"protocol":"0.7.1","address":"storj.uk","port":32630,"nodeID":"205e303205fc1b7701963eaf888a4ca8463a4013","lastSeen":1470700414340}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/var/folders/9l/x58srf0967jcqgmrz7xy_jrr0000gn/T/187a13fd7776'
    at Error (native)
```

**Comment by bookchin** [comment]
@aleitner we just need to kill the upload queue on cleanup, the client is trying to upload the next shard in the queue after the cleanup has run and the tmp shard is not there anymore

**Comment by MeijeSibbel** [comment]
I get the same error:

[Fri Aug 12 2016 23:55:15 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
[Fri Aug 12 2016 23:55:15 GMT+0200 (W. Europe Daylight Time)] [warn]   Error occured. Triggering cleanup...
[Fri Aug 12 2016 23:55:15 GMT+0200 (W. Europe Daylight Time)] [info]   Cleaning up...
[Fri Aug 12 2016 23:55:15 GMT+0200 (W. Europe Daylight Time)] [info]   Finished cleaning!
[Fri Aug 12 2016 23:55:15 GMT+0200 (W. Europe Daylight Time)] [error]  No storage offers were received
[Fri Aug 12 2016 23:55:16 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.7.1","address":"redcircle.ddns.net","port":4000,"nodeID":"a9f4706cb0887eb5c88a1e3503eb42b2d7895be4","lastSeen":1471038905602}
events.js:160
     throw er; // Unhandled 'error' event
     ^

Error: ENOENT: no such file or directory, open 'C:\Users\Meije\AppData\Local\Temp\e0ce3b1e05c1'
   at Error (native)
