### ISSUE TITLE
Storj Share : Which ports should be open on my router (instead of using UPnP) ???

### ISSUE THREAD

**Issue by babonet13** [Storj/core#239]
Hello, 

My router (Apple Airport) should not support UPnP !

Which port should I open on my router instead of using UPnP ?
> TCP 4000-4004 ?
> TCP 8443 ?
> Others ports ?

Thanks for help

Bernard

**Comment by littleskunk** [comment]
https://storj.readme.io/docs/storjshare-troubleshooting-guide#port-forwarding

https://github.com/Storj/core/issues/218
