### ISSUE TITLE
Add support for hole punching

### ISSUE THREAD

**Issue by felixbrucker** [Storj/core#242]
### P2P across NAT's - the Situation

currently only manual port forwarding, automatic port forwarding with upnp and tunnels are employed to connect to the network and peers.
However in situations with restrictive/multiple NAT's or no control over them there is no other way than using tunnels, which in turn causes network load on peers providing them.
Hole punching allows the peers to create a direct p2p communication channel (possible with udp and tcp) without any manual or automatic port forwarding.
This is done by signaling both peers (aka relay the connection information) from a third "static" server, which might in turn just be another peer with port forwarding enabled or a seed, to establish a direct p2p connection between each other ([more](http://www.brynosaurus.com/pub/net/p2pnat/)).

### Feature Request
it would be great to implement hole punching at some point before the final release to minimize the negative side effects with tunnels and only resort to tunneling if hole punching fails.

**Comment by super3** [comment]
Hole punching is a major undertaking and would take weeks or months of work to do properly. We have much larger priorities. We will keep it in the backlog, but unless a community member wants to submit a pull request to add this feature we will not be adding this anytime soon.
