### ISSUE TITLE
Support better error handling when uploading files

### ISSUE THREAD

**Issue by travism0** [Storj/core#244]
### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

If the program is unable to upload a shard after retrying multiple times it should find another node to upload the shard to instead.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

While transferring a shard the program experienced a ETIMEDOUT error which resulted in it retrying to upload the shard. This process would continue indefinitely with the same destination node instead of switching nodes after experiencing the same error multiple times.

```
[info]   Contract negotiated with: {"protocol":"0.7.0","address":"my_ip","port":4000,"nodeID":"828113...","lastSeen":1467572021469}
 [warn]   Failed to transfer shard, reason: connect ETIMEDOUT my_ip:4000
 [info]   Retrying shard transfer, pointer: {"hash":"95afe9...","token":"876d55...","operation":"PUSH","farmer":{"protocol":"0.7.0","address":"my_ip","port":4000,"nodeID":"828113...","lastSeen":1467572021469}}

Continues to retry the transfer with the same node numerous times until I stop it...
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload a file to the network
2. If it experiences an error while uploading to a node it will try to upload to the same node when it retries instead of switching to another node after experiencing the same error multiple times.

In my case this error was caused by my firewall preventing the shard transfer each time the program selected my own node to upload the file to (running on another computer on my network). Regardless, the program should choose another node when it experiences the same error multiple times with the same node.

This error was also experienced earlier today by @phinx_02 on Slack.

**Comment by bookchin** [comment]
Resolved by https://github.com/Storj/core/releases/tag/v2.0.0
