### ISSUE TITLE
"configured to tunnel up to 3 connections" when tunnels is set to 0.

### ISSUE THREAD

**Issue by lunokhod** [Storj/core#247]
In my config file, I set the the number of inbound tunnel connections to be zero
~~~~
"tunnels": 0,
 "tunnelport": 0,
 "gateways": {
   "min": 0,
   "max": 0
 }
~~~~
However, when I start up storjshare, I get a message saying that I am configured to tunnel up to 3 connections (and this, even though I am behind a firewall).
~~~~
{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-07-06T11:56:19.894Z"}
~~~~
~~~~
StorjShare: 4.0.4
Core:       1.4.0
Protocol:   0.7.1
~~~~

**Comment by bookchin** [comment]
This may actually be at the application layer at storjshare-cli/gui.

**Comment by super3** [comment]
Fixed.
