### ISSUE TITLE
MIRROR abuse for bonus payment

### ISSUE THREAD

**Issue by littleskunk** [storj/core#263]
As farmer I would like to get as many traffic income as possible. I have two ways to generate traffic myself by abusing shards mirrors.

1.) **Farmer pool**
Lets build a farmer pool with at least 2 farmer. Lets call them Bob and Alice. The bridge is uploading a shard to Bob and sending a MIRROR message to Alice. Bob will send a copy of the shard to Alice. This upload will increase the traffic counter for Bob. He will get traffic payment. Now Alice has to delete the shard. The next audit will fail. The bridge will send a new MIRROR message to Bob. The upload counter will increase once more. At the end of the month Bob will pay 50% of the extra payment to Alice.

This plan has one disadvantage. If Alice deletes the shard copy any other node outside this pool can get the shard. This will reduce the regular traffic income. The best way to minimize this risk is a very large pool with hunderts of farmer. That way the new shard copy has a higher chance to be stored on any other node inside the pool. Additional to that Bob and Alice should only compare shards with less than X downloads after Y days. They will not play the game with high income contracts. They can decide a few minutes befor the first audit is comming.

Fun Fact: By holding a contract with low traffic count for one month Alice will get $0.015/GB (renter price inclusive redundace copies!). By deleting that shard a few seconds befor the audit is coming Alice will get 50% of $0.05/GB. Alice would be stupid not deleting the shard copy....

2.) **Upload corrupted copies**
Bob will store the shard but upload a manipulated version to 6 other mirror nodes. All mirror nodes have a corrupted copy and will fail every audit. Only Bob has the shard and he has to upload the shard to the next 6 mirror nodes. That way he will have a nice traffic income without losing the shard control. There is only one risk. After a few audits it would be obvious what Bob is doing and he could end up on a blacklist.

3.) **Upload corrupted copies and cycle pool nodes**
Combination of 1 and 2.
Bob will upload 5 corrupted shards to other mirror nodes and one valid shard to Alice. Bob deletes his own shard. Only Alice has the last valid shard and will get the next traffic increment. This combines the advantages of both solutions. Bob and Alice have no risk to lose the shard control but at the same time it will be harder to find the pattern. With a large pool they have a high chance that any of the mirror nodes is connected to the pool. The last valid shard will be stored on a random pool node. It will be hard for the renter to blacklist them.

4.) **Blacklist non pool nodes**
Obvious solution: If audit fails on 5 of 6 nodes always blacklist Bob. Well in that case Bob has a new way to maximize his income. Upload 5 corrupted shards and only one valid shard. Next audit Bob has to fail himself. The node outside the pool with the only valid shard looks like a bad node playing game number 2 and will be blacklisted and ignored for new shards. Go on like that to increase the blacklisted non pool nodes and increase the number of shards the pool will get.
Bonus quest: Bob should not stupid upload 5 corrupted shards. He should give pool nodes a valid copy but keep them in mind and talk with them a few minutes befor the first audit comes. That way they can keep the good contracts and play the blacklist game only with low traffic count contracts.

**Comment by littleskunk** [comment]
5.) **Free download for the renter**
As renter I would like to download a shard without any payment. Lets send a MIRROR message to Bob and let him upload a shard copy to my farmer. At the moment this will increase the traffic payment for Bob and I have no way to download the shard for free. We should keep this in mind for any solution for problem 1-4. How about increasing the traffic count only if the mirror is valid. In that case my farmer node would report a invalid shard copy. That will not increase the traffic counter and I have a way to download the shard for free.

**Comment by bookchin** [comment]
Thanks for putting this together. Give me the weekend to review and think it over.

**Comment by littleskunk** [comment]
At the moment implemented is number 5:
`Mostly use exchange reports which differentiate between mirror downloads and actual client downloads`

As Renter I can request a download. At the end I will send a `MIRROR_SUCCESS` exchange report. The bridge will count that a mirror download. That way I can download the shard for free.

**Comment by bookchin** [comment]
It should fail signature verification, because exchange reports include the client id and the farmer id.

**Comment by littleskunk** [comment]
On a paid shard download the bridge should get 2 exchange reports. One `SHARD_DOWNLOADED` from the farmer and one `SHARD_DOWNLOADED` from the renter.

Unpaid is one `SHARD_DOWNLOADED` from the farmer and `MIRROR_SUCCESS` from another farmer.

Signature must be correct in both cases. The bridge doesn't see any difference between both. The bridge will ask one farmer and return the token to the other farmer. On receiving an exchange report these signatures must be correct.

As farmer I can request a download channel and send a `MIRROR_SUCCESS` at the end. Signature will be vaild because the bride has a token matching my exchange report. I can download for free.

Plan B:
Send `FAILED_INTEGRITY` will have the same effect. Valid signature and I don't have to pay for the successfull download.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
