### ISSUE TITLE
Issue Template Correct?

### ISSUE THREAD

**Issue by super3** [Storj/core#274]
Replace the values below using the output from `npm list storj`.

```
root@flooder1:~# npm list storj
/root
└── (empty)

npm ERR! code 1
```

Should we instead ask them to simply do ```storj --version```?

**Comment by bookchin** [comment]
Depends on the install method. That command will show the right result if installed as a local dependency. Add -g for global install.

**Comment by super3** [comment]
@bookchin Ah there we go. We recommend -g in many of the guides, so will issue a pull request.
