### ISSUE TITLE
Client needs to handle ECONNREFUSED more gracefully

### ISSUE THREAD

**Issue by utdrmac** [Storj/core#275]
```
 [Fri Jul 22 2016 16:00:28 GMT-0500 (CDT)] [info]   Generating encryption key...
 [Fri Jul 22 2016 16:00:28 GMT-0500 (CDT)] [info]   Encrypting file "/data/myData.dat"
 [Fri Jul 22 2016 16:00:28 GMT-0500 (CDT)] [info]   Encryption complete!
 [Fri Jul 22 2016 16:00:28 GMT-0500 (CDT)] [info]   Creating storage token...
 [Fri Jul 22 2016 16:00:29 GMT-0500 (CDT)] [info]   Storing file, hang tight!
 [Fri Jul 22 2016 16:00:29 GMT-0500 (CDT)] [info]   Trying to upload shard /tmp/9cc84dca2979 index 0
 [Fri Jul 22 2016 16:00:29 GMT-0500 (CDT)] [info]   Hash for this shard is: 8674252308028f02df7c5a808380c8b1e4c3aed5
 [Fri Jul 22 2016 16:00:29 GMT-0500 (CDT)] [info]   Audit generation for shard done.
 [Fri Jul 22 2016 16:00:29 GMT-0500 (CDT)] [info]   Waiting on a storage offer from the network...
 [Fri Jul 22 2016 16:00:29 GMT-0500 (CDT)] [info]   Adding shard metadata for 8674252308028f02df7c5a808380c8b1e4c3aed5 to frame
 [Fri Jul 22 2016 16:00:30 GMT-0500 (CDT)] [info]   Contract negotiated with: {"protocol":"0.7.1","address":"73.183.176.104","port":57534,"nodeID":"8e785a74d1ddb23f1325ce4cec1ad07118a20c4b","lastSeen":1469221230086}
 [Fri Jul 22 2016 16:00:30 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 73.183.176.104:57534
 [Fri Jul 22 2016 16:00:30 GMT-0500 (CDT)] [info]   Retrying shard transfer, pointer: {"hash":"8674252308028f02df7c5a808380c8b1e4c3aed5","token":"02124f7c5ebede41de9e805412c4591f7be49f50","operation":"PUSH","farmer":{"protocol":"0.7.1","address":"73.183.176.104","port":57534,"nodeID":"8e785a74d1ddb23f1325ce4cec1ad07118a20c4b","lastSeen":1469221230086}}
 [Fri Jul 22 2016 16:00:30 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 73.183.176.104:57534
 [Fri Jul 22 2016 16:00:30 GMT-0500 (CDT)] [info]   Retrying shard transfer, pointer: {"hash":"8674252308028f02df7c5a808380c8b1e4c3aed5","token":"02124f7c5ebede41de9e805412c4591f7be49f50","operation":"PUSH","farmer":{"protocol":"0.7.1","address":"73.183.176.104","port":57534,"nodeID":"8e785a74d1ddb23f1325ce4cec1ad07118a20c4b","lastSeen":1469221230086}}
 [Fri Jul 22 2016 16:00:30 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 73.183.176.104:57534
 [Fri Jul 22 2016 16:00:30 GMT-0500 (CDT)] [info]   Retrying shard transfer, pointer: {"hash":"8674252308028f02df7c5a808380c8b1e4c3aed5","token":"02124f7c5ebede41de9e805412c4591f7be49f50","operation":"PUSH","farmer":{"protocol":"0.7.1","address":"73.183.176.104","port":57534,"nodeID":"8e785a74d1ddb23f1325ce4cec1ad07118a20c4b","lastSeen":1469221230086}}
```

LAST TWO LINES REPEATED OVER 10,000 times (literally, the size of my terminal scrollback buffer) before I finally ctrl-c

## Expected Behavior
I would have expected the client to give up contacting an ECONNREFUSED and try a new node instead of hammering the selected one.

**Comment by bookchin** [comment]
What version are you running?

**Comment by utdrmac** [comment]
latest. just updated. 

```
# npm update -g storj
# storj --version
2.0.5
```

**Comment by bookchin** [comment]
What version of node are you running? We support LTS (4.x.x). I suspect that you are running a newer version that removes a private property that we use to determine if we should try another farmer: https://github.com/nodejs/node/commit/ca7507253a1d32e2c54452b22ec020af7e6225a4

**Comment by bookchin** [comment]
Just opened https://github.com/Storj/core/issues/277

**Comment by bookchin** [comment]
Let me know if this persists after installing the correct Node version, so I can close.

**Comment by utdrmac** [comment]
@bookchin 
```root@gasgiant:~# node --version
v4.4.5```

**Comment by super3** [comment]
@utdrmac @bookchin I also experienced this issue on #284

**Comment by utdrmac** [comment]
@bookchin Re-open.

I want to emphasize that 72.183.176.104 is me, just in case that is the issue here. I have the client on my linux NAS and have 2 drive shares on my Windows box. I'm uploading a bunch of small (<1MB) files as tests in a wrapper script. Whenever the client tries to connect/upload to myself, I get these errors. I restarted my GUI shares this morning (restarted = stopped all shares, removed all directories and re-created everything). Drive0 has no contracts; Drive1 has 78.

```root@gasgiant:~# storj --version
2.0.6```

```
Uploading /data/fileData.dat...
 [Mon Jul 25 2016 14:34:55 GMT-0500 (CDT)] [info]   Generating encryption key...
 [Mon Jul 25 2016 14:34:55 GMT-0500 (CDT)] [info]   Encrypting file "/data/fileData.dat"
 [Mon Jul 25 2016 14:34:55 GMT-0500 (CDT)] [info]   Encryption complete!
 [Mon Jul 25 2016 14:34:55 GMT-0500 (CDT)] [info]   Creating storage token...
 [Mon Jul 25 2016 14:34:56 GMT-0500 (CDT)] [info]   Storing file, hang tight!
 [Mon Jul 25 2016 14:34:56 GMT-0500 (CDT)] [info]   Trying to upload shard /tmp/451f883eb65a index 0
 [Mon Jul 25 2016 14:34:56 GMT-0500 (CDT)] [info]   Hash for this shard is: 7bfc42a7fecea5d54a3631f7e235d2cb83ed65db
 [Mon Jul 25 2016 14:34:56 GMT-0500 (CDT)] [info]   Audit generation for shard done.
 [Mon Jul 25 2016 14:34:56 GMT-0500 (CDT)] [info]   Waiting on a storage offer from the network...
 [Mon Jul 25 2016 14:34:56 GMT-0500 (CDT)] [info]   Adding shard metadata for 7bfc42a7fecea5d54a3631f7e235d2cb83ed65db to frame
 [Mon Jul 25 2016 14:34:58 GMT-0500 (CDT)] [info]   Contract negotiated with: {"protocol":"0.7.1","address":"72.183.176.104","port":58001,"nodeID":"7b6dcbed59e9c0198d70ecc00ee23f6ab3d95510","lastSeen":1469475297598}
 [Mon Jul 25 2016 14:34:58 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 72.183.176.104:58001
 [Mon Jul 25 2016 14:34:58 GMT-0500 (CDT)] [info]   Retrying shard transfer, pointer: {"hash":"7bfc42a7fecea5d54a3631f7e235d2cb83ed65db","token":"80efe984235a9298fb48c38293c46ccabe0aa4c4","operation":"PUSH","farmer":{"protocol":"0.7.1","address":"72.183.176.104","port":58001,"nodeID":"7b6dcbed59e9c0198d70ecc00ee23f6ab3d95510","lastSeen":1469475297598}}
 [Mon Jul 25 2016 14:34:58 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 73.183.176.104:58001
 [Mon Jul 25 2016 14:34:58 GMT-0500 (CDT)] [info]   Retrying shard transfer, pointer: {"hash":"7bfc42a7fecea5d54a3631f7e235d2cb83ed65db","token":"80efe984235a9298fb48c38293c46ccabe0aa4c4","operation":"PUSH","farmer":{"protocol":"0.7.1","address":"72.183.176.104","port":58001,"nodeID":"7b6dcbed59e9c0198d70ecc00ee23f6ab3d95510","lastSeen":1469475297598}}
 [Mon Jul 25 2016 14:34:58 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 72.183.176.104:58001
 [Mon Jul 25 2016 14:34:58 GMT-0500 (CDT)] [info]   Retrying shard transfer, pointer: {"hash":"7bfc42a7fecea5d54a3631f7e235d2cb83ed65db","token":"80efe984235a9298fb48c38293c46ccabe0aa4c4","operation":"PUSH","farmer":{"protocol":"0.7.1","address":"72.183.176.104","port":58001,"nodeID":"7b6dcbed59e9c0198d70ecc00ee23f6ab3d95510","lastSeen":1469475297598}}
 [Mon Jul 25 2016 14:34:58 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 72.183.176.104:58001
 [Mon Jul 25 2016 14:34:58 GMT-0500 (CDT)] [info]   Shard transfer failed 3 times, getting another contract...
crypto.js:77
  return this._handle.digest(outputEncoding);
                      ^

Error: Not initialized
    at Error (native)
    at Hash.digest (crypto.js:77:23)
    at BridgeClient._handleShardTmpFileFinish (/usr/lib/node_modules/storj/lib/bridgeclient.js:434:39)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/storj/lib/bridgeclient.js:494:12)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at DataChannelClient._onErr (/usr/lib/node_modules/storj/lib/bridgeclient.js:555:13)
    at emitOne (events.js:77:13)
    at DataChannelClient.emit (events.js:169:7)
    at DataChannelClient._handleChannelError (/usr/lib/node_modules/storj/lib/datachannel/client.js:152:8)
Result: 1
```

**Comment by bookchin** [comment]
Damn, that's new - I just introduced that this morning. On it.

**Comment by utdrmac** [comment]
I'm bored at home. Just playing with this stuff so if you have updates you'd like me to test, I can.

**Comment by bookchin** [comment]
Good! Can you install from my fork and give it another go?

```
npm install -g bookchin/storj-core
```

**Comment by bookchin** [comment]
(https://github.com/Storj/core/pull/290)

**Comment by utdrmac** [comment]
Done. Re-running my script now. Is there a way to create a whitelist of famers so that my client only tries them?

**Comment by bookchin** [comment]
Not as of right now.

**Comment by bookchin** [comment]
Any luck?

**Comment by utdrmac** [comment]
Still going through my script. Hasn't faltered yet. I'll re-run it everything is successful.

**Comment by utdrmac** [comment]
And right after I posted that. 

```
Uploading /data/fileData.dat...
 [Mon Jul 25 2016 16:31:12 GMT-0500 (CDT)] [info]   Generating encryption key...
 [Mon Jul 25 2016 16:31:12 GMT-0500 (CDT)] [info]   Encrypting file "/data/fileData.dat"
 [Mon Jul 25 2016 16:31:12 GMT-0500 (CDT)] [info]   Encryption complete!
 [Mon Jul 25 2016 16:31:12 GMT-0500 (CDT)] [info]   Creating storage token...
 [Mon Jul 25 2016 16:31:13 GMT-0500 (CDT)] [info]   Storing file, hang tight!
 [Mon Jul 25 2016 16:31:14 GMT-0500 (CDT)] [info]   Trying to upload shard /tmp/75a709dc2fa2 index 0
 [Mon Jul 25 2016 16:31:14 GMT-0500 (CDT)] [info]   Hash for this shard is: cc808c5f222170e5a25fef8968a520197126545d
 [Mon Jul 25 2016 16:31:14 GMT-0500 (CDT)] [info]   Audit generation for shard done.
 [Mon Jul 25 2016 16:31:14 GMT-0500 (CDT)] [info]   Waiting on a storage offer from the network...
 [Mon Jul 25 2016 16:31:14 GMT-0500 (CDT)] [info]   Adding shard metadata for cc808c5f222170e5a25fef8968a520197126545d to frame
 [Mon Jul 25 2016 16:31:15 GMT-0500 (CDT)] [info]   Contract negotiated with: {"protocol":"0.7.1","address":"72.183.176.104","port":13255,"nodeID":"cd4ac1e8dbd99a14ddb8d94e35c27471bdd42840","lastSeen":1469482274915}
 [Mon Jul 25 2016 16:31:15 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 72.183.176.104:13255
 [Mon Jul 25 2016 16:31:15 GMT-0500 (CDT)] [info]   Retrying shard transfer, pointer: {"hash":"cc808c5f222170e5a25fef8968a520197126545d","token":"6669bed3c7ca8a31dbec7a6876efc885944f4d06","operation":"PUSH","farmer":{"protocol":"0.7.1","address":"72.183.176.104","port":13255,"nodeID":"cd4ac1e8dbd99a14ddb8d94e35c27471bdd42840","lastSeen":1469482274915}}
 [Mon Jul 25 2016 16:31:15 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 72.183.176.104:13255
 [Mon Jul 25 2016 16:31:15 GMT-0500 (CDT)] [info]   Retrying shard transfer, pointer: {"hash":"cc808c5f222170e5a25fef8968a520197126545d","token":"6669bed3c7ca8a31dbec7a6876efc885944f4d06","operation":"PUSH","farmer":{"protocol":"0.7.1","address":"72.183.176.104","port":13255,"nodeID":"cd4ac1e8dbd99a14ddb8d94e35c27471bdd42840","lastSeen":1469482274915}}
 [Mon Jul 25 2016 16:31:15 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 72.183.176.104:13255
 [Mon Jul 25 2016 16:31:15 GMT-0500 (CDT)] [info]   Retrying shard transfer, pointer: {"hash":"cc808c5f222170e5a25fef8968a520197126545d","token":"6669bed3c7ca8a31dbec7a6876efc885944f4d06","operation":"PUSH","farmer":{"protocol":"0.7.1","address":"72.183.176.104","port":13255,"nodeID":"cd4ac1e8dbd99a14ddb8d94e35c27471bdd42840","lastSeen":1469482274915}}
 [Mon Jul 25 2016 16:31:15 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 72.183.176.104:13255
 [Mon Jul 25 2016 16:31:15 GMT-0500 (CDT)] [info]   Shard transfer failed 3 times, getting another contract...
 [Mon Jul 25 2016 16:31:15 GMT-0500 (CDT)] [info]   Hash for this shard is: cc808c5f222170e5a25fef8968a520197126545d
 [Mon Jul 25 2016 16:31:15 GMT-0500 (CDT)] [info]   Audit generation for shard done.
 [Mon Jul 25 2016 16:31:15 GMT-0500 (CDT)] [info]   Waiting on a storage offer from the network...
 [Mon Jul 25 2016 16:31:15 GMT-0500 (CDT)] [info]   Adding shard metadata for cc808c5f222170e5a25fef8968a520197126545d to frame
 [Mon Jul 25 2016 16:31:16 GMT-0500 (CDT)] [info]   Contract negotiated with: {"protocol":"0.7.1","address":"163.storj.eu","port":8630,"nodeID":"c08fd9d8659c8b9db7d589b1b8dca546259fcd52","lastSeen":1469482276236}
 [Mon Jul 25 2016 16:31:16 GMT-0500 (CDT)] [info]   Data channel opened, transferring shard...
 [Mon Jul 25 2016 16:31:16 GMT-0500 (CDT)] [info]   Shard transfer completed! 0 remaining...
 [Mon Jul 25 2016 16:31:16 GMT-0500 (CDT)] [info]   Transfer finished, creating entry...
 [Mon Jul 25 2016 16:31:17 GMT-0500 (CDT)] [info]   Cleaning up...
 [Mon Jul 25 2016 16:31:17 GMT-0500 (CDT)] [info]   Finished cleaning!
 [Mon Jul 25 2016 16:31:17 GMT-0500 (CDT)] [info]   Encryption key saved to keyring.
 [Mon Jul 25 2016 16:31:17 GMT-0500 (CDT)] [info]   File successfully stored in bucket.
 [Mon Jul 25 2016 16:31:17 GMT-0500 (CDT)] [info]   Name: fileData.dat, Type: application/x-bittorrent, Size: 37666 bytes, ID: 57968525a0494c4b27d6162c
Result: 0
```

And this one came in 2 files later:

```
 [Mon Jul 25 2016 16:31:45 GMT-0500 (CDT)] [info]   Generating encryption key...
 [Mon Jul 25 2016 16:31:45 GMT-0500 (CDT)] [info]   Encrypting file "/data/moreData.dat"
 [Mon Jul 25 2016 16:31:45 GMT-0500 (CDT)] [info]   Encryption complete!
 [Mon Jul 25 2016 16:31:45 GMT-0500 (CDT)] [info]   Creating storage token...
 [Mon Jul 25 2016 16:31:46 GMT-0500 (CDT)] [info]   Storing file, hang tight!
 [Mon Jul 25 2016 16:31:46 GMT-0500 (CDT)] [info]   Trying to upload shard /tmp/ef88b92d44b1 index 0
 [Mon Jul 25 2016 16:31:46 GMT-0500 (CDT)] [info]   Hash for this shard is: 5341b12e055a5deb48f61e20a282579be212ed01
 [Mon Jul 25 2016 16:31:46 GMT-0500 (CDT)] [info]   Audit generation for shard done.
 [Mon Jul 25 2016 16:31:46 GMT-0500 (CDT)] [info]   Waiting on a storage offer from the network...
 [Mon Jul 25 2016 16:31:46 GMT-0500 (CDT)] [info]   Adding shard metadata for 5341b12e055a5deb48f61e20a282579be212ed01 to frame
 [Mon Jul 25 2016 16:32:02 GMT-0500 (CDT)] [info]   Adding shard metadata for 5341b12e055a5deb48f61e20a282579be212ed01 to frame
 [Mon Jul 25 2016 16:32:17 GMT-0500 (CDT)] [info]   Adding shard metadata for 5341b12e055a5deb48f61e20a282579be212ed01 to frame
 [Mon Jul 25 2016 16:32:33 GMT-0500 (CDT)] [info]   Adding shard metadata for 5341b12e055a5deb48f61e20a282579be212ed01 to frame
 [Mon Jul 25 2016 16:32:48 GMT-0500 (CDT)] [info]   Adding shard metadata for 5341b12e055a5deb48f61e20a282579be212ed01 to frame
 [Mon Jul 25 2016 16:33:04 GMT-0500 (CDT)] [info]   Adding shard metadata for 5341b12e055a5deb48f61e20a282579be212ed01 to frame
 [Mon Jul 25 2016 16:33:05 GMT-0500 (CDT)] [info]   Contract negotiated with: {"protocol":"0.7.1","address":"104.196.0.239","port":8508,"nodeID":"40d2e5d7f795e318a567c9bc84b900709a8b4032","lastSeen":1469482384820}
 [Mon Jul 25 2016 16:33:05 GMT-0500 (CDT)] [info]   Data channel opened, transferring shard...
 [Mon Jul 25 2016 16:33:05 GMT-0500 (CDT)] [info]   Shard transfer completed! 0 remaining...
 [Mon Jul 25 2016 16:33:05 GMT-0500 (CDT)] [info]   Transfer finished, creating entry...
 [Mon Jul 25 2016 16:33:06 GMT-0500 (CDT)] [info]   Cleaning up...
 [Mon Jul 25 2016 16:33:06 GMT-0500 (CDT)] [info]   Finished cleaning!
 [Mon Jul 25 2016 16:33:06 GMT-0500 (CDT)] [info]   Encryption key saved to keyring.
 [Mon Jul 25 2016 16:33:06 GMT-0500 (CDT)] [info]   File successfully stored in bucket.
```

**Comment by utdrmac** [comment]
Again, noting that 72.183.176.104 is me.

**Comment by utdrmac** [comment]
The first few lines of the log file for StorjShare Drive1:

```
[1469462434309] Log file created.
{info} [Mon Jul 25 2016 11:00:34 GMT-0500 (Central Daylight Time)] successfully traversed NAT via UPnP: 72.183.176.104:54690
{info} [Mon Jul 25 2016 11:00:34 GMT-0500 (Central Daylight Time)] tunnel server bound and port mapped: 54690
{info} [Mon Jul 25 2016 11:00:34 GMT-0500 (Central Daylight Time)] successfully traversed NAT via UPnP: 72.183.176.104:13255
{info} [Mon Jul 25 2016 11:00:34 GMT-0500 (Central Daylight Time)] kad node bound and port mapped: 13255
{info} [Mon Jul 25 2016 11:00:34 GMT-0500 (Central Daylight Time)] node created with nodeID cd4ac1e8dbd99a14ddb8d94e35c27471bdd42840
{info} [Mon Jul 25 2016 11:00:34 GMT-0500 (Central Daylight Time)] resolving seeds from https://api.storj.io
```

**Comment by utdrmac** [comment]
BTW, that's not my real IP. I'm obfuscating it; just in case you are attempting to do some manual checks.

**Comment by bookchin** [comment]
Okay, so looks good - the retry logic is working. You not being able to transfer shards to yourself is an entirely different problem - one I tend to think is related to router config/networking/loopback funny business.

Closing this now and tagging the hotfix. Thanks for the help!
