### ISSUE TITLE
Wrong port when connecting to farmer

### ISSUE THREAD

**Issue by utdrmac** [Storj/core#276]
Related to #275 and #218 

I'm running farmer / "Storj Share" on my Windows computer. Attempting to upload files from linux host, using CLI.

Looking at the errors in #275, you'll see this:

```{"protocol":"0.7.1","address":"73.183.176.104","port":57534```

Turns out, that's my own IP. The client on my linux box was trying to send a file to my farmer node. I had successfully uploaded about 20 others files to other nodes. Seems that maybe hair-pining is an issue with my router/ISP?

Here is the first few lines of the log from the Windows farmer:

```
{info} [Fri Jul 22 2016 10:51:02 GMT-0500 (Central Daylight Time)] successfully traversed NAT via UPnP: 73.183.176.104:49233
{info} [Fri Jul 22 2016 10:51:02 GMT-0500 (Central Daylight Time)] tunnel server bound and port mapped: 49233
{info} [Fri Jul 22 2016 10:51:02 GMT-0500 (Central Daylight Time)] successfully traversed NAT via UPnP: 73.183.176.104:33024
{info} [Fri Jul 22 2016 10:51:02 GMT-0500 (Central Daylight Time)] kad node bound and port mapped: 33024
{info} [Fri Jul 22 2016 10:51:02 GMT-0500 (Central Daylight Time)] node created with nodeID 93a1b313f8ea34d8cf6b55b73dc7c489c50f5813
```

So, the farmer successfully traversed and setup two ports: 49233 and 33024. Neither is 57534. So, not sure where the fault here lies. Did the farmer not send the right port information? Does the client uploader not honor the different port?

**Comment by bookchin** [comment]
Are you offering tunnels to the network? That is likely another node tunneled through you.

**Comment by utdrmac** [comment]
Yes, looks like I am allowing 3 tunnels.

**Comment by bookchin** [comment]
Can you check your log and verify if you see:

```
gateway opened for <nodeid> at <addr,port>
```

**Comment by bookchin** [comment]
Let me know so I can close this or determine if there is actually an issue.

**Comment by utdrmac** [comment]
Will have to let you know when I'm back home on Monday.

**Comment by utdrmac** [comment]
@bookchin Yes, i found several lines matching that in the logs on my Windows GUI. Now that I'm back home, I can see that I did eventually get some contracts from others. Drive #0 is sharing 40GB and Drive #1 is sharing 15GB. Drive#1 is 100% with 12,262 contracts. Drive#0 is 25% wil 9,012 contracts.
