### ISSUE TITLE
Add support for HD private keys

### ISSUE THREAD

**Issue by bookchin** [Storj/core#281]
This is needed so that a single identity can have multiple node IDs. This is important for bridges to be able to run minion pools that exist in many different sections of the network key space allowing for bigger pools of peers to publish contracts to for shards that hash to a key that has a significant distance from the bridge's own node ID. 

Additionally this can provide a means for tying a payment address to the same private key used for node ID generation without exposing the link. Also, great for running many nodes that use the same private key, but yield different node IDs.

**Comment by super3** [comment]
https://github.com/Storj/sips/pull/7
