### ISSUE TITLE
Windows progress bar GUI chews up CPU

### ISSUE THREAD

**Issue by utdrmac** [Storj/core#282]
I have the GUI open on Windows 7 (Quad i7, 16GB, 512GB ati graphics card). The blue progress bar, representing the amount of space used by contracts, has some constant animation, even when at 100% full. This is causing StorjShare.exe to use an unnecessary high amount of CPU (25%-50%) and makes overall responsiveness within the GUI extremely sluggish. Clicking on the menu in the upper right, next to the gear, to switch between drives takes a good 2-3 seconds to render and execute.

Please remove the animation of the progress bar. It is unnecessary fluff.

**Comment by bookchin** [comment]
This belongs in https://github.com/Storj/storjshare-gui

**Comment by utdrmac** [comment]
https://github.com/Storj/storjshare-gui/issues/302
