### ISSUE TITLE
WIP bridge is sending to many tunnel PUBLISH messages

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#283]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.2.3
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by bookchin** [comment]
Right now we publish a tunnel announcement whenever we fill up and whenever we have a tunnel free. This is probably too noisy. This is probably best solved by reverting to the original method of doing a tunnel announce every 15 minutes. Now that we have tunnel retry logic, this is should be fine.
