### ISSUE TITLE
Removing a bucket containing files doesn't warn user

### ISSUE THREAD

**Issue by utdrmac** [Storj/core#289]
I uploaded 100 files to a bucket. I then called remove-bucket. Received 'bucket successfully destroyed.' For end-user safety, do you think removing a bucket containing files should be disallowed without some additional flag?

### Expected Result
```
root@gasgiant:~# storj remove-bucket 575869851f545db43016498d
 [Mon Jul 25 2016 11:25:27 GMT-0500 (CDT)] [error]   Bucket contains files. Will not remove bucket without --not-empty-ok.
```

On the network side, does removing a bucket containing files also remove those files? Or are all of those files now in "limbo" (ie: existing on the network but not in a bucket and no way to be retrieved)?

**Comment by bookchin** [comment]
Removing the bucket does not remove the files from the network but will ultimately terminate the contract associated as well. 

Yeah I'm down with a prompt/flag for confirming destructive operations.

**Comment by utdrmac** [comment]
So if you delete a bucket with files, you're essentially letting the network clean up the mess?

**Comment by bookchin** [comment]
Yeppers
