### ISSUE TITLE
Rethinking setup defaults

### ISSUE THREAD

**Issue by 1credit** [Storj/core#291]
The below likely applies to all releases and is not an operational issue, however when written, the following releases were current:

StorjShare:  5.0.1
Core:          2.0.7
Protocol:    0.7.1
Node:         4.4.4

Currently a few of the defaults for both the CLI and GUI are:

Network port: 4000 (0 for random)
NAT traversal strategies:  true
Payment address: blank (and optional)
Sharing telemetry: false
Number of tunnel ports: 3
Tunnel server port: 0 (for random)
Start port: 0 (for random)
End port: 0 (for random)

I would like to propose the following changes:

UPnP (automatic firewall configuration):  true
Payment address:  Required (0 if you don't want compensation)
Sharing telemetry: true
Tunnel server port: 4001 (0 for random)
Start port: 4002 (0 for random)
End port: 4004 (0 for random)

From the best I can tell, "NAT traversal strategies" is just another name for UPnP.   Please use the industry standard name so that people can Google it and understand.

Making payment address required reflects the unlikely scenario of beta testers being willing to test for free.  Production users will be even less likely to run nodes without the potential for compensation.  Ideally (long term), this address should be validated as well.  Providing the 0 option allows for those that do want to just participate without compensation.

Sharing telemetry should default based on the existence of a payment address.  If someone enters a non-zero address, they clearly expect to be paid, having the next field possibly deny that is not good sportsmanship.   Should the payment address be zero, then the option makes sense.

The tunnel port defaults are simply to aid in debugging, both short and long term.  With default fixed ports, using "netstat" will make it obvious if connections have been established.   Note that UPnP should work just fine with fixed port addresses, unless more than one server is behind the same firewall.  Using random ports MIGHT hide that, or randomly might not, so could confuse things.

For the CLI, the above, shy the address validation, appear be trivial changes in wizard-schema.js, but I could be wrong.

**Comment by bookchin** [comment]
Couple of notes here:

* Sharing telemetry and receiving payment are not mutually inclusive, farmers receive payment for storing shards and that is managed separately from sending telemetry reports. I will never default sending telemetry reports to true - it will *always* be opt-in. This sends data about bandwidth, storage capacity, and uptime to Storj Labs. 
* The NAT traversal strategies are not limited to UPnP, it will try a series of strategies: first UPnP, then fallback to a storj protocol tunnel. Later we will support NAT-PMP and perhaps TCP hole punching. 
* I agree that a payment address should be required, however the core library will actually use the address derived from the ECDSA key pair used to identify you on the network if you do not supply one yourself. This can have privacy implications if the user chooses not to supply one, so I'm up for requiring an address at the application layer. 
* I am also fine with setting static default ports - the ones you listed are fine.

**Comment by 1credit** [comment]
I fully respect not automatically exporting private data - that is very commendable.  

I am, however, confused about your telemetry comment since its strongly implied that telemetry MUST be enabled in order to receive payments:  
http://puu.sh/qft3j/8eb0b63984.png

**Comment by super3** [comment]
@1credit Users are paid for telemetry reports. If they opt-out then they obviously can't be paid for said telemetry reports. It might also affect our ability to give them payments for Test Groups.

**Comment by bookchin** [comment]
Well that language should be changed. The payment address you supply is included in any storage contract you sign and both parties have that. We are fully capable of issuing payments without the telemetry data. 

The telemetry data does help us though and that's why we also issue rewards for those who choose to share it.
