### ISSUE TITLE
Unhandled 'error' event after sending shard

### ISSUE THREAD

**Issue by NutterzUK** [Storj/core#303]
### Package Versions

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ npm list storj
storj-bridge@0.10.1 /vagrant
└── storj@2.0.7
```

Replace the values below using the output from `node --version`.

```
v4.4.3
```

### Expected Behavior

I should be able to send a shard to the farmer.

### Actual Behavior

After starting a bridge and farmers on the vagrant VM with npm run develop, when I come to sending a shard it crashes and turns off everything (Back to the command prompt). It prints out the following log:

```
`{"level":"info","message":"[minion] got network reply to 9f3c76b7a17354e593097b46efac9b29","timestamp":"2016-08-03T18:02:10.731Z"}
{"level":"info","message":"[minion] sending message to amq.gen-Iq5GzHCKSM2qVfj4iIL3wg","timestamp":"2016-08-03T18:02:10.731Z"}
{"level":"info","message":"Sending message to amq.gen-Iq5GzHCKSM2qVfj4iIL3wg","timestamp":"2016-08-03T18:02:10.732Z"}
{"level":"info","message":"Attempting to process message with correlationId 9f3c76b7a17354e593097b46efac9b29","timestamp":"2016-08-03T18:02:10.735Z"}
{"level":"info","message":"Processing message with correlationId 9f3c76b7a17354e593097b46efac9b29","timestamp":"2016-08-03T18:02:10.736Z"}
{"level":"info","message":"data channel connection opened","timestamp":"2016-08-03T18:02:10.958Z"}
{"level":"warn","message":"[renterpool] killing minions","timestamp":"2016-08-03T18:02:10.988Z"}
{"level":"info","message":"[minion] got work on storj.work.renterpool de1e9c441e853296a2e474b8b738d530","timestamp":"2016-08-03T18:02:10.995Z"}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (/vagrant/node_modules/readable-stream/lib/_stream_writable.js:201:12)
    at PassThrough.Writable.write (/vagrant/node_modules/readable-stream/lib/_stream_writable.js:244:20)
    at WebSocket.<anonymous> (/vagrant/node_modules/storj/lib/datachannel/server.js:177:17)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/vagrant/node_modules/storj/node_modules/ws/lib/WebSocket.js:841:10)
    at /vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:371:5)
    at /vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.opcodes.1.finish (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:493:33)
    at Receiver.add (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/vagrant/node_modules/storj/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.4.3/bin/node" "/home/vagrant/.nvm/versions/node/v4.4.3/bin/npm" "run" "develop"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! storj-bridge@0.10.1 develop: `STORJ_ALLOW_LOOPBACK=1 NODE_ENV=develop node script/develop.js start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the storj-bridge@0.10.1 develop script 'STORJ_ALLOW_LOOPBACK=1 NODE_ENV=develop node script/develop.js start'.
npm ERR! This is most likely a problem with the storj-bridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     STORJ_ALLOW_LOOPBACK=1 NODE_ENV=develop node script/develop.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs storj-bridge
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls storj-bridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:`
```

### Steps to Reproduce

vagrant up
vagrant ssh
npm run develop
send a shard using the java client available here: https://github.com/NutterzUK/storj-java-bridge-client

**Comment by bookchin** [comment]
Looking at the code it appears this will happen when you transfer more data than what is defined in the contract. I am adding a fix that will close the socket gracefully and alert you of this.

**Comment by NutterzUK** [comment]
This interesting, as the exact same client with the exact same config etc but pointed at the bridge (api.storj.io) seems to work (I wouldn't know what is happening on the farmer's side) and I get in response:

{"code":200,"message":"Consignment completed"}

This kinda tells me the client is sending the right data? Unless there is a chance it gives this message even if it fails?

This may be linked to a problem i'm having when downloading files, where I send the auth token and the farmer doesn't seem to reply, perhaps because there was an initial problem sending the shard?

**Comment by bookchin** [comment]
Do you not get that response from your local bridge setup?

**Comment by NutterzUK** [comment]
I do. Then the following request the server doesn't respond to (I guess because it turned off). Should I receive "Consignment completed" if I am sending not the correct data? I was under the impression the farmer would only send that if the data was all good and matched the hash.

**Comment by bookchin** [comment]
Yeah, so what's happening is the farmer is sending that back when you send all the data it expects, then it crashes because of the bug I'm fixing now. The problem with your local bridge is that the farmer node runs in the same process as the bridge, so it brings the whole environment down. Which is why it works in production - you're crashing the farmer but not the bridge. :)

**Comment by NutterzUK** [comment]
`{"level":"warn","message":"Contract no longer open to offers","timestamp":"2016-08-10T19:09:19.717Z"}
{"level":"info","message":"data channel connection opened","timestamp":"2016-08-10T19:09:19.743Z"}
{"level":"warn","message":"[renterpool] killing minions","timestamp":"2016-08-10T19:09:19.766Z"}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (/vagrant/node_modules/readable-stream/lib/_stream_writable.js:201:12)
    at PassThrough.Writable.write (/vagrant/node_modules/readable-stream/lib/_stream_writable.js:244:20)
    at WebSocket.<anonymous> (/vagrant/node_modules/storj/lib/datachannel/server.js:202:17)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/vagrant/node_modules/storj/node_modules/ws/lib/WebSocket.js:841:10)
    at /vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:371:5)
    at /vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.opcodes.1.finish (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:493:33)
    at Receiver.add (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/vagrant/node_modules/storj/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)

npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.4.3/bin/node" "/home/vagrant/.nvm/versions/node/v4.4.3/bin/npm" "run" "develop"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! storj-bridge@0.10.2 develop: `STORJ_ALLOW_LOOPBACK=1 NODE_ENV=develop node script/develop.js start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the storj-bridge@0.10.2 develop script 'STORJ_ALLOW_LOOPBACK=1 NODE_ENV=develop node script/develop.js start'.
npm ERR! This is most likely a problem with the storj-bridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     STORJ_ALLOW_LOOPBACK=1 NODE_ENV=develop node script/develop.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs storj-bridge
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls storj-bridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ npm list storj
storj-bridge@0.10.2 /vagrant
└── storj@2.2.0`



This issue wants reopening I think.

**Comment by bookchin** [comment]
@NutterzUK did you get a response code or message from the farmer before it crashed this time? I see two places where this could be - if you got a message/code, I can narrow it down.

**Comment by NutterzUK** [comment]
I do get:
{"code":200,"message":"Consignment completed"}

This is before it crashes.

**Comment by bookchin** [comment]
Okay, fix is included in my working tree. Thanks
