### ISSUE TITLE
Downloads hang indefinitely on occasion

### ISSUE THREAD

**Issue by NicoNet** [Storj/core#310]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
/usr/local/lib
├── storj@2.1.0
└─┬ storjshare-cli@5.0.1
  └── storj@2.1.0
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior
When attempting to download a file from a bucket, the file should download, and if some type of error is encountered, it should say so.  Maybe it should have some sort of inactivity timeout as well.  

### Actual Behavior
When attempting to download a file from a bucket, at times, the application may hang with 100% CPU utilization.  

Example log...
```
storj -k pass download-file 57a6797c905cfece30b14419 W3rqO9bvPQLIEsmJFGZT W3rqO9bvPQLIEsmJFGZT.download
```
 [Sat Aug 06 2016 20:06:46 GMT-0400 (EDT)] [info]   Creating retrieval token...
 [Sat Aug 06 2016 20:06:46 GMT-0400 (EDT)] [info]   Resolving 6 file pointers...
 [Sat Aug 06 2016 20:06:58 GMT-0400 (EDT)] [info]   Creating retrieval token...
 [Sat Aug 06 2016 20:06:58 GMT-0400 (EDT)] [info]   Resolving 6 file pointers...
Will just sit here and do nothing else with 100% CPU utilization.
running an strace, it loops on a block like this very rapidly
```
clock_gettime(CLOCK_MONOTONIC, {703439, 914236870}) = 0
clock_gettime(CLOCK_MONOTONIC, {703439, 914236870}) = 0
clock_gettime(CLOCK_MONOTONIC, {703439, 914236870}) = 0
clock_gettime(CLOCK_MONOTONIC, {703439, 914236870}) = 0
epoll_wait(6, [], 1024, 0)              = 0
```

### Steps to Reproduce

I have written a script that will make a new bucket.  Create several random files.  Upload those.  Then download the files.  Then run a diff.  The uploads run smoothly.  Occasionally, some of the uploads will fail, with errors such as not being able to get a contract.  Then, almost always, one of the 20 downloads will just hang.  I've let a hung download run for at least 12 hours with no progress made.

Script
Change storjKey to your passphrase to unlock your keyring
```
#!/bin/bash
##CONFIG START
#keyring passphrase
storjKey='a'
#size of files to upload (in bytes)
fileSize=1000000
#number of files to upload
fileCount=20
##CONFIG END

#make a new bucket
newBucket=$(storj -k ${storjKey} add-bucket|cut -f13 -d' '|tr -d ',')
for i in $(seq 1 ${fileCount})
do
  #Random file name to create
  randomFN=`head -c 500 /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1`
  #Fill random file with random data
  echo $(head -c 5000000 /dev/urandom | tr -dc 'a-zA-Z0-9~!@#$%^&*_-' | fold -w ${fileSize} | head -n 1) >${randomFN}
  echo ${randomFN} ${i}
  #Upload the file to Storj
  storj -k ${storjKey} upload-file ${newBucket} ${randomFN} >${randomFN}.up.log 2>&1
  echo ${randomFN} ${i} done
done

#get list of files stored
storj -k a list-files $newBucket|while read e
do 
  echo ${e}
  fileID=$(echo ${e}|cut -f17 -d' ')
  fileName=$(echo ${e}|cut -f10 -d' '|tr -d ',')
  echo ${fileID} -- ${fileName}
  #Download file
  storj -k ${storjKey} download-file ${newBucket} ${fileID} ${fileName}.down >${fileName}.down.log 2>&1
  #diff file to see if it matches original
  diff=$(diff ${fileName} ${fileName}.down)
  if [ "$diff" != "" ]
  then
	echo ${fileID} FAILED!  ${fileName}
  else
    echo OK
  fi
  echo ${fileID} -- ${fileName} done
done
```

**Comment by bookchin** [comment]
I tried to reproduce this using your script, but did not have any success. Is there anything else you can think of that may trigger the issue?

**Comment by genavyshel** [comment]
Similar case: CLI hangs while receiving last block of big file(>5MB) from a farmer:
 [Wed Aug 10 2016 16:09:33 GMT+0100 (BST)] [info]   Received 8701382 of 8766918 bytes

But works well for small files like 0.5MB.
The symptomps are exactly the same: 100%CPU utilization

**Comment by genavyshel** [comment]
NicoNet, what's is your network environment like? Any firewalls?

**Comment by genavyshel** [comment]
Looks like the size of penultimate block was estimated incorrectly

Here and before blocks were 65536 bytes long
>  [Wed Aug 10 2016 16:25:42 GMT+0100 (BST)] [info]   Received 8454144 of 8766918 bytes
>  [Wed Aug 10 2016 16:25:42 GMT+0100 (BST)] [info]   Received 8519680 of 8766918 bytes
>  [Wed Aug 10 2016 16:25:42 GMT+0100 (BST)] [info]   Received 8650752 of 8766918 bytes

And here penultimate block...it is supposed to be 8716288(in case of using 65536-bytes buffer), but it was: 
>  [Wed Aug 10 2016 16:25:42 GMT+0100 (BST)] [info]   Received 8701382 of 8766918 bytes

which is exactly like the last block should be:
8701382 - 8650752 = **50630**
8766918 mod 65536 = **50630**

**Comment by bookchin** [comment]
Interesting, I'll generate some random data of that size and see if I can reproduce this.

**Comment by NicoNet** [comment]
Nothing too special.  Google Onhub router (tplink). 

Ports 7875-7999 forwarded to my Windows system to Storj farmer.   

Port 22 forward to my Linux system for SSH.  Port 34197 for a Factorio server.  Ports 3978-3979 for OpenTTD server. 

Iptables has no rules on the Linux system.

**Comment by genavyshel** [comment]
In my case Storj CLI placed behind firewalls...but not sure if it actually gives anything.
Also hangs when file is less than 65kb working with to channels:

>  [Wed Aug 10 2016 18:39:54 GMT+0100 (BST)] [info]   Creating retrieval token...
>  [Wed Aug 10 2016 18:39:54 GMT+0100 (BST)] [info]   Resolving 6 file pointers...
>  [Wed Aug 10 2016 18:39:55 GMT+0100 (BST)] [info]   Creating retrieval token...
>  [Wed Aug 10 2016 18:39:55 GMT+0100 (BST)] [info]   Resolving 6 file pointers...


Is there anyway how we can reduce the number of open channel via Storj CLI? ))

**Comment by genavyshel** [comment]
The problems were caused by premature emit of FINISH event in BridgeClient._transferShard
```
   shardFile.pipe(datachannel).on('error', _onErr).on('finish', function() {
      emitter.emit('finish');
    });
```

Here we see piping shardFile into datachannel. shardFile might become empty before webscoket in datachannel transmit last buffer to server. 
Receiving response from WSServer must be prior to emitting FINISH into BridgeClient.

So what i did to overcome this issue...
In **BridgeClient._transferShard:**
```
  client._wscb = function(){ emitter.emit('finish');};
  shardFile.pipe(datachannel).on('error', _onErr).on('finish', function() {
  //     emitter.emit('finish');
    });
  });
```

In **DataChannelClient.createWriteStream**
 ```
 this._client.on('message', function(data) {
    try {
      data = JSON.parse(data);
    } catch (err) {
      wstream.emit('error', err);
    }

    if (data.code && data.code !== 200) {
      wstream.emit('error', new Error(data.message));
    }
    //Call the callback from BridgeClient in case we get response from WSServer
    self._wscb();

    this.close();
  });
```

**Comment by genavyshel** [comment]
To clarify my previous statement.
Farmers, that were initially unable to recieve last blocks of shard, store incomplete shard. So client hang waiting for the last block of a shard, whicn it will never recieve. 
100% CPU utilization is more like the result of  

```
while(!socket.empty()){
   //do nothing
}
```
