### ISSUE TITLE
Ability to download/stream a file from arbitrary start and end positions

### ISSUE THREAD

**Issue by NicoNet** [Storj/core#311]
I could say I want 187MB-201MB of a 1GB file.  And, get just that portion rather than downloading/streaming from the start.

**Comment by bookchin** [comment]
This should already be possible with a *little bit* of elbow grease. Use the `BridgeClient#getFilePointers` method to get the slice of shard pointers for the file, then use the `BridgeClient#resolveFileFromPointers` method to get a stream from those slices. Pipe that result through a `stream.Transform` that drops any bytes off the beginning and end of the slice.

If I get some time this week, I'll add an example and maybe add a convenience method for doing so.
