### ISSUE TITLE
Add Library Usage Documentation

### ISSUE THREAD

**Issue by super3** [Storj/core#316]
We have complete documentation on the low level protocol, and plenty of documentation on the API. What we don't have is much documentation on how it ties together into something functional. We should add the following tutorials with complete scripts that the user can run:

- [ ] Authentication to the bridge
- [ ] Encrypting the data
- [ ] Uploading the data
- [ ] Download the data 
- [ ] Decrypting the data 

Might want to make a generic template for this so we can do this for all languages. Will be working with @Miskerest to do the same for the Python library that is currently being revamped.

**Comment by bookchin** [comment]
@aleitner if you add these as markdown files to `doc/` and add entries to `doc/index.json`, they will get published to the documentation site.

**Comment by bookchin** [comment]
Also feel free to add an `example/` directory with any runnable example scripts

**Comment by super3** [comment]
Note we are using this as a template: 
https://github.com/Miskerest/storj-python-sdk
