### ISSUE TITLE
Failure to get a storage offer

### ISSUE THREAD

**Issue by NicoNet** [Storj/core#318]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
/usr/local/lib
├── storj@2.1.1
└─┬ storjshare-cli@5.0.1
  └── storj@2.1.0
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior
If an upload fails, it should be tried again.  Possibly a user defined # of times, with a default.

```

```

### Actual Behavior
Rarely, an upload will fail with the error "[error] No storage offers were received".  The application ends at that point.  Over four 10,000 file upload tests with 1K files, and received this error 67, 82, 55, and 82 times.

```
 [Tue Aug 09 2016 14:14:46 GMT-0400 (EDT)] [info]   Generating encryption key...
 [Tue Aug 09 2016 14:14:46 GMT-0400 (EDT)] [info]   Encrypting file "h3tXeEsrEPSwif4nTpTf.file"
 [Tue Aug 09 2016 14:14:46 GMT-0400 (EDT)] [info]   Encryption complete!
 [Tue Aug 09 2016 14:14:46 GMT-0400 (EDT)] [info]   Creating storage token...
 [Tue Aug 09 2016 14:14:46 GMT-0400 (EDT)] [info]   Storing file, hang tight!
 [Tue Aug 09 2016 14:14:47 GMT-0400 (EDT)] [info]   Trying to upload shard /tmp/d06781d6a62c index 0
 [Tue Aug 09 2016 14:14:47 GMT-0400 (EDT)] [info]   Hash for this shard is: 5ba1c77a09ea93f920dfa88e2bbb125aea70c416
 [Tue Aug 09 2016 14:14:47 GMT-0400 (EDT)] [info]   Audit generation for shard done.
 [Tue Aug 09 2016 14:14:47 GMT-0400 (EDT)] [info]   Waiting on a storage offer from the network...
 [Tue Aug 09 2016 14:14:47 GMT-0400 (EDT)] [info]   Adding shard metadata for 5ba1c77a09ea93f920dfa88e2bbb125aea70c416 to frame
 [Tue Aug 09 2016 14:15:02 GMT-0400 (EDT)] [info]   Adding shard metadata for 5ba1c77a09ea93f920dfa88e2bbb125aea70c416 to frame
 [Tue Aug 09 2016 14:15:18 GMT-0400 (EDT)] [info]   Adding shard metadata for 5ba1c77a09ea93f920dfa88e2bbb125aea70c416 to frame
 [Tue Aug 09 2016 14:15:33 GMT-0400 (EDT)] [info]   Adding shard metadata for 5ba1c77a09ea93f920dfa88e2bbb125aea70c416 to frame
 [Tue Aug 09 2016 14:15:49 GMT-0400 (EDT)] [info]   Adding shard metadata for 5ba1c77a09ea93f920dfa88e2bbb125aea70c416 to frame
 [Tue Aug 09 2016 14:16:04 GMT-0400 (EDT)] [info]   Adding shard metadata for 5ba1c77a09ea93f920dfa88e2bbb125aea70c416 to frame
 [Tue Aug 09 2016 14:16:20 GMT-0400 (EDT)] [info]   Adding shard metadata for 5ba1c77a09ea93f920dfa88e2bbb125aea70c416 to frame
 [Tue Aug 09 2016 14:16:36 GMT-0400 (EDT)] [warn]   Failed to upload shard...
 [Tue Aug 09 2016 14:16:36 GMT-0400 (EDT)] [warn]   Error occured. Triggering cleanup...
 [Tue Aug 09 2016 14:16:36 GMT-0400 (EDT)] [info]   Cleaning up...
 [Tue Aug 09 2016 14:16:36 GMT-0400 (EDT)] [info]   Finished cleaning!
 [Tue Aug 09 2016 14:16:36 GMT-0400 (EDT)] [error]  No storage offers were received
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Perform a upload of a whole bunch of files.
2. Eventually, the error will be encountered.

**Comment by bookchin** [comment]
Currently it does retry 6 times by default, see:

```
 [Tue Aug 09 2016 14:14:47 GMT-0400 (EDT)] [info]   Adding shard metadata for 5ba1c77a09ea93f920dfa88e2bbb125aea70c416 to frame
 [Tue Aug 09 2016 14:15:02 GMT-0400 (EDT)] [info]   Adding shard metadata for 5ba1c77a09ea93f920dfa88e2bbb125aea70c416 to frame
 [Tue Aug 09 2016 14:15:18 GMT-0400 (EDT)] [info]   Adding shard metadata for 5ba1c77a09ea93f920dfa88e2bbb125aea70c416 to frame
 [Tue Aug 09 2016 14:15:33 GMT-0400 (EDT)] [info]   Adding shard metadata for 5ba1c77a09ea93f920dfa88e2bbb125aea70c416 to frame
 [Tue Aug 09 2016 14:15:49 GMT-0400 (EDT)] [info]   Adding shard metadata for 5ba1c77a09ea93f920dfa88e2bbb125aea70c416 to frame
 [Tue Aug 09 2016 14:16:04 GMT-0400 (EDT)] [info]   Adding shard metadata for 5ba1c77a09ea93f920dfa88e2bbb125aea70c416 to frame
 [Tue Aug 09 2016 14:16:20 GMT-0400 (EDT)] [info]   Adding shard metadata for 5ba1c77a09ea93f920dfa88e2bbb125aea70c416 to frame
```

That log message basically means "I'm giving the metadata to bridge and waiting for it to negotiate a contract". The user can in fact specify the number of retries [as seen in the docs for `options.retry`](http://storj.github.io/core/BridgeClient.html#addShardToFileStagingFrame__anchor) though this is not exposed to the CLI at the moment.

I'm all for adding a CLI option to specify the number of retries, but want to note that pending the resolution of some lower level issues around message routing that are being worked on, this should really never happen.

**Comment by NicoNet** [comment]
Is it retrying to the same host every time?  Perhaps it should retry to a different host?  The failures are very spread out, and there isn't like a sequence of them.  On failure, almost always, the next file transferred succeeds.  
I've seen warnings like this where it fails and tries again and succeeds.

```
[Sat Aug 06 2016 18:08:25 GMT-0400 (EDT)] [info]   Adding shard metadata for 9a0ae043e7af7b8a31bac617f02a01f9efae189f to frame
 [Sat Aug 06 2016 18:08:27 GMT-0400 (EDT)] [info]   Contract negotiated with: {"protocol":"0.7.1","address":"76.196.236.76","port":4575,"nodeID":"965ef2f236da31ecf6ec466bf53afb89fff2231e","lastSeen":1470521306625}
 [Sat Aug 06 2016 18:09:30 GMT-0400 (EDT)] [warn]   Failed to transfer shard, reason: connect ETIMEDOUT 76.196.236.76:4575
 [Sat Aug 06 2016 18:09:30 GMT-0400 (EDT)] [info]   Retrying shard transfer, pointer: {"hash":"9a0ae043e7af7b8a31bac617f02a01f9efae189f","token":"fdeb7aaaa0123158420eb02026985c806a487c60","operation":"PUSH","farmer":{"protocol":"0.7.1",
 [Sat Aug 06 2016 18:09:33 GMT-0400 (EDT)] [info]   Data channel opened, transferring shard...
 [Sat Aug 06 2016 18:09:34 GMT-0400 (EDT)] [info]   Shard transfer completed! 0 remaining...
```

In the original issue, it is likely that the farmer is no longer there?  Or maybe it is able to communicate with the bridge, but not my end for some reason?

**Comment by bookchin** [comment]
Those are two separate issues. The original is failure for the bridge to receive an offer for the contract. The other is a failed transfer to the farmer. The former simply will republish the contract, the latter will do the same but exclude the failed farmer from the result.

**Comment by genavyshel** [comment]
Hello, guys =) Actually, had the same problem after migrating from 0.7.0 to 0.7.1
What i've noticed: messages were spawned only after storj client had been staying logged in for several hours without activity.

**Comment by bookchin** [comment]
The changes made in https://github.com/Storj/core/pull/319 should greatly diminish the chance of this happening, so I'm going to close in favor of pushing further issues like this on over to https://github.com/Storj/bridge where optimizations can be made to handle these scenarios better.
