### ISSUE TITLE
Getting error: "Failed to get retrieval token"

### ISSUE THREAD

**Issue by plul** [Storj/core#320]
### Package Versions

Output from `npm list -g storj`:

```
/home/plul/.nvm/versions/node/v4.4.5/lib
└─┬ storjshare-cli@5.0.2
  └── storj@2.2.0
```

Output from `node --version`:

```
v4.4.5
```

This is running on an Ubuntu 16.04 VPS on Scaleway.

### Expected Behavior

I am following along with the upload/download tutorial at http://docs.storj.io/docs/uploading-and-downloading-cats , yet at step 4, `storj download-file` I get an error that I cannot find in the common issues page.

### Actual Behavior

Program terminates after the following messages:

```
 [Thu Aug 11 2016 07:44:44 GMT+0000 (UTC)] [info]   Creating retrieval token...
 [Thu Aug 11 2016 07:44:45 GMT+0000 (UTC)] [info]   Resolving 6 file pointers...
 [Thu Aug 11 2016 07:44:48 GMT+0000 (UTC)] [error]  Failed to get retrieval token
```

### Steps to Reproduce

I have simply tried to follow along with the getting started guide (creating an account) and then the upload/download guide here http://docs.storj.io/docs/uploading-and-downloading-cats

Note: The package version info above shows `storjshare` in addition to `storj`. I have installed `storjshare` in between getting this error and submitting this issue. `storjshare` was not installed when this issue first occurred.

**Comment by bookchin** [comment]
This error means that the farmer who stored the data was not reachable. You can avoid this in the future by creating mirrors when you upload the file by adding the `-r <number of mirrors>` option.

Ideally, we should automatically establish a few mirrors without any user input to do so, so let's open an issue for that: https://github.com/Storj/core/issues/332
