### ISSUE TITLE
Add cryptographic key/keyring documentation

### ISSUE THREAD

**Issue by Miskerest** [Storj/core#324]
I need documentation for how the node client's keyring/encryption functions work. I'm working on the Python SDK and without this documentation it won't be possible to have inter-operability with other clients, as files wont be able to be decrypted or encrypted from different clients.

A simple explanation defining the `export-keyring` feature and how it's output can tie into the AES-CTR standard would suffice. This can be broken down into:

- [ ] How keys are generated from user input

- [ ] How the counter input is calculated

- [ ] How exported keys are encoded, if at all

- [ ] A general overview for how the `counter + keyring_password -> aes_key`

**Comment by jackyq2015** [comment]
I am also confusing about the address created from wallet.counterwallet.io and the owner address for SJCX from the "show info" drop down menu. I assume that the owner address is the payout address I filled in from the GUI. But it's not! it is an address I never see and does not seem to own.

**Comment by bookchin** [comment]
@miskerest I will spend some time adding a doc for this stuff next week. 

@jackyq2015 your comment is not related to this ticket.

**Comment by Miskerest** [comment]
Pertinent docs are located here: https://github.com/Storj/core/blob/master/doc/file-encryption.md

**Comment by bookchin** [comment]
Prettier ones here: http://storj.github.io/core/tutorial-file-encryption.html :)
