### ISSUE TITLE
leveldb clean doesn't release free space

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#334]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
└─┬ storjshare-cli@5.0.2
  └── storj@2.2.0 
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Once a day a cleanup job should delete old shards. The free spae can be used for new shars.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

https://github.com/Storj/core/blob/db24a6c653e6653cb4844ef3374aadf69f3dcd13/lib/storage/manager.js#L121

My Version of this task:
```
var storj = require('storj');
var persistence = new storj.LevelDBStorageAdapter('/root/.storjshare/farmer.db');
var manager = new storj.Manager(persistence);

var StorageAdapter = require('storj/lib/storage/adapter');
var StorageItem = require('storj/lib/storage/item');

var rstream = manager._storage.createReadStream();
rstream.on('data', function(item) {
  rstream.pause();

  var total = Object.keys(item.contracts).length;
  var endedOrIncomplete = 0;

  for (var nodeID in item.contracts) {
    var ended = item.contracts[nodeID].get('store_end') < Date.now();
    var incomplete = !item.contracts[nodeID].isComplete();
    var badRenter = item.contracts[nodeID].get('renter_id') !== '593844dc7f0076a1aeda9a6b9788af17e67c1052';
    if (ended || incomplete || badRenter) {
      endedOrIncomplete++;
    }
  }

  if (total === endedOrIncomplete) {
    console.log(item.hash);
    manager._storage.del(item.hash, function(/* err */) {
      rstream.resume();
    });
  } else {
    rstream.resume();
  }

});

rstream.on('end', function() {
  manager._checkCapacity();
  process.exit();
});
```

Running the script will delete the db entries but not the space on my drive. -> I can't except new shards even if the clean job deletes old shards. The leveldb compact function should solve this but I didn't find a way to call it myself.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Farm a few GB shards.
2. Change the clean task to delete all shards.
3. After executing clean task the farmer.db folder has the same size. No free space for new shards.

**Comment by bookchin** [comment]
LevelDB writes tombstones for deleted entries until the next compaction. We can trigger a compaction with `leveldown.repair()` which will be implemented for https://github.com/Storj/storjshare-cli/issues/132.

**Comment by bookchin** [comment]
However, the `clean()` task should not call this itself, instead relying on leveldb to perform compaction when appropriate. In order to trigger compaction this way, we have to close the database, trigger, then reopen. This will have undesirable side effects for most scenarios where the allocated space is not full during a clean, preventing any reads or writes until the compaction completes. 

For that reason, I'm going to close this issue in favor of implementing  https://github.com/Storj/storjshare-cli/issues/132 which will be triggered from storjshare by the user, explicitly.

**Comment by littleskunk** [comment]
```
root@farmer:/usr/local/lib/node_modules/storjshare-cli# storjshare repair-db
 [info]   Initializing DB repair and compaction...
 [info]   DB repair and compacation completed successfully!
```

```
2016/08/19-06:12:04.358768 7fe003fff700 Delete type=3 #1
2016/08/19-06:12:04.716263 7fe0019d2700 Moved #1431459 to level-1 834 bytes OK: files[ 206302 1 0 0 0 0 0 ]
2016/08/19-06:12:04.922761 7fe0019d2700 Compacting 64907@0 + 0@1 files
2016/08/19-06:15:09.392728 7fe0019d2700 compacted to: files[ 206302 1 0 0 0 0 0 ]
2016/08/19-06:15:09.392804 7fe0019d2700 Compaction error: IO error: /root/.storjshare/farmer.db/3655454.ldb: Too many open files
```

**Comment by bookchin** [comment]
:/ I don't know what to say, there isn't anything we can do about this. I would suggest using `ulimit` to increase the number of allowed file descriptors open and try again.

**Comment by bookchin** [comment]
Let me dig around and see if we can tell the native driver to limit open file descriptors...

**Comment by bookchin** [comment]
Woo! Looks like we *can* do it. However the default max files is only 1000. I would think that's generally an acceptable limit. Can you tell me what your system's default is?

**Comment by bookchin** [comment]
Well, I take that back. We can limit the max files when opening the db which will fix this issue for normal compaction, however the driver does not accept these options when using `repair()`. I've opened an issue here: https://github.com/Level/leveldown/issues/301

Will wait for movement there before we can do anything.

**Comment by littleskunk** [comment]
intermediate results:

I didn't try the repair command a second time. While my node is running leveldb starts compacting on his own and with the last core release without any error messages.

I still have no free space even if leveldb is compacting everything. Lets wait for the final result to panic.

My node needs more than 24 hours already and it looks like it will take some more days. -> I am lucky that the repair command stoped with an error. My node would be offline for days.

```
2016/08/21-14:43:09.853835 7fcb335e7700 Moved #2118659 to level-1 2104659 bytes OK: files[ 111043 88904 0 0 0 0 0 ]
2016/08/21-14:43:10.002911 7fcb335e7700 Compacting 31758@0 + 0@1 files
```

**Comment by littleskunk** [comment]
ulimit -a
open files (-n) 1024

```
2016/08/22-01:33:13.456982 7f04c0e1d700 Compacting 78735@0 + 98029@1 files
2016/08/22-01:36:24.226040 7f04c0e1d700 compacted to: files[ 78765 98029 20945 0 0 0 0 ]
2016/08/22-01:36:24.235033 7f04c0e1d700 Compaction error: IO error: /root/.storjshare/farmer.db/3772957.ldb: Too many open files
```

**Comment by deadgray** [comment]
For historical use:
/etc/security/limits.conf
```
*               hard    nofile          10240    
*               soft    nofile          10240     
```
then reboot, will set system-wide limits (all users) to 10k open files.

**Comment by aleitner** [comment]
We have an in progress improvement to the storage adaptor that shall resolve this issue.
https://github.com/Storj/core/issues/143
