### ISSUE TITLE
Token Expiration on Website (apps.storj.io)

### ISSUE THREAD

**Issue by computeronix** [Storj/core#337]
I hope this is the right place to put this...

I noticed today that the https://app.storj.io/ does not have a token expiration (or if it does it is really really long).  I created my bucket about a monthish ago and when I clicked Login today it remembered me and signed right in.

I would recommend adding a Token expiration (or making it shorter if it is there) for security.

**Comment by super3** [comment]
This belongs in https://github.com/Storj/bridge
