### ISSUE TITLE
Upload File Example Not Working

### ISSUE THREAD

**Issue by rdegges** [Storj/core#341]
### Package Versions

```
secure-storage@1.0.0 /home/rdegges/Dropbox/Code/rdegges/secure-storage
└── storj@3.0.1 
```

Replace the values below using the output from `node --version`.

```
v6.3.1
```

### Expected Behavior

I'm trying to get the file upload example in the latest master branch to work as expected and let me upload a file to storj: https://github.com/Storj/core/blob/master/example/6a-upload-file.js

I'm testing this on very small local files.

### Actual Behavior

What happens is that after my code reaches this line, this callback never finishes firing, even for small files (a few KB): https://github.com/Storj/core/blob/master/example/6a-upload-file.js#L45

It appears to me that the `client.storeFileInBucket` method is not working.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install storj.
2. Copy the example code from: https://github.com/Storj/core/blob/master/example/6a-upload-file.js
3. Hardcode in a new `filepath` value and the path to your private key.
4. Run the code.
5. It will hang on the `client.storeFileInBucket` callback and will never finish executing.

**Comment by bookchin** [comment]
Please see the release notes, we are deploying the bridge updates today. https://github.com/Storj/core/releases/tag/v3.0.0

**Comment by rdegges** [comment]
D'oh, sorry. Completely missed this. Thanks =)

**Comment by bookchin** [comment]
No problem. Also keep in mind we supported the LTS release of node, so you might like to install 4.x.x instead of 6
