### ISSUE TITLE
File upload task stops and exits without error  (core v.3.0.3) - windows 10

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#347]
### Package Versions

npm --version: 2.15.9

node --version: 4.5.0

core version : 3.0.3

OS: windows 10 home edition

### Expected Behavior

clean exit with 'failed-upload message' or continuous retry of upload.

### Actual Behavior

7bec37370199f889f3 to frame
 [Thu Aug 18 2016 23:21:48 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 0f1f87cc21d1107cd20458336d43727c07dda54e to frame
 [Thu Aug 18 2016 23:21:53 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 82d38aeeaa21b0d4dd2c5c8643f5298f879a8977 to frame
 [Thu Aug 18 2016 23:21:55 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 2b68ac9089705628cf4449a16a94d56838432cb5 to frame
 [Thu Aug 18 2016 23:21:57 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 8317ac5abc3fb9cdda4defbdc089fa0c62f6dea0 to frame
 [Thu Aug 18 2016 23:21:58 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 4e788d71f9ce64260d2d65b1e6123fbbd43e5f4e to frame
 [Thu Aug 18 2016 23:22:02 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 8970ed8333fa8d599c702e7bec37370199f889f3 to frame
 [Thu Aug 18 2016 23:22:04 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 0f1f87cc21d1107cd20458336d43727c07dda54e to frame
 [Thu Aug 18 2016 23:22:09 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 82d38aeeaa21b0d4dd2c5c8643f5298f879a8977 to frame
 [Thu Aug 18 2016 23:22:10 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
 [Thu Aug 18 2016 23:22:10 GMT+0200 (W. Europe Daylight Time)] [warn]   Error occured. Triggering cleanup...
 [Thu Aug 18 2016 23:22:10 GMT+0200 (W. Europe Daylight Time)] [info]   Cleaning up...
 [Thu Aug 18 2016 23:22:11 GMT+0200 (W. Europe Daylight Time)] [info]   Finished cleaning!
 [Thu Aug 18 2016 23:22:11 GMT+0200 (W. Europe Daylight Time)] [error]  No storage offers were received
 [Thu Aug 18 2016 23:22:13 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 8317ac5abc3fb9cdda4defbdc089fa0c62f6dea0 to frame
 [Thu Aug 18 2016 23:22:18 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 8970ed8333fa8d599c702e7bec37370199f889f3 to frame

C:\WINDOWS\system32>

### Steps to Reproduce

upload a file.

**Comment by MeijeSibbel** [comment]
This issue only appears when you upload large files (+5GB), for small files these errors do not appear.

**Comment by bookchin** [comment]
Ah shit, I broke it. There are two things here:

1. The concurrent shard uploads are still not being cancelled properly when there is an error, so we need to fix that (more)
2. We are now performing a smarter calculation of the optimal shard size for a given file that increases based on the size of the complete file. When a contract gets published, the opcode sequence that identifies the topic for the contract get automatically generated based on the contract parameters (of which the shard size is one). The size opcode will be created as null if it exceeds 32mb (because of a bug in that part of the library). For this reason, no farmers are subscribed to the topic because it is not valid and thus no farmers will send an offer to store. 

Hotfix tomorrow with the v3.0.3 PR that is open now.  Thanks for the report.

**Comment by MeijeSibbel** [comment]
The file that did pass the upload( 1GB file) gave me this at the end:

 [Fri Aug 19 2016 02:47:27 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Fri Aug 19 2016 02:47:29 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 0 remaining...
 [Fri Aug 19 2016 02:47:29 GMT+0200 (W. Europe Daylight Time)] [info]   Transfer finished, creating entry...
 [Fri Aug 19 2016 02:47:29 GMT+0200 (W. Europe Daylight Time)] [info]   Cleaning up...
 [Fri Aug 19 2016 02:47:29 GMT+0200 (W. Europe Daylight Time)] [info]   Finished cleaning!
 [Fri Aug 19 2016 02:47:29 GMT+0200 (W. Europe Daylight Time)] [info]   Encryption key saved to keyring.
 [Fri Aug 19 2016 02:47:29 GMT+0200 (W. Europe Daylight Time)] [info]   File successfully stored in bucket.
 [Fri Aug 19 2016 02:47:29 GMT+0200 (W. Europe Daylight Time)] [info]   Name: 1GB, Type: application/octet-stream, Size: 1308622848 bytes, ID: 57b657230c97558c3c4a34d5
 [Fri Aug 19 2016 02:47:29 GMT+0200 (W. Europe Daylight Time)] [info]   Establishing 1000 mirrors per shard for redundancy
 [Fri Aug 19 2016 02:47:29 GMT+0200 (W. Europe Daylight Time)] [info]   This can take a while, so grab a cocktail...
 [Fri Aug 19 2016 02:49:21 GMT+0200 (W. Europe Daylight Time)] [error]  <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>

------------------------------------------------
- The upload process was stuck for like 45 minutes before giving me these final lines.

**Comment by bookchin** [comment]
Well I would certainly expect establishing 1000 mirrors to take a while. The 502 is from the nginx proxy in front of the bridge timing out waiting for a response.

**Comment by MeijeSibbel** [comment]
I get this new error when uploading a file a 2x that succeeded before, probably also related to the same issue:


[Fri Aug 19 2016 13:10:23 GMT+0200 (W. Europe Daylight Time)] [info]   Retrying shard transfer, pointer: {"hash":"5b7a36718f1a4e737b26995750115e6c3ae0089b","token":"132f9209e64a4d50c237812695aa577450101b75","operation":"PUSH","farmer":{"protocol":"0.8.0","address":"89.231.22.170","port":32538,"nodeID":"45a4fbf2572b7ae5f498d8d1e7b313016ec24943","lastSeen":1471604757257}}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, open 'C:\Users\meije\AppData\Local\Temp\b061e8fcb19d'
    at Error (native)

C:\WINDOWS\system32>
