### ISSUE TITLE
File upload process hangs during upload of last/last few shards.

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#357]
### Package Versions

npm --version: 2.15.9

node --version: 4.5.0

core version : 3.0.4

python --version: 2.7.12

OS: windows 10 home edition

### Expected Behavior

file upload complete, clean exit. 

### Actual Behavior

The upload goes well for 99%, during the last 1% of the upload (last 1-5 shards) the upload halts and just sits there doing nothing (max 18 hours so far, still hanging). 

example:

[Sat Aug 20 2016 13:28:15 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 5 remaining...
 [Sat Aug 20 2016 13:28:20 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 67f0e0506dac9b65eebcf23813c04b659a12aa04 to frame
 [Sat Aug 20 2016 13:28:22 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 1e24f282c2ebf8d0296e9242131cc2776c93f2df to frame
 [Sat Aug 20 2016 13:28:25 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"5.15.8.218","port":52268,"nodeID":"1c7a44fdad1403584784e9220b8ca18cb876dd56","lastSeen":1471692509099}
 [Sat Aug 20 2016 13:28:25 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Sat Aug 20 2016 13:28:30 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 1c36cc7d60afa419f8251c624406058f4aa13f8a to frame
 [Sat Aug 20 2016 13:28:33 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 4 remaining...
 [Sat Aug 20 2016 13:28:35 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"138.201.13.159","port":4105,"nodeID":"1c9be241580706f09c2d60a526c01dc9e068e7c9","lastSeen":1471692518302}
 [Sat Aug 20 2016 13:28:35 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Sat Aug 20 2016 13:28:37 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"80.237.71.105","port":6344,"nodeID":"631c052fec35be6c06ce130086b464877098ff8e","lastSeen":1471692512867}
 [Sat Aug 20 2016 13:28:38 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Sat Aug 20 2016 13:28:56 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 3 remaining...
 [Sat Aug 20 2016 13:28:57 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 2 remaining...

The process hangs after this for a unlimited amount of time.

### Steps to Reproduce

Upload a large file(1GB+).

**Comment by littleskunk** [comment]
Confirmed and I have the perfect logfile.
`storj upload-file -c 9 <bucketID> D:\iso\ubuntu-14.04.3-desktop-amd64.iso`  ~1GB

[Upload.txt](https://github.com/Storj/core/files/428731/Upload.txt)

63 Trying to upload shard
63 Hash for this shard is
63 Audit generation for shard done
63 Waiting on a storage offer from the network
**65 Adding shard metadata for**
63 Contract negotiated with
63 Data channel opened, transferring shard
**62 Shard transfer completed**

At the end I have one open data channel but the shard transfer is not completed. Even LAN disconnect has no effect. The last shard is still missing.

Lets take a look at the 65 shard metadata. `70f0b66eff952d1492b2bfc49b95408895fe858b` and `566ab962d5c736a022e00612bfd0c1e333445d73` are duplicate.
```
 [Sun Aug 21 2016 09:18:36 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Trying to upload shard C:\Users\Skunk\AppData\Local\Temp\9413f2247402 index 1
 [Sun Aug 21 2016 09:18:37 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Hash for this shard is: 70f0b66eff952d1492b2bfc49b95408895fe858b
 [Sun Aug 21 2016 09:18:37 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Trying to upload shard C:\Users\Skunk\AppData\Local\Temp\c6170bb421a8 index 2
 [Sun Aug 21 2016 09:18:37 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Hash for this shard is: 1d10290d098b22f7c6f2b0b78f6559d336f2824a
 [Sun Aug 21 2016 09:18:37 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Audit generation for shard done.
 [Sun Aug 21 2016 09:18:37 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Waiting on a storage offer from the network...
 [Sun Aug 21 2016 09:18:37 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Adding shard metadata for 70f0b66eff952d1492b2bfc49b95408895fe858b to frame
 [Sun Aug 21 2016 09:18:37 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Trying to upload shard C:\Users\Skunk\AppData\Local\Temp\d5f82fd98dff index 3
 [Sun Aug 21 2016 09:18:37 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Hash for this shard is: d36c68b7fb94e2897d940164bcdf514353a9f5b7
 [Sun Aug 21 2016 09:18:37 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Audit generation for shard done.
 [Sun Aug 21 2016 09:18:37 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Waiting on a storage offer from the network...
 [Sun Aug 21 2016 09:18:37 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Adding shard metadata for 1d10290d098b22f7c6f2b0b78f6559d336f2824a to frame
 [Sun Aug 21 2016 09:18:38 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Trying to upload shard C:\Users\Skunk\AppData\Local\Temp\f4d68022484d index 4
 [Sun Aug 21 2016 09:18:38 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Hash for this shard is: 3c0f432c9bfe4f8ce6edb5baee0cf3fda1dc6e61
 [Sun Aug 21 2016 09:18:38 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Audit generation for shard done.
 [Sun Aug 21 2016 09:18:38 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Waiting on a storage offer from the network...
 [Sun Aug 21 2016 09:18:38 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Adding shard metadata for d36c68b7fb94e2897d940164bcdf514353a9f5b7 to frame
 [Sun Aug 21 2016 09:18:38 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Trying to upload shard C:\Users\Skunk\AppData\Local\Temp\c6d5486c8e35 index 5
 [Sun Aug 21 2016 09:18:38 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Hash for this shard is: 71c24a7c610759eb42d5505ceaa7f520ecc34558
 [Sun Aug 21 2016 09:18:38 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Audit generation for shard done.
 [Sun Aug 21 2016 09:18:38 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Waiting on a storage offer from the network...
 [Sun Aug 21 2016 09:18:38 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Adding shard metadata for 3c0f432c9bfe4f8ce6edb5baee0cf3fda1dc6e61 to frame
 [Sun Aug 21 2016 09:18:39 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Trying to upload shard C:\Users\Skunk\AppData\Local\Temp\cba4449335c6 index 6
 [Sun Aug 21 2016 09:18:39 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Hash for this shard is: cc73e6416b096c1a952f5954f1d06013ce95aaf9
 [Sun Aug 21 2016 09:18:39 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Audit generation for shard done.
 [Sun Aug 21 2016 09:18:39 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Waiting on a storage offer from the network...
 [Sun Aug 21 2016 09:18:39 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Adding shard metadata for 71c24a7c610759eb42d5505ceaa7f520ecc34558 to frame
 [Sun Aug 21 2016 09:18:39 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Trying to upload shard C:\Users\Skunk\AppData\Local\Temp\d86142fec575 index 7
 [Sun Aug 21 2016 09:18:39 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Hash for this shard is: c22ae4cbf0f9a86e8b631db7a87c04060cdf1c4b
 [Sun Aug 21 2016 09:18:39 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Audit generation for shard done.
 [Sun Aug 21 2016 09:18:39 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Waiting on a storage offer from the network...
 [Sun Aug 21 2016 09:18:39 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Adding shard metadata for cc73e6416b096c1a952f5954f1d06013ce95aaf9 to frame
 [Sun Aug 21 2016 09:18:40 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Trying to upload shard C:\Users\Skunk\AppData\Local\Temp\877560aa8914 index 8
 [Sun Aug 21 2016 09:18:40 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Hash for this shard is: 05d644b8c2065db6eb37cc437a97de71cc76c646
 [Sun Aug 21 2016 09:18:40 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Audit generation for shard done.
 [Sun Aug 21 2016 09:18:40 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Waiting on a storage offer from the network...
 [Sun Aug 21 2016 09:18:40 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Adding shard metadata for c22ae4cbf0f9a86e8b631db7a87c04060cdf1c4b to frame
 [Sun Aug 21 2016 09:18:40 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Hash for this shard is: a2a0ee142056ade29601643a80f0a3b72c61ba14
 [Sun Aug 21 2016 09:18:40 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Audit generation for shard done.
 [Sun Aug 21 2016 09:18:40 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Waiting on a storage offer from the network...
 [Sun Aug 21 2016 09:18:40 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Adding shard metadata for 05d644b8c2065db6eb37cc437a97de71cc76c646 to frame
 [Sun Aug 21 2016 09:18:40 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Audit generation for shard done.
 [Sun Aug 21 2016 09:18:40 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Waiting on a storage offer from the network...
 [Sun Aug 21 2016 09:18:40 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Adding shard metadata for a2a0ee142056ade29601643a80f0a3b72c61ba14 to frame
 [Sun Aug 21 2016 09:18:41 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"storj2.sdo-srv.com","port":4000,"nodeID":"7050a71f33ed0d7b9e974e01c4b41f8772f0b314","lastSeen":1471763916391}
 [Sun Aug 21 2016 09:18:41 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"80.237.71.105","port":6260,"nodeID":"304e89d25585d12f12553ba8d5496803103ff778","lastSeen":1471763916044}
 [Sun Aug 21 2016 09:18:41 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Data channel opened, transferring shard...
 [Sun Aug 21 2016 09:18:41 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Data channel opened, transferring shard...
 [Sun Aug 21 2016 09:18:41 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"ormgas.com","port":4000,"nodeID":"d24f5552fa9a678927c836e5ac045e5df14c2412","lastSeen":1471763916630}
 [Sun Aug 21 2016 09:18:42 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"STORJ-CLUS-025.storj.space","port":4100,"nodeID":"06b738b3fafe1a0e8b2720b8316dbbbfe3433764","lastSeen":1471763917570}
 [Sun Aug 21 2016 09:18:42 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"40.79.75.79","port":4000,"nodeID":"c6447d2aac3ad5fcc0977f46f302e21c93dcf341","lastSeen":1471763917021}
 [Sun Aug 21 2016 09:18:42 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"STORJ-CLUS-026.storj.space","port":4300,"nodeID":"b6cbcf940f9e892234aa967dfdf1f78914c7c5cf","lastSeen":1471763917806}
 [Sun Aug 21 2016 09:18:42 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Data channel opened, transferring shard...
 [Sun Aug 21 2016 09:18:42 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"67.181.126.109","port":65384,"nodeID":"c026577a0011e4dd2b8fe958fb180911582d0df5","lastSeen":1471763916987}
 [Sun Aug 21 2016 09:18:42 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Data channel opened, transferring shard...
 [Sun Aug 21 2016 09:18:42 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Data channel opened, transferring shard...
 [Sun Aug 21 2016 09:18:42 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Data channel opened, transferring shard...
 [Sun Aug 21 2016 09:18:43 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Data channel opened, transferring shard...
 [Sun Aug 21 2016 09:19:06 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Adding shard metadata for 70f0b66eff952d1492b2bfc49b95408895fe858b to frame
[...]
[Sun Aug 21 2016 09:29:57 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Shard transfer completed! 21 remaining...
 [Sun Aug 21 2016 09:29:57 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Trying to upload shard C:\Users\Skunk\AppData\Local\Temp\39936467d593 index 50
 [Sun Aug 21 2016 09:29:57 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Hash for this shard is: 566ab962d5c736a022e00612bfd0c1e333445d73
 [Sun Aug 21 2016 09:29:57 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Audit generation for shard done.
 [Sun Aug 21 2016 09:29:57 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Waiting on a storage offer from the network...
 [Sun Aug 21 2016 09:29:57 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Adding shard metadata for 566ab962d5c736a022e00612bfd0c1e333445d73 to frame
 [Sun Aug 21 2016 09:30:13 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Adding shard metadata for 566ab962d5c736a022e00612bfd0c1e333445d73 to frame
 [Sun Aug 21 2016 09:30:15 GMT+0200 (Mitteleuropäische Sommerzeit)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"storj1.sdo-srv.com","port":4000,"nodeID":"b13a2e881a9d5e525fab0e505d77dfb76d6c5611","lastSeen":1471764610748}
```

**Comment by littleskunk** [comment]
I think @NutterzUK has the same issue and found the problem https://github.com/Storj/core/issues/355#issuecomment-241283059

**Comment by MeijeSibbel** [comment]
yes indeed, he is basically having the same issue but in the other direction (downloading).

**Comment by MeijeSibbel** [comment]
My uploads are not hanging anymore, but now instead i get this error:

[Mon Aug 22 2016 20:40:55 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
[Mon Aug 22 2016 20:40:55 GMT+0200 (W. Europe Daylight Time)] [warn]   Error occurred. Triggering cleanup...
[Mon Aug 22 2016 20:40:55 GMT+0200 (W. Europe Daylight Time)] [info]   Cleaning up...
[Mon Aug 22 2016 20:40:55 GMT+0200 (W. Europe Daylight Time)] [info]   Finished cleaning!
[Mon Aug 22 2016 20:40:55 GMT+0200 (W. Europe Daylight Time)] [error]  No storage offers were received

![2016-08-22](https://cloud.githubusercontent.com/assets/11735738/17867316/4d753f6c-68aa-11e6-82db-4c79acb481a8.png)

**Comment by aleitner** [comment]
just for documenting the hanging issue is generally caused when shard transfer times out and attempts to retry the shard transfer with the same farmer 3 times.

**Comment by MeijeSibbel** [comment]
Some new errors when uploading:

 [Tue Aug 23 2016 01:47:30 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Tue Aug 23 2016 01:47:31 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
 [Tue Aug 23 2016 01:47:31 GMT+0200 (W. Europe Daylight Time)] [warn]   Error occurred. Triggering cleanup...
 [Tue Aug 23 2016 01:47:31 GMT+0200 (W. Europe Daylight Time)] [info]   Cleaning up...
 [Tue Aug 23 2016 01:47:31 GMT+0200 (W. Europe Daylight Time)] [info]   Finished cleaning!
 [Tue Aug 23 2016 01:47:31 GMT+0200 (W. Europe Daylight Time)] [error]  No storage offers were received
 [Tue Aug 23 2016 01:47:36 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: connect ETIMEDOUT 108.238.244.144:8603
 [Tue Aug 23 2016 01:47:42 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: connect ETIMEDOUT 73.40.252.127:4000
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error
    at WritableDataChannelStream._handleClosed (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\lib\data-channels\writable-stream.js:112:18)
    at WebSocket.<anonymous> (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\lib\data-channels\writable-stream.js:28:10)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at WebSocket.cleanupWebsocketResources (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\node_modules\ws\lib\WebSocket.js:950:8)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

C:\WINDOWS\system32>

**Comment by MeijeSibbel** [comment]
And another one:

[Tue Aug 23 2016 01:50:15 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
 [Tue Aug 23 2016 01:50:15 GMT+0200 (W. Europe Daylight Time)] [warn]   Error occurred. Triggering cleanup...
 [Tue Aug 23 2016 01:50:15 GMT+0200 (W. Europe Daylight Time)] [info]   Cleaning up...
 [Tue Aug 23 2016 01:50:15 GMT+0200 (W. Europe Daylight Time)] [info]   Finished cleaning!
 [Tue Aug 23 2016 01:50:15 GMT+0200 (W. Europe Daylight Time)] [error]  No storage offers were received
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write ECONNRESET
    at exports._errnoException (util.js:907:11)
    at WriteWrap.afterWrite (net.js:785:14)

C:\WINDOWS\system32>[Tue Aug 23 2016 01:50:15 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
 [Tue Aug 23 2016 01:50:15 GMT+0200 (W. Europe Daylight Time)] [warn]   Error occurred. Triggering cleanup...
 [Tue Aug 23 2016 01:50:15 GMT+0200 (W. Europe Daylight Time)] [info]   Cleaning up...
 [Tue Aug 23 2016 01:50:15 GMT+0200 (W. Europe Daylight Time)] [info]   Finished cleaning!
 [Tue Aug 23 2016 01:50:15 GMT+0200 (W. Europe Daylight Time)] [error]  No storage offers were received
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write ECONNRESET
    at exports._errnoException (util.js:907:11)
    at WriteWrap.afterWrite (net.js:785:14)

C:\WINDOWS\system32>

**Comment by MeijeSibbel** [comment]
new error while uploading a 700GB zip file: 

[Tue Aug 23 2016 20:00:02 GMT+0200 (W. Europe Daylight Time)] [info]   Retrying shard transfer, pointer: {"hash":"ee7fa9b59ccef9e7f9fc4eb9e3dee1e9b73cb611","token":"6b13a4956a9f631fe0b103dca84d24dad4a7b8cd","operation":"PUSH","farmer":{"protocol":"0.8.0","address":"STORJ-CLUS-009.storj.space","port":4200,"nodeID":"e92fbb4feaa50f90f1f4870e33946242ea8f1202","lastSeen":1471970223115}}
 [Tue Aug 23 2016 20:00:02 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 13.88.251.179:4200
 [Tue Aug 23 2016 20:00:02 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer failed 3 times, getting another contract...
 [Tue Aug 23 2016 20:00:02 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: ee7fa9b59ccef9e7f9fc4eb9e3dee1e9b73cb611
 [Tue Aug 23 2016 20:00:04 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 13.88.251.179:4200
buffer.js:440
    throw new Error('toString failed');
    ^

Error: toString failed
    at Buffer.toString (buffer.js:440:11)
    at C:\Users\meije\AppData\Roaming\npm\node_modules\storj\lib\audit-tools\audit-stream.js:76:26
    at Array.forEach (native)
    at AuditStream._write (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\lib\audit-tools\audit-stream.js:74:16)
    at doWrite (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\node_modules\readable-stream\lib\_stream_writable.js:319:64)
    at writeOrBuffer (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\node_modules\readable-stream\lib\_stream_writable.js:308:5)
    at AuditStream.Writable.write (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\node_modules\readable-stream\lib\_stream_writable.js:246:11)
    at ReadStream.ondata (_stream_readable.js:542:20)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at ReadStream.Readable.push (_stream_readable.js:111:10)
    at onread (fs.js:1739:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)

C:\WINDOWS\system32>

**Comment by computeronix** [comment]
Interesting note on the server, this particular instance's drive is currently set to read-only for testing

So it appears the shards failed to write and after three failures it appears it crashed his client but not the server

**Comment by bookchin** [comment]
@aleitner for reference:

![tmp_26421-screenshot_20160823-233245-650059629](https://cloud.githubusercontent.com/assets/1188875/17917393/0babe62c-698a-11e6-9380-eaa4895f5403.png)

**Comment by MeijeSibbel** [comment]
Just a quick comment:

Somehow if i re-synchronize my clock (internet time) in windows just before uploading a file the success rate of uploading without errors is much larger. After the upload and i try again without synchronizing it will fail, then if i re-synchronize my clock i am able to upload again. is it possible that somehow the time deviation in windows causes some sort of issue for storj?. This is just a empirical test, and i have no idea if it actually works, it might just be a coincidence. I remembered this from a issue with node synchronization in the ethereum geth client that wouldn't synchronize due to the time deviation between the PC time and the network time.
