### ISSUE TITLE
NTP library passes a string instead of an error to callback

### ISSUE THREAD

**Issue by bookchin** [Storj/core#358]
This causes undefined to be logged in storjshare CLI if the request times out. Additionally we should make this fault tolerant and not simply exit if this happens.

**Comment by 1credit** [comment]
Fully concur on both points.

**Comment by bookchin** [comment]
First issue has been fixed in an open PR to the library maintainer. Will point our package.json to my fork until that is merged.

https://github.com/moonpyk/node-ntp-client/issues/8

**Comment by bookchin** [comment]
https://github.com/moonpyk/node-ntp-client/pull/9
