### ISSUE TITLE
Unequal shard distribution

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#359]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
├── storj@3.0.4
```

Replace the values below using the output from `node --version`.

```
v4.4.6
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
I am uploading a ~1GB file (63 shards).
I would expect a equal chance for every farmer.
I should see 63 different farmer on my log.

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

[Upload.txt](https://github.com/Storj/core/files/428754/Upload.txt)
Only a few farmer are getting all of my shards. `8260345d73af2a73dca08cadceadc5d9c408b3d3` has 5 of my shards. As renter I have a problem with that distribution. If this farmer goes offline I will lose 5 shards at once.
As farmer I have a problem as well. I will not get any rewards that way. I can hold 1K SJCX and still get no shards. The meanwhile other farmer are getting all of them.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload a large file with core cli
2. Count the renterIDs.

**Comment by aleitner** [comment]
Is it possible that this happened because the network hasn't completely upgrade d other than an express few people?

**Comment by littleskunk** [comment]
Even in that case I would expect a equal number of shards of each nodeID. Maybe one node could get 2 shards but not 5 shards.

If you look at the contact information of the nodes you will notice a lot of datacenter / hosted VMs. At the moment the first offer will win the race. Low ping and you get them all.

**Comment by bookchin** [comment]
Between the following two features, I think this will be effectively closed:

* https://github.com/Storj/core/issues/511
* https://github.com/Storj/core/issues/281
