### ISSUE TITLE
Allow contract to disallow uploader to delete files

### ISSUE THREAD

**Issue by Tails** [Storj/core#361]
Hi guys, this is a feature/documentation request.

I've looked through the documentation and source code but the following doesn't seem possible (yet).

I am looking for the possibility of having a renter upload files without having the possibility for deleting them. I would like to have the files online as long as they are financed externally (by entities/smart contracts external from the "owner"). The use case is when StorJ would be used by a blockchain network where files are uploaded by miners and kept online by group consensus using an ethereum smart contract that automatically pays out StorJ contracts based on the specific blockchain blocks.

Is this already possible? Through voluntary transfer of ownership (to unusable address) of files perhaps?

**Comment by super3** [comment]
The best way to handle this is not to disable deleting by the renter(this is impossible anyways), but to just have a very high redundancy and contracts from different parties. 

This is possible with no changes to the current contracts or protocol. That being said 90% of the work would just be getting the smart contract in place.
