### ISSUE TITLE
Replace leveldb with a more scalable solution

### ISSUE THREAD

**Issue by 1credit** [Storj/core#363]
<release independent suggestion>

Level DB appears not be be scaling well.  Following the chat channels and from personal experience running Storj, there are several problems:

1)  Loss of a single 2mb shard will result in invalidation of the entire database - potentially TBs gone.  Loss of a shard should invalidate that contract, but not everything.

2)  Excessive open files - reports of 10s of thousands of files being held open, possibly 100s of thousands.  This is not sustainable on most host platforms without significant tweaking and may cause failure on those that just want to "plug and play".  Overhead of course is significant.

3)  Database maintenance (database compaction, expired file deletion, etc.) are reported to take excessive system resources and excessive time (one report of over 24 hours for 650GB of data).

I suggest that leveldb, although a reasonable first choice, is not proving itself appropriate for the long term.  I understand switching would not be easy, and may in fact require wiping of all data and starting over, but that is why this is a Test Group.

Alternatively, simply announce the limitation and advise people not to share more than, say, 500GB per SYSTEM, in order to avoid resource limitations.

Please keep in mind that first and foremost is the need for the final production system to be stable, reliable, and worry free.  That trumps most any other consideration or feature.

**Comment by bookchin** [comment]
Can you move this to a comment on https://github.com/Storj/core/issues/143? That is where we are tracking this known issue.
