### ISSUE TITLE
uploading multiple files does not work

### ISSUE THREAD

**Issue by computeronix** [Storj/core#377]
### Package Versions

```
3.1.0
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

```
should upload all files in a folder
```

### Actual Behavior

```
does not upload any files in the foldr  (should have one file in it)

C:\>storj upload-file 57c3a9f281e21cfd4f3d973f C:\folder
 [Mon Aug 29 2016 21:37:19 GMT-0400 (Eastern Daylight Time)] [info]   0 file(s)
to upload.
 [...]  > Enter your passphrase to unlock your keyring  >  **************

 [Mon Aug 29 2016 21:37:28 GMT-0400 (Eastern Daylight Time)] [info]   Generating
 encryption key...

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. C:\folder
2. Put a txt banlog.txt
3. Run the command above

**Comment by littleskunk** [comment]
I had not time to try it myself. As far as I understand the path must be `C:\folder\*` to upload all files or `C:\folder\cat*.jpg` for cat pictures only.

**Comment by MeijeSibbel** [comment]
When a selected folder for uploading contains sub-folders, Storj will return that there are no files to upload. If the folder contains only files, than it will upload all the files.

**Comment by littleskunk** [comment]
We need a --recursiv flag or something like that: https://github.com/Storj/core/issues/385

Without that flag I would expect the upload of all files exclusiv subfolders. That part is not working at the moment and a bug.

**Comment by aleitner** [comment]
We are using glob patterns for uploading files so you can use /path/* to upload all files within a folder, and /path/**/* to upload all files within a folder recursively

**Comment by utdrmac** [comment]
See comment on #385. The `/**/*` syntax does not work in all cases.
