### ISSUE TITLE
feature request: delete-file order

### ISSUE THREAD

**Issue by computeronix** [Storj/core#378]
As I would like to have a better experience within deleting files using the core, I would like the order for deleting a file procedures to be adjusted per the below information.

New Order when delete-file is issued
1. Prompt for passphrase
2. Check if file exists
3. Prompt to confirm deletion
4. [as skunk suggested] Prompt to delete the encryption key as well (or assume you want it gone automatically)

By adjusting the above information this will allow for a better overall user experience when manipulating files.  It does not not make too much sense first for asking are you sure then ask for the passphrase.  As a user I would like to  first be asked to prompt for the passphrase to then be able to check to see if the file exists.  Why ask me to confirm to delete something that potentially does not exist?

**Comment by littleskunk** [comment]
Can you write this isse as a user story please?

As <user role> I would like to have <new Feature> to be able to <advantage for me>.

Example:
As renter I would like to have a new storj cli command "delete-files". That would allow me to clean up my buckets for a better overview of "list-files" output. Please add a warning and confirmation to remember me about the consequences.

Delete the encryption key as well?

**Comment by computeronix** [comment]
done - re -worded above

**Comment by aleitner** [comment]
In what scenario do you want to keep an encryption key for a file that no longer exists?

**Comment by littleskunk** [comment]
I don't see any reason to keep the key. Don't ask and delete the key.

I think the "problem" in this issue is only the order. Delete-file is working fine but it is confusing for the user.

**Comment by super3** [comment]
1. The order you suggested makes no functional difference 
2. Encryption key should just be deleted by default
