### ISSUE TITLE
self report required for rewards but missing in command line version

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#38]
Driveshare-gui is not running on every system. Some users are using dataserv-client command line version. They will have to switch to node-storj command line? The self report (https://github.com/Storj/driveshare-gui/issues/193) is required for rewards.

Self report must be implemented in node-storj or command line users are unable to get rewards.

**Comment by gordonwritescode** [comment]
Yes, the node-storj CLI will be broken out into a driveshare-cli equivalent (farmer-cli). Working on it this week.
