### ISSUE TITLE
cause bridge to error instead of invalid email

### ISSUE THREAD

**Issue by computeronix** [Storj/core#381]
Can cause the bridge to issue error [minor security hole] if you do the following (overflow the variable)

storj register

for email enter
abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123@abc.com

password: b

 [Mon Aug 29 2016 22:31:02 GMT-0400 (Eastern Daylight Time)] [error]  WiredTigerIndex::insert: key too large to index, f
ailing  1100 { : "abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123
abc123abc123abc123abc123abc123abc123abc123abc123..." }

**Comment by littleskunk** [comment]
This looks like a bridge issue to me. Can you please repeat the test with --debug flag? This should print out the http request and Response. Maybe the bridge is sending an error already but storj cli ignores the error message.

**Comment by bookchin** [comment]
Please open in bridge

**Comment by computeronix** [comment]
https://github.com/Storj/bridge/issues/204

done
