### ISSUE TITLE
unlimited size or null size buckets

### ISSUE THREAD

**Issue by computeronix** [Storj/core#383]
run the command 
`
storj add-bucket "Name" 999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999 99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
`

it then shows

 [Tue Aug 30 2016 00:07:58 GMT-0400 (Eastern Daylight Time)] [info]   ID: 57c5069e43790f5527db306b, Name: Name, Storage:
 null, Transfer: null

**Comment by littleskunk** [comment]
Please repeat the test with --debug. That should print out the bridge comunication.

**Comment by bookchin** [comment]
Please open in bridge

**Comment by computeronix** [comment]
https://github.com/Storj/bridge/issues/206

done
