### ISSUE TITLE
Storj CLI upload-file --recursiv including subfolders

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#385]
As farmer I would like to have a --recursiv flag for `storj upload-file`. That will allow me to upload all files including subfolders. Without --recursiv flag I would like to upload only the files in that directory exclusiv subfolders.

**Comment by aleitner** [comment]
We are using glob patterns for uploading files so you can use /path/* to upload all files within a folder, and /path/**/* to upload all files within a folder recursively

**Comment by utdrmac** [comment]
This syntax doesn't work on macOS Sierra

`[drmac@othala ~]$ storj upload-file XXXX426d0ab9f8daa42 /Applications/iMovie.app/**/*`

This only uploaded 3 files inside the immediate sub-directory. There are many more files:

```
[drmac@othala ~]$ find /Applications/iMovie.app/ -type f | wc -l
   37490
[drmac@othala ~]$ bash --version
bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.

Storjcli: 4.0.0 | Core: 6.0.1
```
