### ISSUE TITLE
redundancy numbers below 1

### ISSUE THREAD

**Issue by computeronix** [Storj/core#390]
### Package Versions

```
3.1.0
```
```
v4.5.0
```

### Expected Behavior

```
Error out when wanting redundancy below 1
```

### Actual Behavior

```
Allows redundancy below 1
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. storj -r 0.01 upload-file 57c3a9f281e21cfd4f3d973f C:\bginfo\bg.jpg
2. storj -r 0 supload-file 57c3a9f281e21cfd4f3d973f C:\bginfo\bg.jpg

Logs

C:\Windows\system32>storj -r 0.01 upload-file 57c3a9f281e21cfd4f3d973f C:\bginfo\bg.jpg
 [Tue Aug 30 2016 15:23:26 GMT-0400 (Eastern Daylight Time)] [info]   1 file(s) to upload.
 [...]  > Enter your passphrase to unlock your keyring  >  *

 [Tue Aug 30 2016 15:23:28 GMT-0400 (Eastern Daylight Time)] [info]   Generating encryption key...
 [Tue Aug 30 2016 15:23:28 GMT-0400 (Eastern Daylight Time)] [info]   Encrypting file "C:/bginfo/bg.jpg"
 [Tue Aug 30 2016 15:23:28 GMT-0400 (Eastern Daylight Time)] [info]   [ bg.jpg ] Encryption complete!
 [Tue Aug 30 2016 15:23:28 GMT-0400 (Eastern Daylight Time)] [info]   [ bg.jpg ] Creating storage token...
 [Tue Aug 30 2016 15:23:29 GMT-0400 (Eastern Daylight Time)] [info]   [ bg.jpg ] Storing file, hang tight!
 [Tue Aug 30 2016 15:23:29 GMT-0400 (Eastern Daylight Time)] [info]   Trying to upload shard C:\Users\STORJ_~1\AppD
ata\Local\Temp\9d66d0a09d77 index 0
 [Tue Aug 30 2016 15:23:29 GMT-0400 (Eastern Daylight Time)] [info]   Hash for this shard is: ee8dfbe1c66ec28d5f897
e872afe8c63f2338137
 [Tue Aug 30 2016 15:23:29 GMT-0400 (Eastern Daylight Time)] [info]   Audit generation for shard done.
 [Tue Aug 30 2016 15:23:29 GMT-0400 (Eastern Daylight Time)] [info]   Waiting on a storage offer from the network..
.
 [Tue Aug 30 2016 15:23:29 GMT-0400 (Eastern Daylight Time)] [info]   Querying bridge for contract for ee8dfbe1c66e
c28d5f897e872afe8c63f2338137 (retry: 0)
 [Tue Aug 30 2016 15:23:30 GMT-0400 (Eastern Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0"
,"address":"storj05.graymines.net","port":4500,"nodeID":"ff13c0df527373af6934e342f090f83920514e09","lastSeen":14725
85010500}
 [Tue Aug 30 2016 15:23:30 GMT-0400 (Eastern Daylight Time)] [info]   Data channel opened, transferring shard...
 [Tue Aug 30 2016 15:23:31 GMT-0400 (Eastern Daylight Time)] [info]   Shard transfer completed! 0 remaining...
 [Tue Aug 30 2016 15:23:31 GMT-0400 (Eastern Daylight Time)] [info]   Transfer finished, creating entry...
 [Tue Aug 30 2016 15:23:31 GMT-0400 (Eastern Daylight Time)] [info]   [ bg.jpg ] Cleaning up...
 [Tue Aug 30 2016 15:23:31 GMT-0400 (Eastern Daylight Time)] [info]   [ bg.jpg ] Finished cleaning!
 [Tue Aug 30 2016 15:23:31 GMT-0400 (Eastern Daylight Time)] [info]   [ bg.jpg ] Encryption key saved to keyring.
 [Tue Aug 30 2016 15:23:31 GMT-0400 (Eastern Daylight Time)] [info]   [ bg.jpg ] File successfully stored in bucket
.
 [Tue Aug 30 2016 15:23:31 GMT-0400 (Eastern Daylight Time)] [info]   Name: bg.jpg, Type: image/jpeg, Size: 43650 b
ytes, ID: 57c5dd34f0ea649f5e611f9e
 [Tue Aug 30 2016 15:23:31 GMT-0400 (Eastern Daylight Time)] [info]   Establishing 0.01 mirrors per shard for redun
dancy
 [Tue Aug 30 2016 15:23:31 GMT-0400 (Eastern Daylight Time)] [info]   This can take a while, so grab a cocktail...
 [Tue Aug 30 2016 15:24:03 GMT-0400 (Eastern Daylight Time)] [info]   Shard ee8dfbe1c66ec28d5f897e872afe8c63f233813
7 mirrored by 0 nodes

C:\Windows\system32>storj -r 0 upload-file 57c3a9f281e21cfd4f3d973f C:\bginfo\bg.jpg
 [Tue Aug 30 2016 15:25:44 GMT-0400 (Eastern Daylight Time)] [info]   1 file(s) to upload.
 [...]  > Enter your passphrase to unlock your keyring  >  *

 [Tue Aug 30 2016 15:25:46 GMT-0400 (Eastern Daylight Time)] [info]   Generating encryption key...
 [Tue Aug 30 2016 15:25:46 GMT-0400 (Eastern Daylight Time)] [info]   Encrypting file "C:/bginfo/bg.jpg"
 [Tue Aug 30 2016 15:25:46 GMT-0400 (Eastern Daylight Time)] [info]   [ bg.jpg ] Encryption complete!
 [Tue Aug 30 2016 15:25:46 GMT-0400 (Eastern Daylight Time)] [info]   [ bg.jpg ] Creating storage token...
 [Tue Aug 30 2016 15:25:46 GMT-0400 (Eastern Daylight Time)] [info]   [ bg.jpg ] Storing file, hang tight!
 [Tue Aug 30 2016 15:25:47 GMT-0400 (Eastern Daylight Time)] [info]   Trying to upload shard C:\Users\STORJ_~1\AppD
ata\Local\Temp\5d5bf0a95b2b index 0
 [Tue Aug 30 2016 15:25:47 GMT-0400 (Eastern Daylight Time)] [info]   Hash for this shard is: 37dc0c79baf9c10ba88f2
a22a39a702a6a13c533
 [Tue Aug 30 2016 15:25:47 GMT-0400 (Eastern Daylight Time)] [info]   Audit generation for shard done.
 [Tue Aug 30 2016 15:25:47 GMT-0400 (Eastern Daylight Time)] [info]   Waiting on a storage offer from the network..
.
 [Tue Aug 30 2016 15:25:47 GMT-0400 (Eastern Daylight Time)] [info]   Querying bridge for contract for 37dc0c79baf9
c10ba88f2a22a39a702a6a13c533 (retry: 0)
 [Tue Aug 30 2016 15:25:48 GMT-0400 (Eastern Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0"
,"address":"newton1vpn.idiil.org","port":4600,"nodeID":"33815bb05cb87efdcdda3acfb8fe5fce829d90f4","lastSeen":147258
5148113}
 [Tue Aug 30 2016 15:25:48 GMT-0400 (Eastern Daylight Time)] [info]   Data channel opened, transferring shard...
 [Tue Aug 30 2016 15:25:48 GMT-0400 (Eastern Daylight Time)] [info]   Shard transfer completed! 0 remaining...
 [Tue Aug 30 2016 15:25:48 GMT-0400 (Eastern Daylight Time)] [info]   Transfer finished, creating entry...
 [Tue Aug 30 2016 15:25:48 GMT-0400 (Eastern Daylight Time)] [info]   [ bg.jpg ] Cleaning up...
 [Tue Aug 30 2016 15:25:48 GMT-0400 (Eastern Daylight Time)] [info]   [ bg.jpg ] Finished cleaning!
 [Tue Aug 30 2016 15:25:48 GMT-0400 (Eastern Daylight Time)] [info]   [ bg.jpg ] Encryption key saved to keyring.
 [Tue Aug 30 2016 15:25:48 GMT-0400 (Eastern Daylight Time)] [info]   [ bg.jpg ] File successfully stored in bucket
.
 [Tue Aug 30 2016 15:25:48 GMT-0400 (Eastern Daylight Time)] [info]   Name: bg.jpg, Type: image/jpeg, Size: 43650 b
ytes, ID: 57c5ddbd43790f5527dc82b4
 [Tue Aug 30 2016 15:25:48 GMT-0400 (Eastern Daylight Time)] [info]   Establishing 0 mirrors per shard for redundan
cy
 [Tue Aug 30 2016 15:25:48 GMT-0400 (Eastern Daylight Time)] [info]   This can take a while, so grab a cocktail...
 [Tue Aug 30 2016 15:26:04 GMT-0400 (Eastern Daylight Time)] [info]   Shard 37dc0c79baf9c10ba88f2a22a39a702a6a13c53
3 mirrored by 0 nodes

**Comment by computeronix** [comment]
Is there an intent to allow 0 redundancy?

**Comment by NicoNet** [comment]
And what about negative redundancy?
``` storj -r -1 -k a upload-file $newBucket abc ```

**Comment by NicoNet** [comment]
0 redundancy does make sense.  One might want to override a different setting in the config file.

**Comment by computeronix** [comment]
Can't have negative because the app thinks its a parameter and not a number  (i tried multiple ways :) )

**Comment by computeronix** [comment]
spoke with shawn and will provide a code change once i get some time
