### ISSUE TITLE
Feature Request: Check bucket first then upload

### ISSUE THREAD

**Issue by computeronix** [Storj/core#394]
### Package Versions

```
3.1.0
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

```
Check for a valid bucket before doing a bunch of wasted work :)
```

### Actual Behavior

```
Program begins to work and attempts to post in invalid bucket and then errors out
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. run this command storj upload-file \ C:\test\1GB.zip

Log

PS C:\Windows\system32> storj upload-file \ C:\test\1GB.zip
 [Tue Aug 30 2016 16:30:13 GMT-0400 (Eastern Daylight Time)] [info]   1 file(s) to upload.
 [...]  > Enter your passphrase to unlock your keyring  >  *

 [Tue Aug 30 2016 16:30:50 GMT-0400 (Eastern Daylight Time)] [info]   Generating encryption key...
 [Tue Aug 30 2016 16:30:50 GMT-0400 (Eastern Daylight Time)] [info]   Encrypting file "C:/test/1GB.zip"
 [Tue Aug 30 2016 16:31:32 GMT-0400 (Eastern Daylight Time)] [info]   [ 1GB.zip ] Encryption complete!
 [Tue Aug 30 2016 16:31:32 GMT-0400 (Eastern Daylight Time)] [info]   [ 1GB.zip ] Creating storage token...
 [Tue Aug 30 2016 16:31:33 GMT-0400 (Eastern Daylight Time)]1GB.zip,Cannot POST /buckets///tokens

 [Tue Aug 30 2016 16:31:33 GMT-0400 (Eastern Daylight Time)] [info]   [ 1GB.zip ] Cleaning up...
 [Tue Aug 30 2016 16:31:39 GMT-0400 (Eastern Daylight Time)] [info]   [ 1GB.zip ] Finished cleaning!

Story:

A user would expect that all potential errors would be checked before initiating a costly upload.

By adjusting the order of this check this would prevent the user from wasting resources.

**Comment by super3** [comment]
Earlier would be better, but I think it errors out an acceptable time for a reference CLI.
