### ISSUE TITLE
Shard ....... mirrored by 0 nodes

### ISSUE THREAD

**Issue by lakewik** [Storj/core#395]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
├── storj@3.1.0
├─┬ storj-bridge@0.10.0
│ └── storj@2.0.5
└─┬ storjshare-cli@6.0.1
  └── storj@3.0.4
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior

The program should display the error and/or continue an attempt to create a mirror. I discovered that the error occurs for files larger than 8 MB. 

### Actual Behavior

The program displays information that file copied on 0 nodes.
When i try with --debug option, i get this response from server:

`[debug]  Body: [{"hash":"xyzxyzxyz","mirrors":[]}]`

Excuted upload file command with -r 5:
```

 [Wed Aug 31 2016 14:12:18 GMT+0200 (Środkowoeuropejski czas letni)] [info]   Transfer finished, creating entry...
 [Wed Aug 31 2016 14:12:18 GMT+0200 (Środkowoeuropejski czas letni)] [info]   [ pibackup.zip ] Cleaning up...
 [Wed Aug 31 2016 14:12:18 GMT+0200 (Środkowoeuropejski czas letni)] [info]   [ pibackup.zip ] Finished cleaning!
 [Wed Aug 31 2016 14:12:18 GMT+0200 (Środkowoeuropejski czas letni)] [info]   [ pibackup.zip ] Encryption key saved to keyring.
 [Wed Aug 31 2016 14:12:18 GMT+0200 (Środkowoeuropejski czas letni)] [info]   [ pibackup.zip ] File successfully stored in bucket.
 [Wed Aug 31 2016 14:12:18 GMT+0200 (Środkowoeuropejski czas letni)] [info]   Name: pibackup.zip, Type: application/zip, Size: 8982265 bytes, ID: 57c6c9a6216fd4f11fc7482e
 [Wed Aug 31 2016 14:12:18 GMT+0200 (Środkowoeuropejski czas letni)] [info]   Establishing 5 mirrors per shard for redundancy
 [Wed Aug 31 2016 14:12:18 GMT+0200 (Środkowoeuropejski czas letni)] [info]   This can take a while, so grab a cocktail...
 [Wed Aug 31 2016 14:12:49 GMT+0200 (Środkowoeuropejski czas letni)] [info]   Shard 4f3bed1794dfeabe7e3050e6e46159e5d08d9e15 mirrored by 0 nodes
 [Wed Aug 31 2016 14:12:49 GMT+0200 (Środkowoeuropejski czas letni)] [info]   Shard cb6963d1b62c5646ea325e6e74da804472f985c7 mirrored by 0 nodes
```
When I try to manually create mirror with `storj create-mirrors [bucketid] [fileid] -r 3  ,` occur same bug.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload file larger than 8 MB with option -r
2. The program display "mirrored by 0 nodes" info

**Comment by super3** [comment]
@lakewik So this is caused by an architecture issue in the way we do mirrors. It will work with really small files, but with larger files it will timeout. We are aware of this issue, and will fix in the next update or two.

**Comment by bookchin** [comment]
https://github.com/Storj/bridge/issues/195
https://github.com/Storj/bridge/issues/219
