### ISSUE TITLE
core 3.1.1 upload issues

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#398]
### Package Versions

core --version: 3.1.1

node --version: 4.5.0

### Expected Behavior

clean exit

### Actual Behavior

C:\Users\meije>storj -k meije0612 upload-file 57b04b21dd072de41858a79f H:\AnalogueModels\GS_B45\Top_View\*

 [Tue Sep 06 2016 23:00:59 GMT+0200 (W. Europe Daylight Time)] [info]   48 file(s) to upload.
 [Tue Sep 06 2016 23:00:59 GMT+0200 (W. Europe Daylight Time)] [info]   Generating encryption key...
 [Tue Sep 06 2016 23:00:59 GMT+0200 (W. Europe Daylight Time)] [info]   Encrypting file "H:/AnalogueModels/GS_B45/Top_View/brittle 45.JPG"
 [Tue Sep 06 2016 23:00:59 GMT+0200 (W. Europe Daylight Time)] [info]   [ brittle 45.JPG ] Encryption complete!
 [Tue Sep 06 2016 23:00:59 GMT+0200 (W. Europe Daylight Time)] [info]   [ brittle 45.JPG ] Creating storage token...
 [Tue Sep 06 2016 23:02:59 GMT+0200 (W. Europe Daylight Time)]brittle 45.JPG,<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>

 [Tue Sep 06 2016 23:02:59 GMT+0200 (W. Europe Daylight Time)] [info]   [ brittle 45.JPG ] Cleaning up...
 [Tue Sep 06 2016 23:02:59 GMT+0200 (W. Europe Daylight Time)] [info]   [ brittle 45.JPG ] Finished cleaning!

C:\Users\meije>

**Comment by MeijeSibbel** [comment]
[Tue Sep 06 2016 22:57:22 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Tue Sep 06 2016 22:57:23 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 3 remaining...
 [Tue Sep 06 2016 22:57:24 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"136.62.72.151","port":36502,"nodeID":"6034299a587ae04782dce3eaf493161292919288","lastSeen":1473195439968}
 [Tue Sep 06 2016 22:57:24 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Tue Sep 06 2016 22:57:38 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 2 remaining...
 [Tue Sep 06 2016 22:58:07 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 465204b1c2600701b9eefdfacb9d68ac1104a4de (retry: 12)
 [Tue Sep 06 2016 22:58:22 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 465204b1c2600701b9eefdfacb9d68ac1104a4de (retry: 13)
 [Tue Sep 06 2016 22:58:38 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 465204b1c2600701b9eefdfacb9d68ac1104a4de (retry: 14)
 [Tue Sep 06 2016 23:00:37 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 465204b1c2600701b9eefdfacb9d68ac1104a4de (retry: 15)
 [Tue Sep 06 2016 23:00:52 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 465204b1c2600701b9eefdfacb9d68ac1104a4de (retry: 16)
 [Tue Sep 06 2016 23:02:52 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 465204b1c2600701b9eefdfacb9d68ac1104a4de (retry: 17)
 [Tue Sep 06 2016 23:03:09 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 465204b1c2600701b9eefdfacb9d68ac1104a4de (retry: 18)
 [Tue Sep 06 2016 23:03:32 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 465204b1c2600701b9eefdfacb9d68ac1104a4de (retry: 19)
 [Tue Sep 06 2016 23:04:07 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 465204b1c2600701b9eefdfacb9d68ac1104a4de (retry: 20)
 [Tue Sep 06 2016 23:06:07 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 465204b1c2600701b9eefdfacb9d68ac1104a4de (retry: 21)
 [Tue Sep 06 2016 23:06:22 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 465204b1c2600701b9eefdfacb9d68ac1104a4de (retry: 22)
 [Tue Sep 06 2016 23:06:38 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 465204b1c2600701b9eefdfacb9d68ac1104a4de (retry: 23)
 [Tue Sep 06 2016 23:06:53 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 465204b1c2600701b9eefdfacb9d68ac1104a4de (retry: 24)
 [Tue Sep 06 2016 23:07:09 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
 [Tue Sep 06 2016 23:07:09 GMT+0200 (W. Europe Daylight Time)] [warn]   [ Terminator.Genisys.mp4 ] Error occurred. Triggering cleanup...
 [Tue Sep 06 2016 23:07:09 GMT+0200 (W. Europe Daylight Time)] [info]   [ Terminator.Genisys.mp4 ] Cleaning up...
 [Tue Sep 06 2016 23:07:09 GMT+0200 (W. Europe Daylight Time)] [info]   [ Terminator.Genisys.mp4 ] Finished cleaning!
 [Tue Sep 06 2016 23:07:09 GMT+0200 (W. Europe Daylight Time)] [error]  [ undefined ] A file has failed to upload: Error: No storage offers were received

C:\Users\meije>

**Comment by MeijeSibbel** [comment]
command: C:\Users\meije>storj -k meije0612 -r 10 -c 200 upload-file 57b05629905cfece30b430f0 H:\Meije\Movies\The.Young.Victoria.2009.720p.Bluray.x264.anoXmous.mp4

[Tue Sep 06 2016 23:11:38 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Tue Sep 06 2016 23:11:47 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 1 remaining...
 [Tue Sep 06 2016 23:11:54 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 9b2d7581492d88722c04c009a484a060c48031a7 (retry: 9)
 [Tue Sep 06 2016 23:11:55 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"24.24.200.97","port":60261,"nodeID":"98825a4650a87ed63322d696f865fa24d7dcaa9b","lastSeen":1473196314822}
 [Tue Sep 06 2016 23:11:56 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Tue Sep 06 2016 23:12:01 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 0 remaining...
 [Tue Sep 06 2016 23:12:01 GMT+0200 (W. Europe Daylight Time)] [info]   Transfer finished, creating entry...
 [Tue Sep 06 2016 23:12:01 GMT+0200 (W. Europe Daylight Time)] [info]   [ The.Young.Victoria.2009.720p.Bluray.x264.anoXmous.mp4 ] Cleaning up...
 [Tue Sep 06 2016 23:12:01 GMT+0200 (W. Europe Daylight Time)] [info]   [ The.Young.Victoria.2009.720p.Bluray.x264.anoXmous.mp4 ] Finished cleaning!
 [Tue Sep 06 2016 23:12:01 GMT+0200 (W. Europe Daylight Time)] [info]   [ The.Young.Victoria.2009.720p.Bluray.x264.anoXmous.mp4 ] Encryption key saved to keyring.
 [Tue Sep 06 2016 23:12:01 GMT+0200 (W. Europe Daylight Time)] [info]   [ The.Young.Victoria.2009.720p.Bluray.x264.anoXmous.mp4 ] File successfully stored in bucket.
 [Tue Sep 06 2016 23:12:01 GMT+0200 (W. Europe Daylight Time)] [info]   Name: The.Young.Victoria.2009.720p.Bluray.x264.anoXmous.mp4, Type: video/mp4, Size: 784025085 bytes, ID: 57cf31215f1f579c7b3838e8
 [Tue Sep 06 2016 23:12:01 GMT+0200 (W. Europe Daylight Time)] [info]   Establishing 10 mirrors per shard for redundancy
 [Tue Sep 06 2016 23:12:01 GMT+0200 (W. Europe Daylight Time)] [info]   This can take a while, so grab a cocktail...
 [Tue Sep 06 2016 23:14:01 GMT+0200 (W. Europe Daylight Time)] [error]  <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>


C:\Users\meije>

**Comment by bookchin** [comment]
All of these are related to the bridge. Can you please open the issue there?
