### ISSUE TITLE
[error] <html>

### ISSUE THREAD

**Issue by 1credit** [Storj/core#405]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj:  3.1.2
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior

Upload to finish without error.

```

```

### Actual Behavior

 [Wed Sep 07 2016 19:13:43 GMT-0500 (CDT)] [info]   Data channel opened, transferring shard...
 [Wed Sep 07 2016 19:13:51 GMT-0500 (CDT)] [info]   Shard transfer completed! 1 remaining...
 [Wed Sep 07 2016 19:16:55 GMT-0500 (CDT)] [info]   Shard transfer completed! 0 remaining...
 [Wed Sep 07 2016 19:16:55 GMT-0500 (CDT)] [info]   Transfer finished, creating entry...
 [Wed Sep 07 2016 19:16:56 GMT-0500 (CDT)] [info]   [ mail.tar ] Cleaning up...
 [Wed Sep 07 2016 19:16:56 GMT-0500 (CDT)] [info]   [ mail.tar ] Finished cleaning!
 [Wed Sep 07 2016 19:16:56 GMT-0500 (CDT)] [info]   [ mail.tar ] Encryption key saved to keyring.
 [Wed Sep 07 2016 19:16:56 GMT-0500 (CDT)] [info]   [ mail.tar ] File successfully stored in bucket.
 [Wed Sep 07 2016 19:16:56 GMT-0500 (CDT)] [info]   Name: mail.tar, Type: application/x-tar, Size: 979382272 bytes, ID: 57d0adf88d8000733b7f61b9
 [Wed Sep 07 2016 19:16:56 GMT-0500 (CDT)] [info]   Establishing 12 mirrors per shard for redundancy
 [Wed Sep 07 2016 19:16:56 GMT-0500 (CDT)] [info]   This can take a while, so grab a cocktail...
 [Wed Sep 07 2016 19:18:33 GMT-0500 (CDT)] [error]  <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>

FYI:  fspoe ~ # ./list-files
 [Wed Sep 07 2016 19:24:45 GMT-0500 (CDT)] [info]   Name: mail.tar, Type: application/x-tar, Size: 979382272 bytes, ID: 57d0adf88d8000733b7f61b9

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Tried uploading a ~1GB file, -c 3 -r 12
2. ...
3. ...

**Comment by bookchin** [comment]
Duplicate https://github.com/Storj/bridge/issues/214
