### ISSUE TITLE
No storage offers were received

### ISSUE THREAD

**Issue by 1credit** [Storj/core#406]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
Storj 3.1.2
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior

Network would not fail with lack of storage offers given the amount of unused space on the net.

```

```

### Actual Behavior
dd5dcf0322450c9620077e33c2f3b5095e2f5 (retry: 2)
 [Wed Sep 07 2016 21:42:31 GMT-0500 (CDT)] [info]   Querying bridge for contract for 50f      3f4d77ff3fcb32c0dc59f7dcf048563d07112 (retry: 18)
 [Wed Sep 07 2016 21:43:00 GMT-0500 (CDT)] [info]   Querying bridge for contract for 2df      dd5dcf0322450c9620077e33c2f3b5095e2f5 (retry: 3)
 [Wed Sep 07 2016 21:43:03 GMT-0500 (CDT)] [info]   Contract negotiated with: {"protocol      ":"0.8.1","address":"jsia.ddns.net","port":23550,"nodeID":"29dff6268e24afe024ddcae4e574f      41d4af23edb","lastSeen":1473302582091}
 [Wed Sep 07 2016 21:43:03 GMT-0500 (CDT)] [info]   Data channel opened, transferring sh      ard...
 [Wed Sep 07 2016 21:43:17 GMT-0500 (CDT)] [info]   Querying bridge for contract for 50f      3f4d77ff3fcb32c0dc59f7dcf048563d07112 (retry: 19)
 [Wed Sep 07 2016 21:44:01 GMT-0500 (CDT)] [info]   Shard transfer completed! 9 remainin      g...
 [Wed Sep 07 2016 21:44:01 GMT-0500 (CDT)] [info]   Trying to upload shard /tmp/00fe6600      d61c index 32
 [Wed Sep 07 2016 21:44:01 GMT-0500 (CDT)] [info]   Hash for this shard is: 1c534310ea34      74b6e8226d842871a61941018425
 [Wed Sep 07 2016 21:44:03 GMT-0500 (CDT)] [info]   Audit generation for shard done.
 [Wed Sep 07 2016 21:44:03 GMT-0500 (CDT)] [info]   Waiting on a storage offer from the       network...
 [Wed Sep 07 2016 21:44:03 GMT-0500 (CDT)] [info]   Querying bridge for contract for 1c5      34310ea3474b6e8226d842871a61941018425 (retry: 0)
 [Wed Sep 07 2016 21:44:10 GMT-0500 (CDT)] [info]   Querying bridge for contract for 50f      3f4d77ff3fcb32c0dc59f7dcf048563d07112 (retry: 20)
 [Wed Sep 07 2016 21:44:19 GMT-0500 (CDT)] [info]   Querying bridge for contract for 1c5      34310ea3474b6e8226d842871a61941018425 (retry: 1)
 [Wed Sep 07 2016 21:44:20 GMT-0500 (CDT)] [info]   Contract negotiated with: {"protocol      ":"0.8.0","address":"83.248.66.115","port":4000,"nodeID":"175f699bbf05bcc0a5e4a1674096ac      f836d14c35","lastSeen":1473302660059}
 [Wed Sep 07 2016 21:44:21 GMT-0500 (CDT)] [info]   Data channel opened, transferring sh      ard...
 [Wed Sep 07 2016 21:44:27 GMT-0500 (CDT)] [info]   Querying bridge for contract for 50f      3f4d77ff3fcb32c0dc59f7dcf048563d07112 (retry: 21)
 [Wed Sep 07 2016 21:44:43 GMT-0500 (CDT)] [info]   Querying bridge for contract for 50f      3f4d77ff3fcb32c0dc59f7dcf048563d07112 (retry: 22)
 [Wed Sep 07 2016 21:45:08 GMT-0500 (CDT)] [info]   Shard transfer completed! 8 remainin      g...
 [Wed Sep 07 2016 21:45:08 GMT-0500 (CDT)] [info]   Trying to upload shard /tmp/dcfb4727      a182 index 33
 [Wed Sep 07 2016 21:45:08 GMT-0500 (CDT)] [info]   Hash for this shard is: ec550b8bd630      9345d6b3abb611a16b09b1fa902e
 [Wed Sep 07 2016 21:45:11 GMT-0500 (CDT)] [info]   Audit generation for shard done.
 [Wed Sep 07 2016 21:45:11 GMT-0500 (CDT)] [info]   Waiting on a storage offer from the       network...
 [Wed Sep 07 2016 21:45:11 GMT-0500 (CDT)] [info]   Querying bridge for contract for ec5      50b8bd6309345d6b3abb611a16b09b1fa902e (retry: 0)
 [Wed Sep 07 2016 21:45:21 GMT-0500 (CDT)] [info]   Querying bridge for contract for 50f      3f4d77ff3fcb32c0dc59f7dcf048563d07112 (retry: 23)
 [Wed Sep 07 2016 21:45:26 GMT-0500 (CDT)] [info]   Querying bridge for contract for ec5      50b8bd6309345d6b3abb611a16b09b1fa902e (retry: 1)
 [Wed Sep 07 2016 21:45:37 GMT-0500 (CDT)] [info]   Querying bridge for contract for 50f      3f4d77ff3fcb32c0dc59f7dcf048563d07112 (retry: 24)
 [Wed Sep 07 2016 21:45:41 GMT-0500 (CDT)] [info]   Querying bridge for contract for ec5      50b8bd6309345d6b3abb611a16b09b1fa902e (retry: 2)
 [Wed Sep 07 2016 21:45:53 GMT-0500 (CDT)] [warn]   Failed to upload shard...
 [Wed Sep 07 2016 21:45:53 GMT-0500 (CDT)] [warn]   [ fspoe.tar ] Error occurred. Trigge      ring cleanup...
 [Wed Sep 07 2016 21:45:53 GMT-0500 (CDT)] [info]   [ fspoe.tar ] Cleaning up...
 [Wed Sep 07 2016 21:45:54 GMT-0500 (CDT)] [info]   [ fspoe.tar ] Finished cleaning!
 [Wed Sep 07 2016 21:45:54 GMT-0500 (CDT)] [error]  [ undefined ] A file has failed to u      pload: Error: No storage offers were received

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by littleskunk** [comment]
This is the renter view of https://github.com/Storj/storjshare-cli/issues/122#issuecomment-241548518

The bridge would like to send the shard `50f3f4d77ff3fcb32c0dc59f7dcf048563d07112` to his own neighbors `593844dc7f0076a1aeda9a6b9788af17e67c1052`.

At the same time the bridge will relay contract PUBLISH messages of at least 13 other bridge server. Neighbors are unable to relay the messages and will timeout.

At the end one more issue for https://github.com/Storj/core/issues/221

**Comment by bookchin** [comment]
This issue is bridge side, please open there.

**Comment by 1credit** [comment]
Done.
