### ISSUE TITLE
Checking Wallet Address during initial start

### ISSUE THREAD

**Issue by computeronix** [Storj/core#412]
Not sure if the core does this but here is the scenario

Currently storj checks wether you have a valid wallet address or not during setup.  A user could potentially enter the key into the config directly and bypass this soft check.

A user may want the key checked upon starting of the initial client to ensure the key payment address is correct.  If it is incorrect error out -- or report error and continue running "free".

**Comment by super3** [comment]
This should be in storjshare-cli and/or storjshare-gui.

**Comment by computeronix** [comment]
Done   https://github.com/Storj/storjshare-cli/issues/171      https://github.com/Storj/storjshare-gui/issues/376
