### ISSUE TITLE
Working directory option

### ISSUE THREAD

**Issue by 1credit** [Storj/core#424]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj 3.1.2
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior

Option or environment variable needs to be available to set the working directory for uploading files.

```

```

### Actual Behavior

File encryption and other workfiles are stored in /tmp on Linux based system.  This is often small, fast, storage and is inappropriate when sending large files.  For example, 4-8GB of tmpfs space (ramdisk if you will) is commonly allocated on Linux systems for /tmp.  This suffices for virtually all regular system activity but is totally unsuitable when sending large, say 10+GB, storj files.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by aleitner** [comment]
STORJ_TEMP environment variable will be implemented with the next core release
