### ISSUE TITLE
[error]  undefined is an invalid Redundancy value (core 3.2.1 and core 3.2.2)

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#437]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core

core --version : 3.2.1
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

upload initiates 

### Command

```
storj -k meije0612 upload-file 57af3a1e8f266a7d4e391055 D:\50MB
```

### Actual Behavior

```
C:\Users\Dani Marion>storj -k meije0612 upload-file 57af3a1e8f266a7d4e391055 D:\50MB
 [Mon Sep 19 2016 18:56:09 GMT+0200 (W. Europe Daylight Time)] [error]  undefined is an invalid Redundancy value.

C:\Users\Dani Marion>


```

### Steps to Reproduce

Upload a file

**Comment by MeijeSibbel** [comment]
If -r is specified the error disappears.

**Comment by super3** [comment]
@MeijeSibbel Fixed already

**Comment by super3** [comment]
@MeijeSibbel https://github.com/Storj/core/releases/tag/v3.2.2

**Comment by MeijeSibbel** [comment]
Nope, error still persists.
