### ISSUE TITLE
storjshare-cli error during startup

### ISSUE THREAD

**Issue by Puychack** [Storj/core#443]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
/home/bigminer/.nvm/versions/node/v4.4.7/lib
└─┬ storjshare-cli@6.0.3
  └── storj@3.2.3

```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior

Shoud start without error

### Actual Behavior

Storjshare-cli errors at startup with the following message : 
TypeError: Cannot read property 'bitfield' of undefined
    at Function.BloomFilter.deserialize (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad-quasar/lib/bloomfilter.js:47:18)
    at Object.callback (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad-quasar/lib/quasar.js:362:32)
    at Transport.RPC._execPendingCallback (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/lib/rpc.js:331:17)
    at /home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/lib/rpc.js:235:12
    at /home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/lib/rpc.js:305:5
    at /home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:251:17
    at /home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:154:25
    at /home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:248:21
    at /home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:612:34
    at Transport.protocol (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/lib/hooks/protocol.js:21:14)
    at /home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:607:21
    at /home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:246:17
    at iterate (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:146:13)
    at /home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:157:25
    at /home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:248:21
    at /home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:612:34

pm2 automatically reboots storjshare-cli more than 40 times with the same error before everythings starts fine...

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. just start storjshare-cli

**Comment by bookchin** [comment]
Tracking here: https://github.com/kadtools/kad-quasar/issues/8#issuecomment-248335847

**Comment by deadgray** [comment]
Same here, but I just waited few minutes.
Started without error.
