### ISSUE TITLE
Bad gateway error for "list-files" after deletion of file's frame

### ISSUE THREAD

**Issue by virl** [Storj/core#450]
### Package Versions
```
/usr/local/lib
└── storj@3.2.3
```
```
v6.6.0
```

### Expected Behavior

Empty bucket.

### Actual Behavior

```
 [Fri Sep 23 2016 16:49:51 GMT+0300 (MSK)] [error]  <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>
```

### Steps to Reproduce

1. Create bucket.
2. Upload file to it.
3. ```storj list-frames```
4. ```storj remove-frame``` on file's frame.
5. ```storj list-files``` on bucket — receive error.

**Comment by bookchin** [comment]
This is a issue for https://github.com/Storj/bridge and it's already being tracked in several open issues there
