### ISSUE TITLE
File XXXX does not exist in bucket YYYY

### ISSUE THREAD

**Issue by Th3Van** [Storj/core#455]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@0.11.4 /root/bridge
`-- storj@3.2.3 
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
To download files from bucket.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
root@Server025:/tmp# storj list-files 5794e152c57ba12c670ba7e3 | grep "57e83439f4966c65d22fd88d" 
[Sun Sep 25 2016 22:38:43 GMT+0200 (CEST)] [info]   Name: Server025.storj.dk-000005-20160925203012238100178-85051074-e0d518ec7bdfed9ad602d54ce73730a3822be18879ad7d3de4fb8247669082cc, Type: application/octet-stream, Size: 101828290 bytes, ID: 57e83439f4966c65d22fd88d

root@Server025:/tmp# storj -k ( ͡⊙ ͜ʖ ͡⊙)﻿ download-file 5794e152c57ba12c670ba7e3 57e83439f4966c65d22fd88d /tmp/test.file001
 [Sun Sep 25 2016 22:39:35 GMT+0200 (CEST)] [info]   Name: Server025.storj.dk-000005-20160925203012238100178-85051074-e0d518ec7bdfed9ad602d54ce73730a3822be18879ad7d3de4fb8247669082cc, Type: application/octet-stream, Size: 101828290 bytes, ID: 57e83439f4966c65d22fd88d
 [Sun Sep 25 2016 22:39:35 GMT+0200 (CEST)] [info]   Creating retrieval token...
 [Sun Sep 25 2016 22:39:35 GMT+0200 (CEST)] [error]  file 57e83439f4966c65d22fd88d does not exist in bucket 5794e152c57ba12c670ba7e3
 [Sun Sep 25 2016 22:39:35 GMT+0200 (CEST)] [info]   Resolving 6 file pointers...
 [Sun Sep 25 2016 22:39:38 GMT+0200 (CEST)] [info]   Creating retrieval token...
 [Sun Sep 25 2016 22:39:38 GMT+0200 (CEST)] [info]   Resolving 6 file pointers...
 [Sun Sep 25 2016 22:39:40 GMT+0200 (CEST)] [info]   Downloading file slice from 5 channels.
 [Sun Sep 25 2016 22:39:40 GMT+0200 (CEST)] [info]   Creating retrieval token...
 [Sun Sep 25 2016 22:39:40 GMT+0200 (CEST)] [info]   Resolving 6 file pointers...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Did not receive data within max Time-To-First-Byte
    at null._onTimeout (/root/bridge/node_modules/storj/lib/data-channels/readable-stream.js:97:7)
    at Timer.listOnTimeout (timers.js:92:15)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Use Storj CLI to upload a file using a bridge server (api.storj.io / apipool001.storj.dk)
2. Verify the file using the "list-files" option
3. Try to download the file again using the "download-file" option

**Comment by frdwrd** [comment]
This is actually happening to a bunch of the async calls right now. There's a `async.forEach()` driving this, and for some reason some of the callbacks are getting called twice with different arguments, for no apparent reason. You see multiple `Creating retrieval tokens` and `Resolving X file pointers` because of this.

@phutchins had a partial fix merged to the CLI in a PR here: https://github.com/Storj/core-cli/pull/7
