### ISSUE TITLE
Support for custom object metadata (akin to S3)

### ISSUE THREAD

**Issue by haywirez** [Storj/core#459]
It could be useful to be able to store arbitrary, user-defined metadata with each file (or perhaps even a size-limited, encrypted JSON). This would prevent the need for additional lookups elsewhere (e.g. image captions, audio/video/document information). If implemented, there should also be a way to update an object's metadata separately. What do you think?

**Comment by super3** [comment]
@haywirez Best to put that feature suggestion here: https://wantoo.io/storj-product-feedback/

Personally I think that metadata should just be another object, and be handled by the application.

**Comment by super3** [comment]
@haywirez Also this feature request would probably belong in [bridge[(https://github.com/Storj/bridge), but I'd recommend just putting on on Wantoo for now.
