### ISSUE TITLE
Remove temporary encrypted files after upload task completes or fails.

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#464]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core

storj -> v4.0.0-rc.5 (hotfix)
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

Temporary files are removed after upload task exits.

### Actual Behavior

Temporary files are never deleted. 

### Steps to Reproduce

Upload any file

**Comment by aleitner** [comment]
I think this varies depending on where it fails. Can you provide us with at least one spot where an error occured and this happened?

**Comment by MeijeSibbel** [comment]
@aleitner, this occurs mainly after a bad gateway error.
