### ISSUE TITLE
Reuse HTTP Connections

### ISSUE THREAD

**Issue by yuilleb** [Storj/core#484]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
/usr/local/lib
âââ storj@3.2.3
```

Replace the values below using the output from `node --version`.

```
v4.6.0
```

### Expected Behavior

HTTP/1.0 by default suffered serious performance issues because it opened a new TCP connection for every request. HTTP/1.1 improved 1.0 significantly by recommending connections remain open for some period of time whilst there is a chance the connection might be reused (persistent connections). Nodes in the Storj network appear to be very likely to have continued communication with each other and would greatly benefit from reusing TCP connections.

This issue might be related to [storjshare-cli issue 122](https://github.com/Storj/storjshare-cli/issues/122).

### Actual Behavior

Every Storj HTTP/1.1 request and response has a `Connection: close` header which signals to the receiving side to close the connection. This has been shown to create simultaneous established connections along with a long list of sockets sitting in the TIME_WAIT state.

I've noticed my NAT translation tables are now putting considerable load on my router since running storjshare. I have a 2800 series Cisco router which is quite a level above the average home user. The number of new simultaneous connections Storjshare creates is likely to destroy the average home user's network. BitTorrent, which has been known to be rather harsh on a network, has never utilized as much load on my router as Storj has. I think this is an important issue to get resolved for mass adoption.

Here's an example of multiple outbound connections to the same node on port 4600 as well as multiple inbound connection from that same remote node on port 19062:
```
# netstat -pna | grep 66.128.118.34
tcp        0      0 10.33.1.6:57439         66.128.118.34:4600      TIME_WAIT   -
tcp        0      0 10.33.1.6:57347         66.128.118.34:4600      TIME_WAIT   -
tcp        0      0 10.33.1.6:57444         66.128.118.34:4600      ESTABLISHED 16960/node
tcp        0      0 10.33.1.6:57428         66.128.118.34:4600      ESTABLISHED 16960/node
tcp        0      0 10.33.1.6:57372         66.128.118.34:4600      TIME_WAIT   -
tcp        0      0 10.33.1.6:57435         66.128.118.34:4600      TIME_WAIT   -
tcp        0      0 10.33.1.6:57450         66.128.118.34:4600      ESTABLISHED 16960/node
tcp        0      0 10.33.1.6:57388         66.128.118.34:4600      TIME_WAIT   -
tcp        0      0 10.33.1.6:57397         66.128.118.34:4600      TIME_WAIT   -
tcp        0      0 10.33.1.6:57384         66.128.118.34:4600      TIME_WAIT   -
tcp6       0      0 10.33.1.6:19062         66.128.118.34:48318     TIME_WAIT   -
tcp6       0      0 10.33.1.6:19062         66.128.118.34:48142     TIME_WAIT   -
tcp6       0      0 10.33.1.6:19062         66.128.118.34:48204     TIME_WAIT   -
tcp6       0      0 10.33.1.6:19062         66.128.118.34:48332     ESTABLISHED 16960/node
tcp6       0      0 10.33.1.6:19062         66.128.118.34:48314     TIME_WAIT   -
tcp6       0      0 10.33.1.6:19062         66.128.118.34:48320     TIME_WAIT   -
tcp6       0      0 10.33.1.6:19062         66.128.118.34:48074     TIME_WAIT   -
tcp6       0      0 10.33.1.6:19062         66.128.118.34:48206     TIME_WAIT   -
tcp6       0      0 10.33.1.6:19062         66.128.118.34:48352     ESTABLISHED 16960/node
tcp6       0      0 10.33.1.6:19062         66.128.118.34:48292     TIME_WAIT   -
tcp6       0      0 10.33.1.6:19062         66.128.118.34:48280     TIME_WAIT   -
tcp6       0      0 10.33.1.6:19062         66.128.118.34:48112     TIME_WAIT   -
```

### Steps to Reproduce

Run `storjshare-cli`

### Comments

I believe this issue is might be related to the kad library so I've opened an [issue regarding this there as well](https://github.com/kadtools/kad/issues/71). I could be wrong though.

I suggest fixing this issue by [creating your own http.Agent and setting keepAlive to true in the options](http://stackoverflow.com/a/38614839/3453885).

**Comment by littleskunk** [comment]
p2p connection beween farmer is here: https://github.com/kadtools/kad/blob/master/lib/transports/http.js

The communication beween core-cli and bridge is here: https://github.com/Storj/core/blob/a846b4fd8380a690cf2aa92669b811cfe2c45716/lib/bridge-client/index.js#L706
https://github.com/Storj/core/blob/a846b4fd8380a690cf2aa92669b811cfe2c45716/lib/bridge-client/index.js#L1005

**Comment by yuilleb** [comment]
Thanks for the help @littleskunk. I've managed to submit a [pull request for kad](https://github.com/kadtools/kad/pull/72).
