### ISSUE TITLE
Newest Storj Gui Client never connects to network

### ISSUE THREAD

**Issue by bakd247** [Storj/core#488]
i have tried using storj app twice now and all it does is say its preparing then it crashes...debug says it failed to connect to the network....and there is only 1 peer connected.....I have tried everything I can think of and have3 come to the conclusion that this app does not work with windows 10

**Comment by littleskunk** [comment]
Did you try to read the release notes? https://github.com/Storj/storjshare-gui/releases/tag/v2.0.7
