### ISSUE TITLE
File Doesn't Exist, but Continues

### ISSUE THREAD

**Issue by super3** [Storj/core#495]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
 -> C:\Users\work\AppData\Roaming\nvm\v4.5.0 C:\Program Files\nodejs
└── storj@3.2.3
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

Asks for keyring password without error.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
C:\Users\work\Desktop>storj download-file 57fd1cba26adcf743a1adc2c 57fd1cec26adcf743a1add32 C:\Users\work\Desktop\storj.exe
 [Tue Oct 11 2016 13:26:29 GMT-0400 (Eastern Daylight Time)] [info]   Name: storjshare-gui.win32_hotfix.exe, Type: application/x-msdownload, Size: 51084256 bytes, ID: 57fd1cec26adcf743a1add32
 [...]  > Enter your passphrase to unlock your keyring  >   [Tue Oct 11 2016 13:26:29 GMT-0400 (Eastern Daylight Time)] [error]  file 57fd1cec26adcf743a1add32 does not exist in bucket 57fd1cba26adcf743a1adc2c

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload a file.
2. Download it, and it errors before asking for the keyring password.
3. You can still enter the keyring password and it will work.

**Comment by aleitner** [comment]
This doesn't exist in the latest cli
