### ISSUE TITLE
Features for Mirroring

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#500]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

- Allow user to check how many mirrors have been created
- Inform user at mirroring how many mirrors have already been created and how many can still be created
- Allow mirroring of all files inside a buckets at once
- Core-CLI informs the user the specific file now has x amount of mirrors, only (12-x) mirrors can now still be made. If No more mirrors can be created for a file the user is informed on this matter.

### Actual Behavior

- We can only mirror one file at a time.
- A user does not know if the file is already mirrored or not, and how many mirrors are currently in circulation for that specific file

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by bookchin** [comment]
Please move this to bridge
