### ISSUE TITLE
Upload of 2GB file routinely fails with

### ISSUE THREAD

**Issue by 1credit** [Storj/core#505]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
npm -list -g storj
/usr/lib64
storj@4.0.1

storj --version
Storjcli:  1.0.11 | Core:  4.0.2
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

Upload to succeed.

```

```

### Actual Behavior

 storj upload-file -c 1 -r 1 57b51555af035fde12cf7f5b /home/fspoe.junk , where fspoe.junk is a 2GB file, tries... it really does.  The file is split into 26 shards and it manages to upload most, but sometime before finishing, it eventually dies after retrying for a contract.  Example below shows it struggling, but succeeding after retry #10, a success after retry #4, then a timeout and abort:

 [Thu Oct 13 2016 10:12:06 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 1)
 [Thu Oct 13 2016 10:12:09 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 2)
 [Thu Oct 13 2016 10:12:12 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 3)
 [Thu Oct 13 2016 10:12:15 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 4)
 [Thu Oct 13 2016 10:12:18 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 5)
 [Thu Oct 13 2016 10:12:21 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 6)
 [Thu Oct 13 2016 10:12:24 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 7)
 [Thu Oct 13 2016 10:12:27 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 8)
 [Thu Oct 13 2016 10:12:30 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 9)
 [Thu Oct 13 2016 10:12:33 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 10)
 [Thu Oct 13 2016 10:12:35 GMT-0500 (CDT)] [info]   Contract negotiated with: {"userAgent":"4.0.2","protocol":"0.9.0","address":"138.201.13.159","port":4054,"nodeID":"07a2e02adae4207d6d8c9c42ce9e3fba","lastSeen":1476371555092}
 [Thu Oct 13 2016 10:12:35 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 138.201.13.159:4054
 [Thu Oct 13 2016 10:12:35 GMT-0500 (CDT)] [info]   Retrying shard transfer, pointer: {"hash":"0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456","token":"9f0c652fe2052d50b559e411c33f6b73","operation":"PUSH","farmer":{"userAgent":"4.0.2","protocol":"0.9.0","address":"138.201.13.159","port":4054,"nodeID":"07a2e02a766abd4ddae4207d6d8c9c42ce9e3fba","lastSeen":55092}}
 [Thu Oct 13 2016 10:12:35 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 138.201.13.159:4054
 [Thu Oct 13 2016 10:12:35 GMT-0500 (CDT)] [info]   Shard transfer failed 1 times, getting another contract...
 [Thu Oct 13 2016 10:12:35 GMT-0500 (CDT)] [info]   Hash for this shard is: 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456
 [Thu Oct 13 2016 10:12:36 GMT-0500 (CDT)] [info]   Audit generation for shard done.
 [Thu Oct 13 2016 10:12:36 GMT-0500 (CDT)] [info]   Waiting on a storage offer from the network...
 [Thu Oct 13 2016 10:12:36 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 0)
 [Thu Oct 13 2016 10:12:39 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 1)
 [Thu Oct 13 2016 10:12:42 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 2)
 [Thu Oct 13 2016 10:12:45 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 3)
 [Thu Oct 13 2016 10:12:47 GMT-0500 (CDT)] [info]   Contract negotiated with: {"userAgent":"4.0.2","protocol":"0.9.0","address":"50.171.239.236","port":7646,"nodeID":"1b28ede37fd78de3cc119524eae25edf","lastSeen":1476371566758}
 [Thu Oct 13 2016 10:12:47 GMT-0500 (CDT)] [info]   Data channel opened, transferring shard...
 [Thu Oct 13 2016 10:14:17 GMT-0500 (CDT)] [info]   Shard transfer completed! 11 remaining...
 [Thu Oct 13 2016 10:14:17 GMT-0500 (CDT)] [info]   Trying to upload shard /tmp/6462cd69e386 index 21
 [Thu Oct 13 2016 10:14:17 GMT-0500 (CDT)] [info]   Hash for this shard is: 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059
 [Thu Oct 13 2016 10:14:18 GMT-0500 (CDT)] [info]   Audit generation for shard done.
 [Thu Oct 13 2016 10:14:18 GMT-0500 (CDT)] [info]   Waiting on a storage offer from the network...
 [Thu Oct 13 2016 10:14:18 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 0)
 [Thu Oct 13 2016 10:14:21 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 1)
 [Thu Oct 13 2016 10:14:24 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 2)
 [Thu Oct 13 2016 10:14:27 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 3)
 [Thu Oct 13 2016 10:14:30 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 4)
 [Thu Oct 13 2016 10:14:33 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 5)
 [Thu Oct 13 2016 10:14:36 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 6)
 [Thu Oct 13 2016 10:14:39 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 7)
 [Thu Oct 13 2016 10:14:42 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 8)
 [Thu Oct 13 2016 10:14:45 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 9)
 [Thu Oct 13 2016 10:14:48 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 10)
 [Thu Oct 13 2016 10:14:51 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 11)
 [Thu Oct 13 2016 10:14:54 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 12)
 [Thu Oct 13 2016 10:14:57 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 13)
 [Thu Oct 13 2016 10:15:00 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 14)
 [Thu Oct 13 2016 10:15:03 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 15)
 [Thu Oct 13 2016 10:15:06 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 16)
 [Thu Oct 13 2016 10:15:09 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 17)
 [Thu Oct 13 2016 10:15:12 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 18)
 [Thu Oct 13 2016 10:15:15 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 19)
 [Thu Oct 13 2016 10:15:18 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 20)
 [Thu Oct 13 2016 10:15:21 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 21)
 [Thu Oct 13 2016 10:15:24 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 22)
 [Thu Oct 13 2016 10:15:27 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 23)
 [Thu Oct 13 2016 10:15:30 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 24)
 [Thu Oct 13 2016 10:15:33 GMT-0500 (CDT)] [warn]   Failed to upload shard...
 [Thu Oct 13 2016 10:15:33 GMT-0500 (CDT)] [warn]   [ fspoe.junk ] Error occurred. Triggering cleanup...
 [Thu Oct 13 2016 10:15:33 GMT-0500 (CDT)] [info]   [ fspoe.junk ] Cleaning up...
 [Thu Oct 13 2016 10:15:33 GMT-0500 (CDT)] [info]   [ fspoe.junk ] Finished cleaning!
 [Thu Oct 13 2016 10:15:33 GMT-0500 (CDT)] [error]  ETIMEDOUT

Note:  Various combinations of -r and -c  have been tried, including the defaults, -c3 -r 12, and for this example, -c 1 -r 1.
```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by bookchin** [comment]
Thanks @1credit, can you move this to the bridge repo?
