### ISSUE TITLE
Large file upload error - rapid death

### ISSUE THREAD

**Issue by 1credit** [Storj/core#507]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
fspoe home # npm list -g storj
/usr/lib64
âââ storj@4.0.1
fspoe home # storj --version
Storjcli: 1.0.11 | Core: 4.0.2

```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Uploads work
```

### Actual Behavior

fspoe ~ # ./upload-file /home/spoe.tar.gz
 [Thu Oct 13 2016 14:18:31 GMT-0500 (CDT)] [info]   1 file(s) to upload.
 [Thu Oct 13 2016 14:18:31 GMT-0500 (CDT)] [info]   Generating encryption key...
 [Thu Oct 13 2016 14:18:31 GMT-0500 (CDT)] [info]   Encrypting file "/home/spoe.tar.gz"
 [Thu Oct 13 2016 14:19:24 GMT-0500 (CDT)] [info]   [ spoe.tar.gz ] Encryption complete
 [Thu Oct 13 2016 14:19:24 GMT-0500 (CDT)] [info]   [ spoe.tar.gz ] Creating storage token... (retry: 0)
 [Thu Oct 13 2016 14:19:24 GMT-0500 (CDT)] [debug]  Parameter for ECDSA signature: POST\n/buckets/57b51555af035fde12cf7f5b/tokens\n{"operation":"PUSH","__nonce":"aca29966-4768-4c96-888e-e4ece877eb5f"}
 [Thu Oct 13 2016 14:19:24 GMT-0500 (CDT)] [debug]  Request: {"baseUrl":"https://api.storj.io","uri":"/buckets/57b51555af035fde12cf7f5b/tokens","method":"POST","timeout":3000,"json":{"operation":"PUSH","__nonce":"aca29966-4768-4c96-888e-e4ece877eb5f"},"headers":{"x-pubkey":"03e9a81c2096129b0a026225abd42cc7e78c9df8e34e6954523d9b3dbbe89c94ea","x-signature":"3045022100b68a55f22e27ec4e66ba0ef43b1a9a77df62765aeb0ca8683bfe497f6006c95802207efed52244c87a769636c0e26ed9585614de61ff73159a176d9b5aa276666628"}}
 [Thu Oct 13 2016 14:19:27 GMT-0500 (CDT)] [debug]  Body: undefined
 [Thu Oct 13 2016 14:19:27 GMT-0500 (CDT)] [info]   [ spoe.tar.gz ] Creating storage token... (retry: 1)
 [Thu Oct 13 2016 14:19:27 GMT-0500 (CDT)] [debug]  Parameter for ECDSA signature: POST\n/buckets/57b51555af035fde12cf7f5b/tokens\n{"operation":"PUSH","__nonce":"06e0714b-8ce2-4ff7-b0df-d25cbcd07b4f"}
 [Thu Oct 13 2016 14:19:27 GMT-0500 (CDT)] [debug]  Request: {"baseUrl":"https://api.storj.io","uri":"/buckets/57b51555af035fde12cf7f5b/tokens","method":"POST","timeout":3000,"json":{"operation":"PUSH","__nonce":"06e0714b-8ce2-4ff7-b0df-d25cbcd07b4f"},"headers":{"x-pubkey":"03e9a81c2096129b0a026225abd42cc7e78c9df8e34e6954523d9b3dbbe89c94ea","x-signature":"3045022100f9fe0b25ea70997dcb7575d72be85658dab454ce4c6e94e87531533728d2b56a02207846398bcdb360cd2715f938f77a45e4151f38086596421aabd8f5dddd059d22"}}
 [Thu Oct 13 2016 14:19:29 GMT-0500 (CDT)] [debug]  Body: {"bucket":"57b51555af035fde12cf7f5b","operation":"PUSH","expires":"2016-10-13T19:24:28.762Z","token":"538de377d75e76fbe2e0f1101725890d4e14e2def3ab7f0f005ef8321eea8097","id":"538de377d75e76fbe2e0f1101725890d4e14e2def3ab7f0f005ef8321eea8097"}
 [Thu Oct 13 2016 14:19:29 GMT-0500 (CDT)] [info]   [ spoe.tar.gz ] Storing file, hang tight!
 [Thu Oct 13 2016 14:19:29 GMT-0500 (CDT)] [debug]  Parameter for ECDSA signature: POST\n/frames\n{"__nonce":"e654363f-8076-4024-9efa-cf6e82205c25"}
 [Thu Oct 13 2016 14:19:29 GMT-0500 (CDT)] [debug]  Request: {"baseUrl":"https://api.storj.io","uri":"/frames","method":"POST","timeout":3000,"json":{"__nonce":"e654363f-8076-4024-9efa-cf6e82205c25"},"headers":{"x-pubkey":"03e9a81c2096129b0a026225abd42cc7e78c9df8e34e6954523d9b3dbbe89c94ea","x-signature":"3045022100afb4481d73dbf5ebce7288ca5d740512b28d7cd7d058d10bd7916a7f5c54405a02207455f5b6cd83a95d7e9ad68d6c2852bf427425a542bb45ce5ab28dac434db7b0"}}
 [Thu Oct 13 2016 14:19:32 GMT-0500 (CDT)] [debug]  Body: undefined
 [Thu Oct 13 2016 14:19:32 GMT-0500 (CDT)] [warn]   [ spoe.tar.gz ] Error occurred. Triggering cleanup...
 [Thu Oct 13 2016 14:19:32 GMT-0500 (CDT)] [info]   [ spoe.tar.gz ] Cleaning up...
 [Thu Oct 13 2016 14:19:34 GMT-0500 (CDT)] [info]   [ spoe.tar.gz ] Finished cleaning!
 [Thu Oct 13 2016 14:19:34 GMT-0500 (CDT)] [error]  ETIMEDOUT

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...export STORJ_KEYPASS
2. ...storj upload-file -d -c 1 -r 1 57b51555af035fde12cf7f5b $1
3. ...

**Comment by bookchin** [comment]
This is related to the bridge issues right now, so i'm going to close it as there are a number of other issues tracking this.
