### ISSUE TITLE
Tunnel traffic low priority

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#51]
As normal user I would like to give my own farmer more traffic priority than the tunnel connections. That would allow me to maximize my traffic income and allow tunnel connection without the risk to loose my own better paid contracts.

As long as we don't have any traffic payment this can wait.

**Comment by super3** [comment]
@littleskunk I really don't see tunnels being maxed out, especially if there is payment involved. If users want to give their own farmers more priority, I think they should have to script it themselves.
