### ISSUE TITLE
ntp delta 5-15 seconds > PUBLISH TTL -> never send an OFFER

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#515]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
StorjShare: 7.0.1
Core:       4.0.2
Protocol:   0.9.0
```

Replace the values below using the output from `node --version`.

```
v4.6.0
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

System clock is not syncronized with NTP error message if the clock is out of sync for more than 5 seconds.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

We allow 15 seconds offset. All incoming contracts have a TTL of only 5 seconds. Farmer will drop them all and send not one OFFER. https://github.com/Storj/core/blob/5c1c222d0043a957ab7da95d4e60557dda00a486/lib/utils.js#L275
```
Clock is synchronized with ntp, delta: 6748
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Set wrong system clock. Offset between 5 and 15 seconds
2. Start farming. You will be able to connect but never send an OFFER

**Comment by littleskunk** [comment]
I would prefer this solution: https://github.com/Storj/core/issues/521

**Comment by bookchin** [comment]
I think this no longer matter as of https://github.com/kadtools/kad-quasar/issues/12

#521 can stay open though
