### ISSUE TITLE
Terminate Excessively Slow Farmers

### ISSUE THREAD

**Issue by super3** [Storj/core#516]
### Package Versions

Replace the values below using the output from `npm list storj`. Use `npm list -g storj` if installed globally.

```
/root/.nvm/versions/node/v4.4.5/lib
└── storj@4.0.1
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```
### Expected Behavior

The client could do some linear estimation on time to completion of a shard with the average download/upload speed after some time. At first this could be a constant, if the upload for a shard is projected to take an hour or two (or some "long" time period) that should probably be terminated. Later on it could look at other shards transferred, so if the other shards took on average 30 seconds, and this one is projected to take 30 minutes it should be terminated. 
### Actual Behavior

This is less of a problem for smaller files, even with very slow speeds if the shard size is only a few MBs they will transfer in a reasonable amount of time. This becomes more of an issue as the file sizes get larger. For example, a 10 GB file might have shard sizes of 300 MB. Selecting a valid but slow farmer that transfers at 300 kpbs, will make for a really poor upload/download. This is an issue regardless of profiling. 

Assuming we have 848 farmers and 15 of them are very slow, if you upload a file that requires 30 shards there is a ~41% probability of running into a very slow with replacement (i.e. a farmer can get more than one shard). If we assume there is no replacement the probability becomes ~42%. 

```
 [Fri Oct 14 2016 20:54:42 GMT+0000 (UTC)] [info]   Shard transfer completed! 3 remaining...
 [Fri Oct 14 2016 20:54:42 GMT+0000 (UTC)] [info]   Trying to upload shard /tmp/8d0b8acb36b0 index 12
 [Fri Oct 14 2016 20:54:42 GMT+0000 (UTC)] [info]   Hash for this shard is: feed45310eb2c024d4b56b0f89696fb49784da29
 [Fri Oct 14 2016 20:54:42 GMT+0000 (UTC)] [info]   Audit generation for shard done.
 [Fri Oct 14 2016 20:54:42 GMT+0000 (UTC)] [info]   Waiting on a storage offer from the network...
 [Fri Oct 14 2016 20:54:42 GMT+0000 (UTC)] [info]   Querying bridge for contract for feed45310eb2c024d4b56b0f89696fb49784da29 (retry: 0)
 [Fri Oct 14 2016 20:54:44 GMT+0000 (UTC)] [info]   Contract negotiated with: {"userAgent":"4.0.2","protocol":"0.9.0","address":"194.165.230.30","port":5000,"nodeID":"f21c5c830b401e217a0b43bd91ca85ce5417753f","lastSeen":1476478484013}
 [Fri Oct 14 2016 20:54:44 GMT+0000 (UTC)] [info]   Data channel opened, transferring shard...
 [Fri Oct 14 2016 20:54:45 GMT+0000 (UTC)] [info]   Querying bridge for contract for 061676fe9e7d3167e83a782d6c8593d62c65639b (retry: 1)
 [Fri Oct 14 2016 20:54:47 GMT+0000 (UTC)] [info]   Contract negotiated with: {"userAgent":"4.0.2","protocol":"0.9.0","address":"88.168.2.129","port":16672,"nodeID":"35e073142ffc72f0ed61433005d935b7e394de5a","lastSeen":1476478487051}
 [Fri Oct 14 2016 20:54:47 GMT+0000 (UTC)] [info]   Shard transfer completed! 2 remaining...
 [Fri Oct 14 2016 20:54:47 GMT+0000 (UTC)] [info]   Data channel opened, transferring shard...
 [Fri Oct 14 2016 20:54:53 GMT+0000 (UTC)] [info]   Shard transfer completed! 1 remaining...
```
### Steps to Reproduce
1. Upload a larger file
2. You have a high probability of selection a bad farmer
3. Upload will take forever to complete because of the one bad farmer

**Comment by MeijeSibbel** [comment]
Yep, same issue, the upload hangs again and never completes,

```
 [Sat Oct 15 2016 21:55:21 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard E:\Upload\temp\d26751e8dcde index 23
 [Sat Oct 15 2016 21:55:29 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 7d214705f390d25cf142df06d2a813d9a90611de
 [Sat Oct 15 2016 21:55:32 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Sat Oct 15 2016 21:55:32 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Sat Oct 15 2016 21:55:32 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 7d214705f390d25cf142df06d2a813d9a90611de (retry: 0)
 [Sat Oct 15 2016 21:55:34 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"userAgent":"4.0.2","protocol":"0.9.0","address":"138.201.13.159",
"port":4012,"nodeID":"7bc3b922c306171154d5b9b75bcc3f9f86fe7006","lastSeen":1476561322702}
 [Sat Oct 15 2016 21:55:34 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Sat Oct 15 2016 21:56:51 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 5 remaining...
 [Sat Oct 15 2016 21:59:08 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 4 remaining...
 [Sat Oct 15 2016 22:00:24 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 3 remaining...
 [Sat Oct 15 2016 22:01:24 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 2 remaining...
 [Sat Oct 15 2016 22:02:10 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 1 remaining...
```

**Comment by MeijeSibbel** [comment]
I don't know why but this became a big issue since the last 2 bridge releases, i am having farmers uploading and downloading my data at speeds of <10kb/s , which causes my entire download or upload forever to complete.

**Comment by MeijeSibbel** [comment]
Also related to https://github.com/Storj/bridge/issues/279

**Comment by bookchin** [comment]
This should be handled by the latest complex/bridge release
