### ISSUE TITLE
ESOCKETTIMEDOUT on trying to list buckets

### ISSUE THREAD

**Issue by Utsav2** [Storj/core#551]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
/usr/local/lib
└── storj@4.0.1 
```

Replace the values below using the output from `node --version`.

```
v5.8.0
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
storj list-buckets
 [Sun Nov 13 2016 15:15:34 GMT-0600 (CST)] [error]  ESOCKETTIMEDOUT
```

**Comment by littleskunk** [comment]
Should be fixed with latest bridge update. Please try again.

**Comment by bookchin** [comment]
https://github.com/Storj/bridge/issues/281
