### ISSUE TITLE
Bandwidth Limits

### ISSUE THREAD

**Issue by yuilleb** [Storj/core#552]
### Feature

I'm sure this has been talked about, but it would be very nice we could set strojshare bandwidth limits on file uploads and downloads. I've noticed my network slow to a crawl recently and could really use this feature.

I found some example code that appears to rate limit streams. https://gist.github.com/4poc/1454516/8208b391adf7b7af8841c1bee6309f66eb244535

**Comment by bookchin** [comment]
Duplicate https://github.com/Storj/storjshare-cli/issues/150
