### ISSUE TITLE
Renter can't locate farmer for shard download

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#553]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
root@farmer:~# storjshare --version
StorjShare: 8.0.0
Core:       5.0.1
Protocol:   0.10.0
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

I uploaded a single 1GB shard to my own farmer this morning (30 minutes old). I stoped the farmer for a few minutes to simulate a short downtime. Farmer is now running again. In my case same IP and Port but they could have changed.

Now its time for some download tests. I am using get-pointers for this. I would expect one of the following 2 solutions:
1.) The renter close to me starts locating me. Should find me with one iteration.
2.) A random renter far away from me starts locating me. In this case renter need to perform the aggressiv find node with more than one iteration.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

My storj-cli gets timeouts. I am not able to download the shard even if it is only 30 minutes old.

My farmer is getting messages from different renterIDs. -> We have a design problem. A renter far away from me will not be able to locate me with only one find node iteration. My own farmer needs at least 3 find node itereration to find a specific nodeID that is close to me. The renter should have the same problem.

For the renter the situation is even worse. As farmer I can send out only one find node iteration. I will not be able to locate the renter on the first try but all other farmer are doing the same. Sooner or later the renter contact information will find a way to every farmer. Even with only one find node iteration I will find the renter.
My farmerID don't has this option. If a renterID far away from me would like to locate me it will never work with only one iteration.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload a shard to my own farmer.
2. Try to download the shard and watch for timeouts.
3. Take a look at farmer logfile. Which node was sending `authorizing data channel for`

**Comment by littleskunk** [comment]
"Storj Bridge","version":"2.1.0","description":"Access the Storj network using a simple REST API.","x-protocol-version":"0.10.0","x-core-version":"5.1.0"

**Comment by vevarm** [comment]
good analysis and good work

**Comment by bookchin** [comment]
https://github.com/Storj/complex/pull/25
