### ISSUE TITLE
UNKNOWN: unknown error, read

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#556]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@2.2.0 /home/gordon/Code/storj-bridge
└── storj@5.1.2  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Upload is succesfull
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
7
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: UNKNOWN: unknown error, read
    at Error (native)

Waiting for 0 seconds, press a key to continue ...
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run a upload script
2. Hope to get the error
3. ...

**Comment by bookchin** [comment]
Closing. If reproducible now, can reopen.
