### ISSUE TITLE
PING to death

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#560]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
StorjShare: 8.0.0
Core:       5.1.2
Protocol:   0.10.0
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
1.) no room in bucket, sending PING to contact at head
2.) move contact to tail while waiting for the PING response
3.) no room in bucket, sending PING to contact at head (should not ping the same contact again)
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

I am sending PING message only to one farmer in that bucket. The faster I receive messages and don't have room to store the contact the more PING message I will send to that node. I will spam him to death. He needs one timeout in order to stop me spamming.
```
{"level":"debug","message":"no room in bucket, sending PING to contact at head","timestamp":"2016-11-19T13:37:31.003Z"}
{"level":"info","message":"sending PING message to {\"userAgent\":\"5.0.1\",\"protocol\":\"0.10.0\",\"address\":\"96.42.248.149\",\"port\":26181,\"nodeID\":\"2f29a6c671f020a86dd7e2ee00fe522242685cd3\",\"lastSeen\":1479562651004}","timestamp":"2016-11-19T13:37:31.004Z"}
{"level":"debug","message":"queuing callback for reponse to 82af24270853c3f7d16982aca7762ca719db919f","timestamp":"2016-11-19T13:37:31.076Z"}
{"level":"debug","message":"checking pending rpc callback stack for 41583104685a8e0a22f275f7837436ef82555b14","timestamp":"2016-11-19T13:37:31.080Z"}
{"level":"debug","message":"updating contact {\"userAgent\":\"5.1.0\",\"protocol\":\"0.10.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":15411396,\"address\":\"104.196.39.49\",\"port\":8456,\"nodeID\":\"028b17330d1f33b97ef497ecdd64ef0b14c0ca3a\",\"lastSeen\":1479562650428}","timestamp":"2016-11-19T13:37:31.081Z"}
{"level":"debug","message":"no room in bucket, sending PING to contact at head","timestamp":"2016-11-19T13:37:31.082Z"}
{"level":"info","message":"sending PING message to {\"userAgent\":\"5.0.1\",\"protocol\":\"0.10.0\",\"address\":\"96.42.248.149\",\"port\":26181,\"nodeID\":\"2f29a6c671f020a86dd7e2ee00fe522242685cd3\",\"lastSeen\":1479562651083}","timestamp":"2016-11-19T13:37:31.083Z"}
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Not easy to reproduce. Most of the time I only receive PING message. Keep node running for a few hours and look for 'sending PING'

**Comment by littleskunk** [comment]
I don't think step 2 "move contact to tail while waiting for the PING response" is a good idea. It is just an example and you should not implement it. I would expect conflicts with other functions that would like to send message to the contact at head.

**Comment by bookchin** [comment]
Let's move this one to kad

**Comment by littleskunk** [comment]
https://github.com/kadtools/kad/issues/80
