### ISSUE TITLE
Bridge renter causing PING and FIND_NODE spam messages

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#561]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
StorjShare: 8.0.0
Core:       5.1.2
Protocol:   0.10.0
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

Bridge would like to upload a shard with hash X. I would expect that a renter close to shard X will send out the contract.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

A random renter will send out the contract. That way 50% of all shards will be send out by a renterID far away from the target shard hash. This renter will have to communicate with farmer far away. Each farmer will relay the message to neighbor nodes. They all send an OFFER to the renter far away.

For an easy example lets do this with 50 bridge renterIDs. 25 renterID are to far away from me and I should not communicate with them but they initiate a communication with me and my neighbors. We all can only hold 20 renter in our contact list but we would like to send out OFFER to all 25. This is the start point of a never ending FIND_NODE and PING loop. We simply don't have room for all bridge renterIDs.

Here is one example. Shard hash starting with 0 send out by bridge renterID starting with b.
```
{"level":"debug","message":"shard hash: 090ca18ac4e13f3a4093aaff15ffe56ba43126d2","timestamp":"2016-11-20T19:02:21.924Z"}
{"level":"debug","message":"searching for nodes close to key bb534eef7f7717c4bd3a583dda0737c33ea9eb2d","timestamp":"2016-11-20T19:02:25.194Z"}
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start farming and compare the shard hash and renterID.

**Comment by bookchin** [comment]
Please reopen in storj-complex

**Comment by littleskunk** [comment]
Done https://github.com/Storj/complex/issues/21
