### ISSUE TITLE
How a slow node gets a poorly performing node

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#565]
> Reporting will help us identify inactive and poorly performing nodes quicker, which will help improve stability, performance, and reliability within our network.
https://docs.google.com/document/d/1ay0hAorywLD3nq8H4COI9tkn0O6ARs-ojkZSD7dRSuY

Lets say I have only 1MBit/s internet connect. Pending OFFER count gets reduced on bridge response (opening data channel). Even with concurrency 1 my node will start sending new OFFER. If I have bad luck I will get more and more pending shard transfers and each transfer will get slower and slower. At the end storj labs will kick me out but there is no way for me to escape this trap. 1MBit/s would be fast enough if I would have an option to stop sending OFFER while a shard transfer is active. 

Perfect solution would be a minimum bandwidth limit. An online speedtest is simple to execute and will give me some numbers to calculate. I would like to set a minimum speed of 100KBit/s (or what every is need to not get kicked out). My farmer should not send an offer as long as speedtest bandwidth - current bandwidth is lower than minimum speed.

I think this solution is needed in order to prevent this attack:
I have 100MBit/s Up and Download speed. Time to run 100000 uploads with 1KBit/s limit for each instance. This would block all other farmer and allow my own farmer to get more contracts.

**Comment by littleskunk** [comment]
Asynchronous up and download bandwidth are common in germany. Mirrors are another problem for me. Lets run this attack:
Upload shards with as many mirrors as possible and add more mirrors as soon as possible (mirror limit per api call. There is no total limit)
As long as this attack is running more and more farmer will behave like poorly performing nodes. They can't stop it. The exchange report will kick them out.

**Comment by bookchin** [comment]
I like the idea of a simple configuration that allows you to pause on sending OFFERs when N transfers are active. 

We could even use the existing `maxOfferConcurrency` to do this. After all, OFFERS are cheap compared to actual transfer so I think that's probably what you really want anyway.

**Comment by littleskunk** [comment]
I agree. OFFERs are cheap. We can use the existing maxOFFERConcurrency.

How about the mirror download problem?

**Comment by bookchin** [comment]
We can add another mirror concurrency config that would reject the MIRROR request if there are already N mirror transfers active.

**Comment by littleskunk** [comment]
Sounds very good :)

**Comment by littleskunk** [comment]
Fixed with OfferBackoffLimit. My node stops sending OFFER as soon as my upload bandwidth is 100% used. Sooner or later my node will find a good balance.
