### ISSUE TITLE
Make ldb file size some sane power-of-2 value

### ISSUE THREAD

**Issue by CJClaude** [Storj/core#567]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
StorjShare: 8.0.0
Core:       5.1.2
Protocol:   0.10.0

```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

```
ldb files would be some reasonable multiple of common filesystem blocksizes, such as 64kb.
```

### Actual Behavior

```
Most observered ldb files are either 2103723 or 4207391 bytes in length. (2,055 KB or 4,109 KB  as reported by Windows).  Since this is not a regular blocksize, space is wasted for each and every file - surprising for a storage product.

Using a ZFS filesystem as a specific example, the default blocksize is 128KB.  Thus a 2103723 byte file uses 16 full blocks plus a 17th block containing only 6571 bytes - essentially wasting about 6% of the file system space and making i/o bandwidth similiarly inefficient.

ps.  File sizes confirmed on ext4, btrfs, and zfs.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Issue an "ls -l" against most any sharddata.kfs subdirectory
2. ...
3. ...

**Comment by bookchin** [comment]
See https://github.com/dain/leveldb/issues/40
