### ISSUE TITLE
leveldb using Syncronous I/O?

### ISSUE THREAD

**Issue by CJClaude** [Storj/core#569]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
StorjShare: 8.0.0
Core:       5.1.2
Protocol:   0.10.0

```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
All generated I/O should be Asycronous to maximize system throughput.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Apparently some part of storjshare-cli, lilkely leveldb, is using syncronous I/O.  This is a performance killer usually reserved for critical I/O that would result in fatal corruption issues if the system crashed.  In the case of Storj, a system crash would simply terminate a transfer and any open files would be incomplete, and presumably purged at the next audit.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Place Storj data drives on a dedicated ZFS filesystem.
2. Define a seperate ZFS ZIL location on really fast disk (like NVME, or for testing, a ramdisk)
3. Utilize "iostat -p /dev/<zil device> 2 2" to compare average and short term I/O rates to the ZIL device.

On my system (dual 14 core hyperthreaded Xeons - 56 threads) running 64 instances of storjshare, I see a write rate of over 42MB/second AVERAGE since system boot time.  Storjshare is the only resource that utilizes the backed ZFS filessytem (a Z2 built across 10 8TB drives)

**Comment by braydonf** [comment]
leveldown/leveldb is using async i/o with a thread pool of 4 by default for each Node.js process: https://github.com/Level/leveldown/blob/master/src/database.cc#L274

**Comment by CJClaude** [comment]
I'm not a leveldb programmer, but it looks like it can go either way depending on what is selected:

Line 274:  bool sync = BooleanOptionValue(optionsObj, "sync");

Where is optionsObj initialized and/or read in and overwritten?

**Comment by bookchin** [comment]
We have, in fact, set leveldb to perform synchronous writes. This is because crashes like the kind you are described *did* (at least at one point) run the risk of corrupting the shard database.

This may no longer be the case since the work with KFS was implemented. Why don't you patch your KFS package (should be in `lib/s-bucket.js`) to revert this and see how it goes?

**Comment by braydonf** [comment]
Ah, relevant level docs:

>If you provide a 'sync' value of true in your options object, LevelDB will perform a synchronous write of the data; although the operation will be asynchronous as far as Node is concerned. Normally, LevelDB passes the data to the operating system for writing and returns immediately, however a synchronous write will use fsync() or equivalent so your callback won't be triggered until the data is actually on disk. Synchronous filesystem writes are significantly slower than asynchronous writes but if you want to be absolutely sure that the data is flushed then you can use 'sync': true.
https://github.com/Level/levelup#dbputkey-value-options-callback

**Comment by bookchin** [comment]
Actually reviewing the KFS write stream code, and we no longer pass `sync: true`, so I'm not sure about this.

**Comment by CJClaude** [comment]
Thanks for reviewing, I was about to go hack a bit.  It wouldn't take much, with 256 leveldbs running per node now.  My main server has 64 nodes running, so that is 16K leveldbs contributing towards that 42MB/sec.

The combined impact to the system is quite noticeable however.

**Comment by CJClaude** [comment]
For what its worth, currently seeing about 32MBYTES/sec (408 writes/sec) of sync activity on my server dedicated to storj.  That is more bandwidth than my internet download of 200mBITS/sec.  That is with 1042 nodes running with 256GB allocated to each, so roughly 256K leveldb instances.

**Comment by CJClaude** [comment]
Currently running a LOT fewer nodes (like 40 due to other issues right now) and have noticed the Sync write activities goes away awhile after starting.  Feels like something leveldb is doing during its startup process... like perhaps it launches a background sanity check or something that runs for awhile (10s of minutes on 256GB folders) and then goes away satisified.  Because of the number of nodes I was running, and associated disk contention for this hypothetical activity, it would likely show for hours after I launched.

**Comment by bookchin** [comment]
This is likely a side effect of compaction/log replay on db open, based on the information you've given. Closing for now unless we can confirm that all writes following the initial startup period exhibit this behavior.
