### ISSUE TITLE
Seed discovery returns incompatible and offline nodes

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#575]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
GUI
Storj Share 4.0.1
Core Library 6.0.1
Protocol 1.0.0
```

Replace the values below using the output from `node --version`.

```
none
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

Requesting seed list from server025.storj.dk
{"title":"Storj Bridge","version":"3.0.0","description":"Access the Storj network using a simple REST API. Hosted by Th3Van","x-protocol-version":"1.0.0","x-core-version":"6.0.1"}

I would expect a list of compatible nodes. No old protocol version and no offline nodes.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
{debug} [Sat Dec 03 2016 00:29:33 GMT+0100 (Mitteleuropäische Zeit)] Request: {"baseUrl":"http://server025.storj.dk","uri":"/contacts","method":"GET","timeout":30000,"qs":{"connected":true,"__nonce":"dad34303-aab5-43e4-a76a-41788563f7d6"},"json":true}
{debug} [Sat Dec 03 2016 00:29:36 GMT+0100 (Mitteleuropäische Zeit)] Body: [
{"lastSeen":"2016-12-02T23:29:32.123Z","port":4002,"address":"77.70.66.52","userAgent":"5.1.2","protocol":"0.10.0","nodeID":"87d9746cc17b6a4f8ab9c6b8b0e77e189a2452da"},
{"protocol":"0.10.0","userAgent":"5.1.2","address":"138.201.17.121","port":4153,"lastSeen":"2016-12-02T23:29:32.120Z","nodeID":"8faa224a4c37dc971c11946ed1f1614acd1a3dff"},
{"protocol":"0.10.0","userAgent":"5.1.0","address":"104.196.196.231","port":8472,"lastSeen":"2016-12-02T23:29:32.112Z","nodeID":"22901935a4a3eebdc1c462cb7448d667201aa8ad"},
{"protocol":"0.10.0","userAgent":"5.1.0","address":"104.196.39.49","port":8448,"lastSeen":"2016-12-02T23:29:32.112Z","nodeID":"0434996c6148537357bb8127018f88ea94c8d0cf"},
{"lastSeen":"2016-12-02T23:29:32.106Z","port":26399,"address":"24.90.108.93","userAgent":"5.0.1","protocol":"0.10.0","nodeID":"876bffe6d2117139ba1fe98702281da355473adc"},
{"lastSeen":"2016-12-02T23:29:32.102Z","port":44427,"address":"108.63.248.115","userAgent":"5.0.1","protocol":"0.10.0","nodeID":"a9c832465a074654867e3076f660de33e7f1cb37"},
{"protocol":"0.10.0","userAgent":"5.0.1","address":"89.164.183.136","port":53395,"lastSeen":"2016-12-02T23:29:32.094Z","nodeID":"e92a8bf719e3a885b4ad11166b33b8dd9f136cf1"},
...
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by bookchin** [comment]
The requesting node should just filter the incompatible ones out before trying them. This is because the bridge just responds with who it has most recently seen, which in this case are at least partially populated with nodes running the the current release
