### ISSUE TITLE
Uncaught TypeError: res.status(...).end is not a function

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#577]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
GUI
Storj Share 4.0.1
Core Library 6.0.1
Protocol 1.0.0
```

Replace the values below using the output from `node --version`.

```
none
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

No exception

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Uncaught TypeError: res.status(...).end is not a function
C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\network\transport.js:180
https://github.com/Storj/core/blob/master/lib/network/transport.js#L180

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by bookchin** [comment]
Oops! That's express-style, and we are using testify. Will fix
