### ISSUE TITLE
setx STORJ_BRIDGE not working after changing it a few times.

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#581]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@3.0.0 /home/gordon/Code/storj-bridge
└── storj@6.0.1 -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
setx STORJ_BRIDGE <bridge> sets the bridge variable.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
C:\Users\Dani Marion>setx STORJ_BRIDGE http://hack.bookch.in:8080

SUCCESS: Specified value was saved.

C:\Users\Dani Marion>storj get-info
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
 [Wed Dec 07 2016 00:58:52 GMT+0100 (W. Europe Standard Time)] [info]   Title:             Storj Bridge
 [Wed Dec 07 2016 00:58:52 GMT+0100 (W. Europe Standard Time)] [info]   Description:       Access the Storj network using a simple REST API.
 [Wed Dec 07 2016 00:58:52 GMT+0100 (W. Europe Standard Time)] [info]   Version:           2.2.4
 [Wed Dec 07 2016 00:58:52 GMT+0100 (W. Europe Standard Time)] [info]   Host:              0.0.0.0

C:\Users\Dani Marion>storj login
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
 [...]  > Enter your email address  >  meijesibbel@hotmail.com
 [...]  > Enter your password  >  *********

 [Wed Dec 07 2016 00:59:46 GMT+0100 (W. Europe Standard Time)] [error]  ESOCKETTIMEDOUT

C:\Users\Dani Marion>storj login
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
 [...]  > Enter your email address  >  meijesibbel@hotmail.com
 [...]  > Enter your password  >  *********

 [Wed Dec 07 2016 01:00:09 GMT+0100 (W. Europe Standard Time)] [info]   This device has been successfully paired.

C:\Users\Dani Marion>storj get-info
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
 [Wed Dec 07 2016 01:00:28 GMT+0100 (W. Europe Standard Time)] [info]   Title:             Storj Bridge
 [Wed Dec 07 2016 01:00:28 GMT+0100 (W. Europe Standard Time)] [info]   Description:       Access the Storj network using a simple REST API.
 [Wed Dec 07 2016 01:00:28 GMT+0100 (W. Europe Standard Time)] [info]   Version:           2.2.4
 [Wed Dec 07 2016 01:00:28 GMT+0100 (W. Europe Standard Time)] [info]   Host:              0.0.0.0

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. setx STORJ_BRIDGE a few times (different bridges)
2. After changing setx STORJ_BRIDGE a few times it won't change anymore (storj get-info sticks to api.storj.io), the only way to get it to work again is a computer restart. 
3.

**Comment by bookchin** [comment]
How is this an issue with storj-lib? We just read the environment variable your system reports and certainly have no control over what your operating system returns for that variable.

**Comment by littleskunk** [comment]
Note: Windows changed the behavior of `setx`. 
`set` will set a variable only for the current command line session.
`setx` will set a System variable. The current command line session is not effected. Only new command line sessions will get it.
