### ISSUE TITLE
Memory leak to many open data channel

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#583]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
Storj Share 4.0.2
Core Library 6.0.3
Protocol 1.0.0
```

Replace the values below using the output from `node --version`.

```
none
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

Open a few mirror data channel and finish them befor opening new mirror data channels

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

After one 1 houe my node has more than 1GB memory used. I expect WSOD any time. GUI memory snapshot shows ~30000 JSArrayBufferData. I only see `next in writeReq`. Maybe I can add a full stacktrace later.

It looks like to many open data channel. Lets count them on my logfile:

756 sending OFFER message to
440 handling storage consignment request from
443 authorizing data channel for
1 opening data transfer with ... to mirror
69 shard upload completed
6 MIRROR_SUCCESS

= ~371 pending shard uploads? Or at least 371 open data channel?

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start node and wait a few minutes. Memory should grow realy fast.

**Comment by CJClaude** [comment]
This is likely the cause of the resurgence of network issues with this release as well - even with <50% bandwidth usage I'm seeing Rocket disconnects, IRC drops, Skype call issues, BTC miner connection issues, etc.  This behavior has been gone since at least V6, if not V5, and just resurfaced today.

**Comment by littleskunk** [comment]
I was not able to get a full stack trace but maybe a information that should be related:

```
callback :: function nop()
C:\Program Files\Storj Share\resources\app\node_modules\readable-stream\lib\_stream_writable.js:52
```

**Comment by littleskunk** [comment]
Workaround:
Set Storage Size to 1 MB. My node is not sending any OFFER messages and no open data channel. GUI is running stable without any memory leak that way.

**Comment by CJClaude** [comment]
This is likely the cause of the resurgence of network issues with this release as well - even with <50% bandwidth usage I'm seeing Rocket disconnects, IRC drops, Skype call issues, BTC miner connection issues, etc.  This behavior has been gone since at least V6, if not V5, and just resurfaced today.

**Comment by bookchin** [comment]
I am preparing a fix. Setting a default limit of 4 active transfers before an OFFER backoff (configurable via `offerBackoffLimit`). This means the farmer will pause sending offers if there are more than N active transfers at the time of contract receipt.

**Comment by CJClaude** [comment]
Curious if this impacts Concurrency at all?  Does sound like another good reason to run multiple nodes... <smile>
