### ISSUE TITLE
Memory leak queuing callback for reponse - rpc call timed out

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#587]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
Storj Share 4.0.3
Core Library 6.0.5
Protocol 1.0.0
```

Replace the values below using the output from `node --version`.

```
none
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

I start farming for a few hours and created a memory snapshot. The GC should delete old messages after a few hours.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

It looks like timed out messages are not deleted. Even more than 2 hours later I have them in my memory.
```
{info} [Sun Dec 11 2016 12:32:54 GMT+0100 (Mitteleuropäische Zeit)] sending PUBLISH message to {"userAgent":"6.0.6","protocol":"1.0.0","address":"rackserv.carpenter-farms.us","port":8090,"nodeID":"b0aa200946a5d403b2060dca6c1d9d8e7ca6cc19","lastSeen":1481455974749}
{debug} [Sun Dec 11 2016 12:32:54 GMT+0100 (Mitteleuropäische Zeit)] queuing callback for reponse to e9f097def967f332012376dae74df33d4fddf3a5
...
{warn} [Sun Dec 11 2016 12:33:24 GMT+0100 (Mitteleuropäische Zeit)] rpc call e9f097def967f332012376dae74df33d4fddf3a5 timed out
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start GUI and keep it running for a few hours. Loglevel debug.
2. Create a memory snapshot and track down the list of strings. Search for anything that looks like a id on the logfile.

**Comment by bookchin** [comment]
Good sleuthing! Found it. This didn't get brought over during transport adapter rewrite: https://github.com/kadtools/kad/blob/master/lib/transports/http.js#L182

**Comment by littleskunk** [comment]
The Stack trace ends here:
https://github.com/Storj/core/blob/58310173f8b37b17976b4e135a8fa21d2289f408/lib/network/transport.js#L38

This object still holds all timed out messages.

@bookchin your turn. https://github.com/kadtools/kad/blob/130fdf0a594a89b6f87d6ca80021c44d03aaf394/lib/rpc.js#L366 should have deleted it?

**Comment by littleskunk** [comment]
Oh I see I am to late :D
