### ISSUE TITLE
Uploading file to public bucket fails

### ISSUE THREAD

**Issue by retrohacker** [Storj/core#589]
### Package Versions

Replace the values below using the output from `npm list -g | grep storj` if installed globally.

```
/usr/local/lib
`-- storj-cli@3.1.1
  +-- storj-lib@6.0.7
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
$ storj upload-file PublicBucket test.png # should upload file
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
$ storj upload-file PublicBucket test.png # should upload file
 [Sun Dec 11 2016 22:21:32 GMT+0000 (UTC)] [info]   1 file(s) to upload.
 [...]  > Enter your passphrase to unlock your keyring  >
 [Sun Dec 11 2016 22:21:36 GMT+0000 (UTC)] [info]   Generating encryption key...
 [Sun Dec 11 2016 22:21:36 GMT+0000 (UTC)] [warn]   Request failed, reason: Error: File not found
 - retrying(false)...
 [Sun Dec 11 2016 22:21:36 GMT+0000 (UTC)] [info]   [ stage-1225.JPG ] Creating storage token... (retry: 0)
 [Sun Dec 11 2016 22:21:36 GMT+0000 (UTC)] [info]   Encrypting file "stage-1225.JPG"

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: key is expected to a buffer
    at Function.DeterministicKeyIv.getDeterministicKey (/usr/local/lib/node_modules/storj-cli/node_modules/storj-lib/lib/crypto-tools/deterministic-key-iv.js:29:3)
    at /usr/local/lib/node_modules/storj-cli/bin/actions/uploader.js:217:46
    at /usr/local/lib/node_modules/storj-cli/bin/utils.js:59:5
    at _dirCreated (/usr/local/lib/node_modules/storj-cli/node_modules/tmp/lib/tmp.js:311:7)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. `storj generate-seed`
2. `storj add-bucket PublicBucket`
3. `storj make-public PublicBucket --pull`

### Cause

https://github.com/Storj/core/blob/5586c5b50d36e7be5b3e73646552413ae9b39ffb/lib/crypto-tools/deterministic-key-iv.js#L29-L30

`DeterministicKeyIv.getDeterministicKey(key, id)` expects both key and id to be buffers.
These values belong to a token: https://github.com/Storj/core-cli/blob/master/bin/actions/uploader.js#L212
This token is generated with a call to `BridgeClient.createToken`: https://github.com/Storj/core-cli/blob/master/bin/actions/uploader.js#L287
`BridgeClient.createToken` uses `request` under the hood to return JSON: https://github.com/Storj/core/blob/master/lib/bridge-client/index.js#L1086-L1120

This causes both `encryptionKey` and `id` to be strings.

### Suggested patch

Change

```js
DeterministicKeyIv.getDeterministicKey = function(key, id){
  assert(Buffer.isBuffer(key), 'key is expected to a buffer');
  assert(Buffer.isBuffer(id), 'id is expected to be a buffer');
  var buffer = utils.sha512(Buffer.concat([key, id]));
  return buffer.toString('hex').substring(0, 64);
};
```

To

```js
DeterministicKeyIv.getDeterministicKey = function(key, id){
  assert(typeof key === 'string', 'key is expected to be a string');
  assert(typeof id === 'string', 'id is expected to be a string');
  key = Buffer.from(key);
  id = Buffer.from(id);
  var buffer = utils.sha512(Buffer.concat([key, id]));
  return buffer.toString('hex').substring(0, 64);
};
```

**Comment by retrohacker** [comment]
If this patch looks good, I'll open a PR.

**Comment by retrohacker** [comment]
After sending this, I realized `getDeterministicKey` is used in other places. Changing the method signature may not be wise.

Instead, leaving that method alone and changing https://github.com/Storj/core-cli/blob/master/bin/actions/uploader.js#L214

From:

```js
var fileKey = storj.DeterministicKeyIv.getDeterministicKey(
        token.encryptionKey, fileId);
secret = new storj.DeterministicKeyIv(fileKey, fileId);
```

To:

```js
var fileKey = storj.DeterministicKeyIv.getDeterministicKey(
        Buffer.from(token.encryptionKey), Buffer.from(fileId));
secret = new storj.DeterministicKeyIv(fileKey, Buffer.from(fileId));
```

**Comment by bookchin** [comment]
@braydonf

**Comment by braydonf** [comment]
Should be `Buffer.from(fileId, 'hex')`, though we may be able to assume 'hex' if a buffer isn't passed in, similar to key pair.

**Comment by bookchin** [comment]
This belong in core-cli repo, closing
