### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by CJClaude** [Storj/core#605]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
Storjcli: 4.0.0 | Core: 6.0.11

```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

```
Uploads run without errors.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
 [Tue Dec 20 2016 07:22:20 GMT-0600 (CST)] [info]   Querying bridge for contract for 0c834a9454c6ccd407adeab15fab2b9dca91553c (retry: 0)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:799:14)

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...Occurs consistantly when trying to upload a 31G file
2. ...Sometimes happens quickly, sometimes takes a half-hour or so of activity.
3. ...

**Comment by bookchin** [comment]
Closing in favor of https://github.com/Storj/core/issues/656
