### ISSUE TITLE
Request: ipv6 support

### ISSUE THREAD

**Issue by BlackDuck888** [Storj/core#607]
Here in germany the provider are forcing the users to upgrade to an all-ip-voip connections. Old connections with analog or isdn technology will be cut off until 2019. 

with a new contract you will get migrated to ipv6 dual stack. some providers only offer ds-lite (dual-stack lite), in detail this mean the ipv4 address is share to many customers at same time. the users are not able to maintain portforwarding.

**Comment by littleskunk** [comment]
>the users are not able to maintain portforwarding.
Port forwarding is not possible on both ipv4 and ipv6 or can they forward only ipv6?

**Comment by BlackDuck888** [comment]
under ipv6 portfording is not needed, you will get a /56 or /64 network. all nodes behing your router will get an public ipv6 address. the router will act as firewall no more as nat device

**Comment by brodyhoskins** [comment]
I would love to see this feature as well, it would definitely help out beginners where IPv6 is available (automatically open ports on the local machine and forget about NAT on IPv6).

**Comment by bookchin** [comment]
Good News, Everyone
==================

![](http://vignette2.wikia.nocookie.net/en.futurama/images/a/ad/GoodNewsEveryone.jpg/revision/latest?cb=20090731021518)

Storj **already supports IPv6**. All you need to do is set your node's `rpcAddress` to your public IPv6 address. Period. :smiley_cat: 

Here you can see my IPv6 farmer running in Digital Ocean for testing. Logs + Status + Config to show where to place the address.

![screenshot-20170208-12 19 40](https://cloud.githubusercontent.com/assets/1188875/22748699/e6f6ba2a-edf8-11e6-9da9-d2143b12a5ee.png)

Additionally the Bridge + Complex see this node as well.

![screenshot-20170208-12 21 24](https://cloud.githubusercontent.com/assets/1188875/22748855/74a0607e-edf9-11e6-9aa0-f80e95f03617.png)

> Note that as of right now, GCP infrastructure does not support IPv6, so the bridge and complex nodes will only be available on IPv4 - however they **seem** to be capable of sending and receiving messages to and from IPv6 farmers.

> Also note that some networks, like shared office or corporate network, and others do not support IPv6. Right now, if a client tries to transfer data to an IPv6 farmer and cannot reach them because of this, the client will retry another farmer. This will also generally trigger a negative exchange report, however later using collaborative filtering, the bridge will be capable of intelligently pairing client with farmer based on historical exchange results.

**Comment by BlackDuck888** [comment]
Deamon is not starting on ipv6 only server!

```
duck@r710-2:~/ipv6$ ifconfig
eno1      Link encap:Ethernet  Hardware Adresse bc:30:5b:e2:33:f9
          inet6-Adresse: fe80::be30:5bff:fee2:33f9/64 Gültigkeitsbereich:Verbindung
          inet6-Adresse: 2003:7a:4976:4f00:be30:5bff:fee2:33f9/64 Gültigkeitsbereich:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metrik:1
          RX-Pakete:52791 Fehler:0 Verloren:0 Überläufe:0 Fenster:0
          TX-Pakete:48865 Fehler:0 Verloren:0 Überläufe:0 Träger:0
          Kollisionen:0 Sendewarteschlangenlänge:1000
          RX-Bytes:29436590 (29.4 MB)  TX-Bytes:8150136 (8.1 MB)

lo        Link encap:Lokale Schleife
          inet Adresse:127.0.0.1  Maske:255.0.0.0
          inet6-Adresse: ::1/128 Gültigkeitsbereich:Maschine
          UP LOOPBACK RUNNING  MTU:65536  Metrik:1
          RX-Pakete:14277 Fehler:0 Verloren:0 Überläufe:0 Fenster:0
          TX-Pakete:14277 Fehler:0 Verloren:0 Überläufe:0 Träger:0
          Kollisionen:0 Sendewarteschlangenlänge:1
          RX-Bytes:1165543 (1.1 MB)  TX-Bytes:1165543 (1.1 MB)

duck@r710-2:~/ipv6$ storjshare-daemon

  * starting daemon in background
duck@r710-2:~/ipv6$ storjshare-status

  daemon is not running, try: storjshare daemon

duck@r710-2:~/.config/storjshare/logs$ storjshare-daemon -F

  * starting daemon in foreground

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:45015
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by BlackDuck888** [comment]
If i use ipv6 only dns entry is the lookup made correctly by the other clients? If they query dns-v4 it will fail.
i have dynamic ipv6 from providerside, using ipv6 naming service is handy for me.
