### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by revathimaha** [Storj/core#612]
I'm gettting the following while installing storj lib in ubuntu 12.04.i used the following code.
npm install storj-lib 

**Error**
prebuild ERR! build error 
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/home/sample/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! stack     at emitTwo (events.js:106:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:191:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/home/sample/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
re@0.1.0 /home/sample
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})
npm WARN react-dom@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN url-loader@0.5.7 requires a peer of file-loader@* but none was installed.
npm ERR! Linux 3.2.0-115-generic-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "storj-lib" "--save"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.5.3 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the leveldown@1.5.3 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sample/npm-debug.log

**Comment by bookchin** [comment]
Make sure you have the `build-essential` package installed.

**Comment by revathimaha** [comment]
thank you for your reply.Build Essential package was intalled.still i'm
getting the same error

**Comment by revathimaha** [comment]
thank you for your reply.Build Essential package was installed.still i'm
getting the same error
