### ISSUE TITLE
GNU/GPL/LGPL is a problem

### ISSUE THREAD

**Issue by mavericken** [Storj/core#613]
Many developers will simply walk away when they see any GNU/GPL/LGPL.  No debate is required-- these developers will walk away, whether they are right or wrong to do so.  It is against the interest of the owners and users of Storj to have developers walk away, as a bigger ecosystem reduces the chance of data loss.  Client libraries at least should be licensed under MIT.

**Comment by bookchin** [comment]
No debate required? Good, see you later.

**Comment by mavericken** [comment]
@bookchin 
Your fast response has saved me time, and I sincerely thank you for that.  Good luck dealing with more inclusive competition.

**Comment by bookchin** [comment]
![](http://extra.wdka.nl/designresearch/files/2013/05/1366746718472.jpg)

**Comment by bookchin** [comment]
![tmp_16883-1366746718472279382439](https://cloud.githubusercontent.com/assets/1188875/21596711/f42875e8-d10c-11e6-9dc3-d2a40928624b.jpg)

**Comment by mavericken** [comment]
You are a pretty fun guy.  I wanted to include this image but I wasn't sure if it was appropriate:
![image](https://cloud.githubusercontent.com/assets/7833752/21596746/7d52b176-d10d-11e6-9edb-d7e2dec2cdfd.png)
Also, I gave my opening statement another read and realized that I didn't quite communicate it exactly as I intended.  The only part I felt did not need debating is the fact that many developers will walk away.  The merits of GNU are actually very debatable.

**Comment by bookchin** [comment]
Most subjects *are* debatable, but that doesn't mean they should be debated ad nauseum as this one certainly would be. Furthermore, our issue tracking board is not the place I'd wish to invite such debate. 

In the interest of saving you more time, I'll just put it simply. We care about free software and we have licensed our work accordingly. The license will not change. The protocol is open and you are free and encouraged to implement it yourself and license that however you like.
