### ISSUE TITLE
Bridge operators have complete access to file metadata

### ISSUE THREAD

**Issue by utdrmac** [Storj/core#617]
This is a huge security issue. This information is available as plain, unencrypted data, to any bridge operator. We, clients and farmers, are supposed to put our trust in the network that our data is safe and secure against invasion and detection.

This is not the case. Any bridge operator can easily log in to their mongo instance and run a basic query to see file names, types and sizes.

This information needs to be either A) redacted completely (why does the bridge need this info in the first place) or B) secured with the uploaders key so that it is only accessible by the original data owner.

```
> db.bucketentries.find().limit(1).pretty()
{
	"_id" : ObjectId("30edc2e708440222ac62029a"),
	"bucket" : ObjectId("4745cc69022a15045cb22590"),
	"__v" : 0,
	"renewal" : ISODate("2017-04-02T21:17:11.811Z"),
	"created" : ISODate("2017-01-02T21:17:11.811Z"),
	"frame" : ObjectId("586ac0a797ecf163e7053838"),
	"name" : "100mb.dat",
	"mimetype" : "application/octet-stream"
}
```

I'll reference bullet point #5 on the master plan: http://blog.storj.io/post/151390093908/storj-master-plan

> Better privacy - Storj operates a zero-knowledge system which does not need to know anything about the data stored on the network in order to be able to operate. This means the USER’s data stays private, and properly built applications can take advantage of this as well.

https://github.com/Storj/bridge/issues/321#issuecomment-270158685

This is a re-open of https://github.com/Storj/bridge/issues/321

**Comment by lunokhod** [comment]
Let me quote from Wilkinson and Lowry (2014):

> We need a cloud storage model that is not based on trust between client and host. All client private data, including filename, date and other metadata, must be encrypted before any transfer takes place from a clients computer to the  cloud.

The current configuration does not achieve this goal.

**Comment by super3** [comment]
@utdrmac 

A) The filename and mimetype are included so the tools and applications know how to handle the data. If you upload a cat picture, the tools need to know it is a cat picture instead of a excel file so it can display it properly. This is especially important for future features like public buckets. 
B) This is already on the roadmap. 

@lunokhod PGP is really secure, its just impossible to use. We choose making the CLI tools usable at an early stage, obviously a fully featured application would encrypt the filename. 

The bridge is implemented as intended. It is up to the client to encrypt all metadata, not the bridge. Options:

1. Run your own bridge
2. Write a very nice issue asking for filename encryption in the CLI tool
3 Write a pull request to encrypt filenames in the CLI tool
4. Just wait because this is already in the roadmap
5. Write a fully featured application that has a metadata encryption scheme
6. Wait for someone else to write a fully featured application that has a metadata encryption scheme

**Comment by utdrmac** [comment]
@super3  "so the tools and applications" - What tools are you referring to? There is absolutely nothing about the entire storj architecture that needs to know I just uploaded a cat picture. All it needs to know is that I uploaded some data. This completely and unequivocally violates every privacy related notion about Storj's promises to be secure and encrypted and "zero-knowledge" (your words).

The bridge (Storj Inc, in this example) has this information available to them. A simple court ordered subpoena could force Storj Inc to turn over all uploaded content metadata for user xyz@domain.com. You have each users email address and associated buckets and bucket lists in plain-text.

This information could then be used in a court setting against a defendant. Filenames are one thing, but also having the file-type would be hard to dispute in a trial.

Public buckets should be a complete afterthought BEHIND security and protection; not in front of it. Sure, allow public buckets to have this information, given that the user has been prompted and made aware that any information uploaded to a public bucket is open for any to see. But under no circumstances should this be the default.

The bridge simply should not be storing this type of information; period. You have created a central repository of knowledge about the entire storj network and it's contents.

**Comment by super3** [comment]
You are confusing the service that Storj Labs offers and Storj the network. The network has no knowledge of any of this information. 

The bridge will store what you give it. The answer is not to give the information to the bridge if you don't want it to have it.

**Comment by utdrmac** [comment]
Right now, I don't have a choice. Using the official client, all data is given whether I want it to or not. There's no `--dont-send-metadata` flag when I upload files. Which, if existed, should be the default. And then, that flag wouldn't exist, but it's counterpart `--make-public` would exist which would then warn the user that data about this file is being uploaded in an unsecure manner and visible to all.

**Comment by bookchin** [comment]
It's trivial to encrypt the filename and mimetype with the same encryption key used to encrypt the data, so we'll just do it by default. The bridge doesn't use this information for anything but providing it back to the owner of the data - who sends it in the first place.

**Comment by utdrmac** [comment]
I understand that the bridge only stores this information so the client has access to it. But that just begs the question as to why bother sending it to the bridge in the first place. Why not just store that information locally in a DB within the client config dir alongside the keychain file? You still have the file hash in the bridge to create a link between local information and what the bridge needs to know to retrieve the file.

Let's please leave this issue open until after "...to encrypt the data, so we'll just do it by default." is implemented and really is the default.

**Comment by littleskunk** [comment]
Encrypte it here: https://github.com/Storj/core/blob/7575337a7b555e468606d5d51ab59f497e567b71/lib/bridge-client/index.js#L686-L687

(I can understand the idea but even as a paranoid user I don't have a problem with these information. As long as my file content is secure I don't care about filenames and mimetype. -> Low priority for me)

**Comment by utdrmac** [comment]
Having this little information is enough to prosecute someone for illegal activities. Imagine if you uploaded some video to Storj. While the data itself is encrypted, the metadata shows you uploaded a video/matroska mime-type of size 4509715661 with filename 'RogueOne.mkv' on Jan 3rd 2017 at 23:14:11. It's a simple subpoena to force Storj Inc to turn over this information for any and all users on their bridge.

There is just absolutely no need for this information to be present anywhere but locally to the client.

**Comment by littleskunk** [comment]
Do you think uploading illegal stuff with wrong file name will protect you? They will get you anyway as soon as you share the file with other users.

Anyway that is not the point. As you can see the issue is still open and will be solved. I posted the important code line in case someone likes to work on it.

**Comment by vevarm** [comment]
intresting discussion :). I think for the benifit of storj labs, the less you know the better. All kinds of entities may otherwise request filters of this and that in your network.

**Comment by braydonf** [comment]
**Important note from discussion**: The key to encrypt the filename and mimetype should not be the same key used for encrypting the file. The total number of mimetimes is limited which would make guessing the plaintext of the cyphertext trivial. And if the same key and aes mode (ctr) is used could be used to decrypt the file. The key for the filename and mimetype should be derived in a different way.

**Comment by braydonf** [comment]
**For reference**: File name encryption has been added to libstorj at: https://github.com/Storj/libstorj/blob/master/src/uploader.c#L1946-L1980

In summary the file name is encrypted by:
1. Generating the deterministic bucket key
2. Taking the left half of a sha512 hmac of the bucket key as the key using known constant
3. Taking the left half of a sha512 hmac of the bucket id and filename for the iv
4. Encrypted with AES-256-GCM
5. Digest (GCM_DIGEST_SIZE) is concatenated with iv (SHA512_DIGEST_SIZE/2) and ciphertext (variable length)

**Comment by super3** [comment]
@utdrmac @lunokhod @littleskunk Filename is now encrypted in the C library. When the JS library is refactored this will also support encrypted filenames. I am closing this as now there is a recommend tool and process that had not expose any identifiable metadata.
