### ISSUE TITLE
30 reps: Error: Failed to join network

### ISSUE THREAD

**Issue by CJClaude** [Storj/core#631]
Package Versions

Replace the values below using the output from storjshare --version.

 * daemon: 2.1.0, core: 6.0.14, protocol: 1.1.0

Replace the values below using the output from node --version.

6.9.2

Expected Behavior

Nodes continue to run.

Actual Behavior

Node routinely crashing with error message "Failed to join network"

Full log attached.

Steps to Reproduce

[node00.zip](https://github.com/Storj/core/files/717914/node00.zip)

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

...
...
...

**Comment by littleskunk** [comment]
Duplicate https://github.com/kadtools/kad/issues/89
