### ISSUE TITLE
Unlimited mirror creation

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#639]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
└─┬ storjshare-daemon@2.1.2
  └── storj-lib@6.0.15
```

Replace the values below using the output from `node --version`.

```
v6.9.4
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

I would expect 1 shard and 5 mirros. I should see these magic numbers on my logfile.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Last 9 hour stats of my farmer
```
root@storj:~/.config/storjshare/logs# grep 'sending OFFER' 188071ba7cfd974a9e47b59e24b0737ebf845db3.log | wc -l
190
root@storj:~/.config/storjshare/logs# grep 'successfully mirrored shard' 188071ba7cfd974a9e47b59e24b0737ebf845db3.log | wc -l
179
root@storj:~/.config/storjshare/logs# grep 'Shard upload completed' 188071ba7cfd974a9e47b59e24b0737ebf845db3.log | wc -l
9
root@storj:~/.config/storjshare/logs# grep 'not sending' 188071ba7cfd974a9e47b59e24b0737ebf845db3.log | wc -l
0
```

Every time I send an OFFER i receive a shard. The bridge doesn't stop at 5 mirrors. It creates as many mirrors as received OFFER. Looks more like 20 mirros for each shard. There is not one "to late for this shard" or anything like that.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run a farmer on loglevel debug for a few hours.
2. Take a look on the logfile and start counting messages.

**Comment by bookchin** [comment]
Correct, the bridge will accept up to 24 offers for a given shard, the first offer gets handed off to the client for upload, then the next 5 get mirrored one by one from the last successful transfer. The remaining offer received get queued for mirroring later in the event of the farmer failure in the first 6.

**Comment by littleskunk** [comment]
That doesn't explain the numbers I see on my logfile. 3^6 farmer can receive the contract PUBLISH. Not all of them will send an OFFER. Lets say the bridge will receive 100 OFFER. How likely is it that I am always on top 1-6? My slow NAS should be to late for most of the shards. I should get something beween 1 out of 4 and 1 out of 20 shards. At the moment I get every shard. Each time I send an OFFER i will receive a shard. That is very unlikely.

```
root@storj:~/.config/storjshare/logs# grep 'sending OFFER' 188071ba7cfd974a9e47b59e24b0737ebf845db3.log | grep -v '2017-01-31T15' | wc -l                                                                                                                        
269                                                                                                                                                                                                                                                              
root@storj:~/.config/storjshare/logs# grep 'Shard upload completed' 188071ba7cfd974a9e47b59e24b0737ebf845db3.log | grep -v '2017-01-31T15' | wc -l                                                                                                               
13                                                                                                                                                                                                                                                               
root@storj:~/.config/storjshare/logs# grep 'successfully mirrored shard' 188071ba7cfd974a9e47b59e24b0737ebf845db3.log | grep -v '2017-01-31T15' | wc -l                                                                                                          
244                                                                                                                                                                                                                                                              
root@storj:~/.config/storjshare/logs# grep 'authorizing data channel' 188071ba7cfd974a9e47b59e24b0737ebf845db3.log | grep -v '2017-01-31T15' | wc -l                                                                                                             
125
```

root@storj:~/.config/storjshare/logs# grep 'sending OFFER' 188071ba7cfd974a9e47b59e24b0737ebf845db3.log | grep -v '2017-01-31T15' | wc -l                                                                                                                        
269                                                                                                                                                                                                                                                              
root@storj:~/.config/storjshare/logs# grep 'Shard upload completed' 188071ba7cfd974a9e47b59e24b0737ebf845db3.log | grep -v '2017-01-31T15' | wc -l                                                                                                               
13                                                                                                                                                                                                                                                               
root@storj:~/.config/storjshare/logs# grep 'successfully mirrored shard' 188071ba7cfd974a9e47b59e24b0737ebf845db3.log | grep -v '2017-01-31T15' | wc -l                                                                                                          
244                                                                                                                                                                                                                                                              
root@storj:~/.config/storjshare/logs# grep 'authorizing data channel' 188071ba7cfd974a9e47b59e24b0737ebf845db3.log | grep -v '2017-01-31T15' | wc -l                                                                                                             
125
```

**Comment by littleskunk** [comment]
Something is wrong with ExchangeReport. My farmer has 13 Shard upload completed but didn't send the ExchangeReport for it. I have only `MIRROR_SUCCESS` and if they don't increase the counter the bridge will go on and create more and more mirrors. I will try to get some more informations.

**Comment by bookchin** [comment]
The chances that you will get a contract you send an OFFER for a actually pretty high. I think your math is off. Publications travel 3 hops with a parallelism of 3. This is 3 + 9 + 27 = *39*. Given that we accept the first *24* offers - if every node reached is _unique_, you have a 62% chance of getting the contract, however the likelihood of every node reached being unique is very low. This means that the absolute highest probability that you won't get a contract you send an offer for is 38% - in practice this is far lower as neighbors are very likely to relay the publication to nodes who have already received the publication from other neighbors.

As far as the exchange reporting goes, that's another issue so I will wait for any information you might have on that.

**Comment by littleskunk** [comment]
It should be 6 hops: https://github.com/Storj/core/blob/master/lib/constants.js#L18

I can grep the duplicate PUBLISH messages later. I wouldn't expect many of them but lets see.

ExchangeReport issue created here: https://github.com/Storj/core/issues/640

**Comment by littleskunk** [comment]
I uploaded some small files and list mirrors. You are correct. Only 5 mirrors created.
```
root@storj:~# storj list-mirrors 57449d89dc436e0a48f041aa 74678725b35bb0b14cf99cac                                                                                                                                                          
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]   
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]   Established
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]   -----------
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]   Shard: 0
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]   Hash: 97186ad43e138b5aa4e47e4235efd52369c6d912
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://192.0.191.14:58211/9755fe3dcafe325ccd21099a9372e8b0d7ee5c55
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://76.181.246.27:44596/dc810268c68943a7a8f86b7b379c3c567682aef5
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://node001.carpenter-farms.us:14001/09315c5b7892e18c3a780099bfda0857c33dc7bc
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://98.234.173.181:50137/9796545e40b1cf09c73763f991492cedbe372fbf
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://hashpeekpower.hopto.org:4102/095bf027715564b6989cf8fa60fc74dd33404aea
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]   
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]   Available
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]   ---------
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]   Shard: 0
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]   Hash: 97186ad43e138b5aa4e47e4235efd52369c6d912
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://client016.storj.dk:15094/97200716556e3e7cf5e6145d5159e8ab24be4496
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://symbiont.spdns.de:11155/092d092b075a17176c947499592465cfc207b84e
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://84.232.166.83:4005/96f6746b24c2d53b5e22135812992a4e5be00867
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://64.233.244.158:9983/0962e1d4712bbd8092f728d8672726a46d73c353
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://client021.storj.dk:15074/09d3ed446918aa0af4502f665337d5cfe563d4c5
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://client017.storj.dk:15025/9716f3ab476c924206e2c4318ee9f3f6ec9fa0ad
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://client021.storj.dk:15044/9735a147f5ed190d40f3adf88f42e677f9c187b2
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://client019.storj.dk:15050/975847afeb48df1099bb63308581cf84c4af1524
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://184.161.46.145:18952/2bcbf134a5c10d551775216a51c2334984e90cdf
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://86.127.194.47:3216/09ebdb7b5af2045b050da1d9e24bb283330de4f9
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://73.224.39.151:38926/9752677613291e89dc690a182d0731c6939b0a1d
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://89.176.149.45:37745/09acb9b2c79a182b1a20a516d6d44ec4ac042f84
 [Tue Jan 31 2017 18:57:36 GMT+0100 (CET)] [info]       storj://125.212.196.180:4000/0990977b46df2a70f80839aad768c5e5692140cd
```

Something must be wrong with the PUBLISH relay. In some cases only 4 or 5 farmer send an OFFER. That should never happen.
```
root@storj:~# storj list-mirrors 57449d89dc436e0a48f041aa 28e35784b7adbee9b677936a                                                                                                                                                                               
 [Tue Jan 31 2017 19:07:16 GMT+0100 (CET)] [info]   
 [Tue Jan 31 2017 19:07:16 GMT+0100 (CET)] [info]   Established
 [Tue Jan 31 2017 19:07:16 GMT+0100 (CET)] [info]   -----------
 [Tue Jan 31 2017 19:07:16 GMT+0100 (CET)] [info]   Shard: 0
 [Tue Jan 31 2017 19:07:16 GMT+0100 (CET)] [info]   Hash: c2b8dbf4830c2c6500b17f5ce4152a21ba27d68c
 [Tue Jan 31 2017 19:07:16 GMT+0100 (CET)] [info]       storj://client021.storj.dk:15044/c3414d82767b388f02adbb05512bc214547a73a8
 [Tue Jan 31 2017 19:07:16 GMT+0100 (CET)] [info]       storj://client013.storj.dk:15045/c2e0018f25e1593bc0be1fb9fdcb3e331db72a62
 [Tue Jan 31 2017 19:07:16 GMT+0100 (CET)] [info]   
 [Tue Jan 31 2017 19:07:16 GMT+0100 (CET)] [info]   Available
 [Tue Jan 31 2017 19:07:16 GMT+0100 (CET)] [info]   ---------
 [Tue Jan 31 2017 19:07:16 GMT+0100 (CET)] [info]   Shard: 0
 [Tue Jan 31 2017 19:07:16 GMT+0100 (CET)] [info]   Hash: c2b8dbf4830c2c6500b17f5ce4152a21ba27d68c
 [Tue Jan 31 2017 19:07:16 GMT+0100 (CET)] [info]       storj://client015.storj.dk:15098/c2b11d8e4274c229e4045708dcf1ae3d0a27fe80
```
