### ISSUE TITLE
Error: write ECONNRESET

### ISSUE THREAD

**Issue by Coinpiet** [Storj/core#659]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

-- storj@4.0.1

Replace the values below using the output from `node --version`.

v6.9.5

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Uploads run without errors.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
 [Wed Feb 22 2017 15:59:06 GMT+0100 (Mitteleuropäische Zeit)] [info]   Adding NodeID 7961ab384653cb21fd9a4976ee9b5916efd81fb0 to blacklist
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14)
```

**Comment by bookchin** [comment]
https://github.com/Storj/core-cli/issues/76
