### ISSUE TITLE
listFilesInBucket extra parameters

### ISSUE THREAD

**Issue by NicoNet** [Storj/core#673]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
/usr/local/lib
├── storj@4.0.1
└─┬ storjshare-cli@5.0.2
  └── storj@2.2.0
```

Replace the values below using the output from `node --version`.

```
v6.9.4
```

### Expected Behavior

There could be some additional parameters passed to listFilesInBucket.  Such as:

- Limit # of files returned
- Regex search of file names
- Other limiting factors, such as size, date uploaded

### Actual Behavior

I have over 100k files in a single bucket, and it takes a VERY long time to get a file listing.

**Comment by bookchin** [comment]
https://github.com/Storj/bridge/pull/384
