### ISSUE TITLE
Python 3.x support

### ISSUE THREAD

**Issue by computeronix** [Storj/core#694]
As a feature request, upgrade the core of Storj to support Python 3.x

Python 2 end of life in 2020 sometime
https://pythonclock.org/

Python 3.x supports additional platforms for example Windows Server Nano
https://social.technet.microsoft.com/wiki/contents/articles/34961.nano-server-deploying-python-3-x-interpreter.aspx

Overview Python 2.x vs 3.x
https://wiki.python.org/moin/Python2orPython3#fnref-4fcb00922956f144dafd52e4f75d82631e225d1b

**Comment by braydonf** [comment]
Python is a dependency of node-gyp https://github.com/nodejs/node-gyp and can not be resolved here.
