### ISSUE TITLE
All links to examples are broken

### ISSUE THREAD

**Issue by AlexeyALeonov** [Storj/core#718]
### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
open documentation https://storj.github.io/core/
click the first link to example and get first example
...
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
click link [Example 1 - Creating a User](https://github.com/Storj/core/blob/master/example/1-create-user.js) and got a error 404.
same for others
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. open documentation http://storj.github.io/core/
2. click link [Example 1 - Creating a User](https://github.com/Storj/core/blob/master/example/1-create-user.js) and got a error 404.
3. ...

**Comment by braydonf** [comment]
Needs to be fixed at storj.io repo

**Comment by bookchin** [comment]
@braydonf 

```
npm run make-docs
npm run publish-docs
```

**Comment by braydonf** [comment]
Updated
