### ISSUE TITLE
Unsatisfactory renter experience due to bandwidth throttling or malicous actor

### ISSUE THREAD

**Issue by ygshdeee** [Storj/core#73]
### scenario

During "Executing a Storage Contract" phase. (https://github.com/Storj/core/blob/master/doc/protocol-spec.md)

Then a renter uses the token that was provided by the farmer to open a data channel. The farmer can start accepting the data, then (A).Throttle bandwidth and oversubscribe their network connection or (B). drop data and request retransmission via TCP for an extended period of time effecting performing a DOS attack. 

Both Senarios produce an unsatisfactory customer experience. scenario (A). doesn't meet the renters expections as it was agreed in the speed criteria of the contract (https://github.com/Storj/core/blob/master/doc/contract-topics.md)

Scenario (B). requires the renter to wait or/and re-negitiate contract with alternative farmer. The renters payment is locked until first Audit request fails.

### Solution

Both scenarios could be managed in the renters favor by implementing a TTL (Time-To-Live) condition in the contract that voids contract if file transfer does not happen in an agreed amount of time.

**Comment by gordonwritescode** [comment]
Thanks for taking the time to put this together, this is an excellent point and we should work on implementing this when we get closer to our audits and payments milestones in the coming weeks.

**Comment by gordonwritescode** [comment]
Having given this some more thought in regard to how we might implement it, I don't think that anything needs to be done here in core. Seems to me that implementing clients should handle this.

After all a contract becomes null already when:

* The renter does not pay
* The farmer does not store/serve data

These conditions, I think, are broad enough to allow clients to determine the threshold appropriate for their users or allow their users to configure themselves. I don't think that anything else needs to be added to the contract. Any given storage contract published will have many farmers sending `OFFER`s back to the renter, which can be queued by clients and tried in sequence until one satisfies the renter's requirements. Farmers left with half-open contracts will already reap them on an interval.
