### ISSUE TITLE
New Shares Fail to Connect to Bridge

### ISSUE THREAD

**Issue by sibblegp** [Storj/core#740]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.2.3
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Newly created shares using storjshare-daemon should connect to the bridge and show "connected" in storjshare status
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Newly created shares using storjshare-daemon frequently cannot connect to the bridge and show this error in the logs:

{"level":"error","message":"Unable to connect to bridge: https://api.storj.io, reason: Bridge request failed (500)","timestamp":"2017-10-10T07:22:44.070Z"}
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Create a new share with the latest storjshare-daemon
2. Start the share
3. Share will not connect to bridge

**Comment by sibblegp** [comment]
I should also note that none of these nodes are getting any data, even the new ones that are connected to the bridge.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/bridge/issues/524 and https://github.com/Storj/bridge/issues/527
