### ISSUE TITLE
Handle incomplete contract directories

### ISSUE THREAD

**Issue by subwolf** [Storj/core#81]
After using ctrl-c to exit from the cli, upon restart the client will die with an error like this

````
{"level":"warn","message":"missing or empty reply from contact","timestamp":"2016-05-07T06:47:40.915Z"}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/root/.storj-farmer-cli/shards/b1e04d1d5fef22d4f107c7e1fb20d30e14e399d0/challenges'
    at Error (native)
````

I have to delete the directory to get the client to work again. Would be nice to have that handled automatically when you exit the program, say by cleaning up any incomplete contract directories to avoid the error in future.

**Comment by gordonwritescode** [comment]
#84
