### ISSUE TITLE
Close open files to avoid crash

### ISSUE THREAD

**Issue by subwolf** [Storj/core#82]
My Synology NAS allows 1,024 open files by default. Running the CLI would generate a 'too many open files' error within an hour or two, I think files were being opened as contracts were accepted and not closed again afterwards.

I've increased the open files limit to 8192, but watching the open files count climb regularly, I fear this is a problem that will not go away until the correct fixes are in place.

**Comment by subwolf** [comment]
Ran a netstat call pulling out the IP address connected to...

````
root@subwolf-nas:/# netstat -an | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | grep -v 192\.168 | grep -v 127\.0 | grep -v 0\.0 | wc -l
11243
root@subwolf-nas:/# netstat -an | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | grep -v 192\.168 | grep -v 127\.0 | grep -v 0\.0 | uniq | wc -l
8947
````

So its open connections as well as open files.

**Comment by subwolf** [comment]
````
root@subwolf-nas:/# netstat -an | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | grep -v 192\.168 | grep -v 127\.0 | grep -v 0\.0 | sort -nr | uniq -c
   2677 162.243.72.56
    144 138.201.13.159
     54 128.171.159.70
   2633 108.238.244.144
      1 104.196.133.93
      1 104.172.19.215
   3003 91.138.6.120
     27 88.164.182.121
   1151 87.64.100.36
     43 83.140.11.247
      2 77.250.97.61
      2 54.93.90.7
      1 54.93.177.70
      1 37.35.96.44
     12 37.35.96.35
    558 37.35.96.34
      1 37.35.96.31
      1 37.35.96.23
      1 37.35.96.21
    307 37.35.96.13
     22 37.35.96.12
    509 37.35.96.11
     64 5.9.69.118
````

**Comment by subwolf** [comment]
162.243.72.56 (2677 connections) is api.storj.io
108.238.244.144 (2633 connections) is a.storj.eu

Thats guesswork.

**Comment by gordonwritescode** [comment]
See #84 for the first part of this issue. The second part will need some more investigating, but I suspect that it's a bug somewhere in the datachannels or transport adapter.

**Comment by subwolf** [comment]
If the open files limit is not hit first, open network connections will do it, more than 65,535 and it's toast.

**Comment by gordonwritescode** [comment]
For reference the open file issue comes from https://github.com/Storj/core/blob/master/lib/storage/adapters/fs.js#L94 - where we don't close the file descriptors later on. I'm guessing this dies when the shard reaper scans for dead contracts and as a side effect opens the file descriptors for each shard.
