### ISSUE TITLE
NotFoundError: Key not found in database

### ISSUE THREAD

**Issue by lunokhod** [Storj/core#96]
Since starting storjshare (0.6.13, farmer 3.0.2) this morning, it has crashed twice with the following ouput
~~~~
NotFoundError: Key not found in database [ed06117e1d9fb7ad2dc45c3f6889e19e5d5a9fee.data 129]
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/levelup/lib/levelup.js:217:15
NotFoundError: Key not found in database [ed06117e1d9fb7ad2dc45c3f6889e19e5d5a9fee.data 129]
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/levelup/lib/levelup.js:217:15
~~~~
Otherwise, seams to be working fine.

**Comment by gordonwritescode** [comment]
Do you have a longer stack trace you can share?

**Comment by gordonwritescode** [comment]
It's coming from here: https://github.com/Storj/core/blob/master/lib/storage/adapters/level/filestore.js#L71

I will add better error handling, but this should only happen if a shard did not get completely stored, so we want to make sure it's handled appropriately.

**Comment by gordonwritescode** [comment]
Actually an 8 mb shard stored in 64k chunks (like they are):

```
8388608 ÷ 65536= 128
```

And they key lookup that's failing is 129 - which is correct. However, we are supposed to be storing a null value at the last index to signal EOF, so that must be where this is failing. 

I'll issue a fix on Tuesday.

**Comment by gordonwritescode** [comment]
The good news is that you are successfully storing and delivering shards (unfortunately at the expense of your process).
