### ISSUE TITLE
PUBLISH spam messages

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#99]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
/usr/local/lib
└─┬ storjshare-cli@3.0.2
  └── storj@0.6.13
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

https://github.com/Storj/core/blob/master/doc/protocol-spec.md
Once a node has a view of the publications to which it's neighbors are subscribed, it is capable of issuing a PUBLISH message containing a topic and some content. This message is sent to the node's nearest neighbors, who then relay it to their neighbors based upon their own view of nearby subscriptions.

Upon receipt of a PUBLISH message, a node must first check to make sure it has not already received the publication. This is done by caching the uuid of received publications. If the node has already seen the publication, it should respond with an error message indicating such. The node should also make sure that the publication has not expired by checking the ttl against the current UNIX time.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

The real network is full of PUBLISH spam messages. 

To find out why I setup 4 isolated nodes connected to each other. One node has no seed in his config-> _listenForTunnelers will not be called (no 15 minute timeout for this node). 
After 15 minutes the first node will start the first spam round with 9 PUBLISH messages. A few minutes later the second Node will do the same.

```
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.13\",\"address\":\"192.168.123.124\",\"port\":6000,\"nodeID\":\"0d66fa31d43faa8388325c4f1e78b6dc91355048\",\"lastSeen\":1463348428125}","timestamp":"2016-05-15T21:40:28.125Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.13\",\"address\":\"192.168.123.124\",\"port\":4000,\"nodeID\":\"b08490845870037e7e0d723889931f635e890380\",\"lastSeen\":1463348428148}","timestamp":"2016-05-15T21:40:28.148Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.13\",\"address\":\"192.168.123.100\",\"port\":4000,\"nodeID\":\"b408aeb67291e4d1994a95394e674c09eb683d3c\",\"lastSeen\":1463348428163}","timestamp":"2016-05-15T21:40:28.163Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.13\",\"address\":\"192.168.123.124\",\"port\":4000,\"nodeID\":\"b08490845870037e7e0d723889931f635e890380\",\"lastSeen\":1463348428237}","timestamp":"2016-05-15T21:40:28.237Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.13\",\"address\":\"192.168.123.124\",\"port\":6000,\"nodeID\":\"0d66fa31d43faa8388325c4f1e78b6dc91355048\",\"lastSeen\":1463348428244}","timestamp":"2016-05-15T21:40:28.244Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.13\",\"address\":\"192.168.123.124\",\"port\":4000,\"nodeID\":\"b08490845870037e7e0d723889931f635e890380\",\"lastSeen\":1463348428275}","timestamp":"2016-05-15T21:40:28.275Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.13\",\"address\":\"192.168.123.100\",\"port\":4000,\"nodeID\":\"b408aeb67291e4d1994a95394e674c09eb683d3c\",\"lastSeen\":1463348428293}","timestamp":"2016-05-15T21:40:28.293Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.13\",\"address\":\"192.168.123.124\",\"port\":6000,\"nodeID\":\"0d66fa31d43faa8388325c4f1e78b6dc91355048\",\"lastSeen\":1463348428308}","timestamp":"2016-05-15T21:40:28.308Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.13\",\"address\":\"192.168.123.124\",\"port\":6000,\"nodeID\":\"0d66fa31d43faa8388325c4f1e78b6dc91355048\",\"lastSeen\":1463348428314}","timestamp":"2016-05-15T21:40:28.314Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.13\",\"address\":\"192.168.123.124\",\"port\":4000,\"nodeID\":\"b08490845870037e7e0d723889931f635e890380\",\"lastSeen\":1463348428337}","timestamp":"2016-05-15T21:40:28.337Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.13\",\"address\":\"192.168.123.100\",\"port\":4000,\"nodeID\":\"b408aeb67291e4d1994a95394e674c09eb683d3c\",\"lastSeen\":1463348428351}","timestamp":"2016-05-15T21:40:28.351Z"}
```

### Possible Abuse

Now lets abuse the 4 nodes. I join with Bob node. Bob will send PUBLISH spam messages every second (or less than one second). He only need to send them to one node in order to use minimal CPU time and network traffic. That node will relay the message to every other node. The bigger the network the more effect bob will have with his minimal setup.
The meanwhile Alice will ignore all PUBLISH messages and sign every contract. The network is busy relaying the spam messages inclusive massive timeouts and Alice can get all contracts.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Setup at least 3 isolated nodes connected to each other.
2. Wait 15 Minutes and count the PUBLISH messages. Each node will send out (N - 1)² PUBLISH messages.
3. Calculate the PUBLISH messages for each node in the real network with lets say 10 nodes. Each node has to send 81 PUBLISH messages every 15 minutes. 31 nodes 900 PUBLISH messages. It is increasing very fast.
4. Start bob node on the real network. 10 nodes = 81 PUBLISH messages every second. 31 nodes = 900 messages ever second.
5.) Get some popcorn and wait for the timeout messages.

**Comment by gordonwritescode** [comment]
Must be a bug with the tunnel announcement. Every 15 minutes a node will announce it's tunnel state (whether or not it has available tunnels). https://github.com/Storj/core/blob/master/lib/network/index.js#L354

**Comment by gordonwritescode** [comment]
The 4 nodes started at the same time announce to each other their state which each relay back to each other. Maybe we solve this by handling the relay of those types of announcements differently.

**Comment by gordonwritescode** [comment]
Could also be a bug in https://github.com/kadtools/kad-quasar. 

Possibly related: https://github.com/kadtools/kad/issues/55#issuecomment-218444310

**Comment by littleskunk** [comment]
I started the nodes with at least 1 minutes delay. The logoutput was the 15 minute trigger of only one node. All other nodes (except the one that never called _listenForTunnelers) did the same some minutes later.

The second kad issue would only reduce the number for spam messages from (N - 1)² to (G*(G + 1))/2. Gauss sum formula with G = (N - 1)
Bob would still be very effective. 31 nodes will not send out 900 messages but 465 messages. It can still be abused.

**Comment by gordonwritescode** [comment]
Perhaps one of the following, then:

1. Remove the announce interval altogether and revert to only announcing tunnel state when it changes (I have tunnels or I'm out of tunnels).
2. Update the quasar implementation to include the node IDs of the contacts it *plans* to send the initial publication to so that the initial recipients do not relay it to each other. 

Doing both might be desirable. Its also important to note that publications are flagged with a TTL so that it won't be relayed after a certain amount of time, so there is a limit to how much of the network can be effectively spammed. The general issue with this specific problem is that all nodes are subscribed to the tunnel announcements so quasar is much less effective at efficient relay in the first place.

We could reduce the number of subscribers to tunnel announcements to nodes that are public (and not tunneled). That would reduce the size of the gravity wells for subscription and may help the issue too, since tunnels are generally requested from an initial public seed (who will ask it's neighbors for tunnels if it doesn't have any). 

Another approach which might be less desirable is to have a federated directory system where tunneling nodes can announce to one of these directory servers its state instead of publishing a message to the network. Then a FIND_TUNNEL message would trigger a local check for tunnels then follow with a request to a directory server for other known tunnels instead of iteratively asking neighbors.

**Comment by littleskunk** [comment]
Solution 1 would not stop bob spam node. This alone will not fix the issue but as additional solution it would be awesome.
Solution 2 would reduce the number of PUBLISH messages to a minimum. I like that idea. Bob spam node should not be able to shutdown the network.
Solution 3 (subscription only for public nodes) is a good idea as well but I see one possible problem. I assume every node will send the PUBLISH messages only to neighboor noods. What should a public node do if only tunnel nodes are around it. It would be isolated and would not receive any PUBLISH message.
Solution 4 (directory server) is the API node at the moment. All GUI user are sending there FIND_TUNNEL message to only one API node. We could call it a directory server already. The network would still work if public nodes would send PUBLISH messages only to the directory server.


I would prefer Solution 4+1 or 2+1
